### ISSUE TITLE
Upgraded to Client: v2.5.5 (api v3) and now telepresence connect can't find the kubeconfig

### ISSUE THREAD

**Issue by tmododragon** [telepresenceio/telepresence#2523] opened 2022-04-12 14:50 UTC
**Describe the bug**
Upgraded to Client: v2.5.5 (api v3) and now `telepresence connect` can't find the kubeconfig

```
telepresence: error: connector.Connect: stat /Users/thomasmoles/.kube/config:/Users/thomasmoles/.kube/kubeconfig: no such file or directory

See logs for details (2 errors found): "/Users/thomasmoles/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md
```
This worked with my previous version 2.4.10

**To Reproduce**
1. When I run 'telepresence connect'
2. I see:
```
telepresence: error: connector.Connect: stat /Users/thomasmoles/.kube/config:/Users/thomasmoles/.kube/kubeconfig: no such file or directory

See logs for details (2 errors found): "/Users/thomasmoles/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md
```

**Expected behavior**
I expected telepresence to connect successfully

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8474013/telepresence_logs.zip)

**Comment by tmododragon** [comment] 2022-04-12 15:04
I think the root cause is that telepresence is no longer able to handle multiple kubeconfigs. When I removed the config I was not currently using from `KUBECONFIG` env var the issue was resolved.

**Comment by thallgren** [comment] 2022-04-13 03:56
Closing as duplicate of #2425

**Closed as completed by thallgren** 2022-04-13 03:56 UTC
