### ISSUE TITLE
Running into an error: `daemon service did not start` on M1 Chip enabled MacBook

### ISSUE THREAD

**Issue by Damans227** [telepresenceio/telepresence#1980] opened 2021-08-11 01:11 UTC
When trying to follow the steps given in this [tutorial](https://www.getambassador.io/docs/telepresence/latest/quick-start/demo-node/)  on a new MacBook with M1 chip, I am running into an issue where telepresence daemon service wont start and throw the following error: 

`telepresence: error: daemon service did not start (see "/root/.cache/telepresence/logs/daemon.log" for more info)`

**Environment Details:**

OS: macOS Big Sur
Hardware: Mac Mini (M1, 2020)
Chip: Apple M1
RAM: 8 Gigs

**Docker Engine:**
v20.10.7

**Comment by petermant** [comment] 2021-08-11 07:56
This looks the same as 1916 - there's a workaround until it gets fixed, where you run the command by hand:
https://github.com/telepresenceio/telepresence/issues/1916#issuecomment-886749080

**Comment by Damans227** [comment] 2021-08-13 16:58
I see, thanks for sharing. I will try running the daemon service manually and verify if it comes up.

**Comment by thallgren** [comment] 2021-08-17 07:46
Closing as duplicate of #1916

**Closed as completed by thallgren** 2021-08-17 07:46 UTC
