### ISSUE TITLE
Multiple files in KUBECONFIG not supported

### ISSUE THREAD

**Issue by rrva** [telepresenceio/telepresence#2457] opened 2022-03-08 03:00 UTC
**Describe the bug**

Multiple files in KUBECONFIG not supported

**To Reproduce**

1. Set the environment variable KUBECONFIG to point to multiple files: 

export KUBECONFIG=$HOME/.kube/foo:$HOME/.kube/bar

2. Run telepresence connect

```connector.Connect: stat /Users/myuser/.kube/foo:/Users/myuser/.kube/bar: no such file or directory```

**Expected behavior**

Picks up kubernetes clusters from both files. 

**Versions (please complete the following information):**

telepresence version
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)

OS version:

macOS 12.2.1

**Comment by thallgren** [comment] 2022-03-11 09:07
Closing as duplicate of #2425

**Closed as completed by thallgren** 2022-03-11 09:07 UTC
