### ISSUE TITLE
Unable to reach services with non-standard cluster naming (svc.cluster.local)

### ISSUE THREAD

**Issue by Martin-4Spaces** [telepresenceio/telepresence#2611] opened 2022-05-24 12:50 UTC
My kubernetes provider has renamed `cluster.local` to something else, ex. `customer1.local`.
I can resolve dns without issues when working inside the cluster without telepresence.
But when using telepresence (v2), I cannot resolve the host when `customer1.local` is suffixed.

**Comment by thallgren** [comment] 2022-06-01 16:08
I finally found some time to test this on my macOS powerbook. I cannot reproduce it. Using none standard cluster domain names works OK for me.

Would it be possible for you to convey the logs from the root daemon and the traffic-manager during the time when the lookup fails? Preferably after invoking `telepresence loglevel debug`.

**Comment by thallgren** [comment] 2024-02-04 15:15
Closing, as no additional info was provided.

**Closed as completed by thallgren** 2024-02-04 15:15 UTC
