### ISSUE TITLE
Table of compartible versions for traffic-manager and traffic-agent

### ISSUE THREAD

**Issue by SomeAkk** [telepresenceio/telepresence#2949] opened 2022-12-20 15:47 UTC
Where i can look which traffic-managers compartible with traffic-agent 1.13.3?

**Comment by thallgren** [comment] 2022-12-21 11:14
We strive to make all versions of the traffic-manager compatible with all versions of the traffic-agent. There's one exception. A traffic-manager < 2.6.0 will need traffic-agent 1.11.4.
The traffic-manager will negotiate the correct version of the traffic-agent with the cloud, unless you are in an air-gapped environment.

Closing this, as it's not a bug report or a feature request.

**Closed as completed by thallgren** 2022-12-21 11:14 UTC
