### ISSUE TITLE
Telepresence 2.7.x broke --docker-run when using -it flag

### ISSUE THREAD

**Issue by jlitola** [telepresenceio/telepresence#2724] opened 2022-08-11 10:36 UTC
**Describe the bug**

When running intercept with Docker with `-it` flag for interactive session, the intercept fails with with error. Tested this both with 2.7.0 and 2.7.1 with similar results. With 2.6.8 (and before) this results in successful intercept.

**To Reproduce**

```
❯ telepresence intercept --mount false --namespace test test --port 8080:80:http --docker-run -- -it --rm ubuntu:20.04 /bin/bash
Using Deployment test
intercepted
    Intercept name         : test-test
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Intercepting           : all TCP requests
the input device is not a TTY
telepresence: error: /usr/local/bin/docker docker run --dns-search tel2-search --env-file /var/folders/7z/929w0qdn5117mcd0mj63lh_c0000gn/T/tel-1562725983.env --name intercept-test-test-8080 -p 8080:80 -it --rm ubuntu:20.04 /bin/bash: exited with 1
```

**Versions (please complete the following information):**

```
> telepresence version
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)

> uname -a
Darwin Taltta.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64
```

**Comment by mruell** [comment] 2022-08-11 10:50
Getting the exact same error

**Comment by cindymullins-dw** [comment] 2022-10-18 17:49
Hi @jlitola  and @mruell , this was fixed in [2.7.3](https://www.getambassador.io/docs/telepresence/latest/release-notes/#2.7.3).  When you get a chance to upgrade could you please let us know if that works better?

**Comment by mruell** [comment] 2022-10-18 18:38
Hi @cindymullins-dw 

unfortunately with the latest version it still does not work :/

```
telepresence intercept test-xyz \
	--local-only \
	--no-report \
	--docker-run \
	-- \
	--rm \
	-it \
	-e start_xdebug= \
	-e APP_ENV=telepresence \
	-e PHP_IDE_CONFIG="serverName=telepresence" \
	--expose 9001 \
	test-xyz \
	/bin/bash
```

Error:

```
	the input device is not a TTY
telepresence: error: /usr/local/bin/docker docker run --env-file /var/folders/nz/9g2c0zfx38jg4_46fg20qs6c0000gn/T/tel-3092064848.env --dns-search tel2-search --name test-xyz-bash-0 --rm -it -e start_xdebug= -e APP_ENV=telepresence -e PHP_IDE_CONFIG=serverName=telepresence --expose 9001 test-xyz /bin/bash: exited with 1
```

Do you have an idea what could cause this?
```
 (master *)$ telepresence version
Client: v2.8.2 (api v3)
Root Daemon: v2.8.2 (api v3)
User Daemon: v2.8.2 (api v3)
```

With `2.6.8` everything is working

Thanks a lot in advance and best,
Marvin

**Comment by jlitola** [comment] 2022-10-19 06:58
Hi @cindymullins-dw,

I can confirm @mruell's observation. Still having the same issue with 2.8.2.

**Comment by mruell** [comment] 2022-10-19 11:34
@cindymullins-dw 

we both seem to use Mac, could this cause the issue?

```
$ uname -a

Darwin XXX 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

**Comment by mruell** [comment] 2022-11-15 20:49
I can comfirm that the issue is gone in `2.9.0`

Thanks a lot!

**Closed as completed** 2022-11-16 11:39 UTC
