### ISSUE TITLE
[v2] Connection failure after 60s since first traffic sent to intercepted pod

### ISSUE THREAD

**Issue by frankgu968** [telepresenceio/telepresence#1933] opened 2021-07-28 01:13 UTC
To reproduce the error, we have to trigger an initial proxied connection (ie. by hitting the service or by hitting any other cloud services in a connected shell). After the initial connection, if we continue to send proxied traffic within 60s between each request, then the connection is stable and continues to work. However, if we wait for more than precisely 60s between proxied requests, then we get a "503 Service Unavailable" error (from Redis).

This only happens for proxying traffic to other services that the target intercept is connecting to (ie. a database or cache). Proxy traffic to the intercepted service itself works without issue over long periods of time.

We are seeing this for both Mac (non-M1) and Linux systems; untested on windows.

Nothing of particular interest in the logs (set to trace for connector and daemon):
```
# daemon.log
2021/07/23 10:41:50.8093 info    daemon/watch-cluster-info : Adding service subnet 10.32.0.0/16 (from pkg/client/daemon/tunrouter.go:261)
2021/07/23 10:41:50.8094 info    daemon/watch-cluster-info : Adding pod subnet 10.1.128.0/18 (from pkg/client/daemon/tunrouter.go:267)
2021/07/23 10:41:53.2720 info    daemon/watch-cluster-info : Adding service subnet 10.32.0.0/16 (from pkg/client/daemon/tunrouter.go:261)
2021/07/23 10:41:53.2720 info    daemon/watch-cluster-info : Adding pod subnet 10.1.128.0/18 (from pkg/client/daemon/tunrouter.go:267)
2021/07/23 10:42:04.9747 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:42:04.9750 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:42:04.9750 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:42:18.2877 debug   daemon/server-router/TUN reader : <- TUN icmp <REDACTED_IPV6> -> ff02::2, type router solicitation, code 0 (from pkg/client/daemon/tunrouter.go:444)
2021/07/23 10:42:20.0831 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:42:20.0834 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:42:20.0836 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:42:35.1824 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:42:35.1826 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:42:35.1827 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:42:44.3226 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:34492 -> 10.1.128.60:5432, sq 2673589531, an 1710859470, wz 501, len 284, flags=ACK,PSH (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:42:44.3249 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.128.60:5432 -> 10.1.128.0:34492, sq 1710859470, an 2673589815, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:42:44.3252 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:34492 -> 10.1.128.60:5432, len 284 (from pkg/tun/tcp/tmgr.go:76)
2021/07/23 10:42:50.2870 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:42:50.2875 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:42:50.2876 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:43:05.3911 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:43:05.3914 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:43:05.3915 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
2021/07/23 10:43:20.4959 debug   daemon/server-router/TUN reader : <- TUN tcp 10.1.128.0:48118 -> 10.1.139.137:44393, sq 227665212, an 53731119, wz 501, len 0, flags=ACK (from pkg/tun/tcp/handler.go:570)
2021/07/23 10:43:20.4960 debug   daemon/server-router/TUN reader : -> MGR tcp 10.1.128.0:48118 -> 10.1.139.137:44393, code KEEP_ALIVE (from pkg/tun/tcp/tmgr.go:129)
2021/07/23 10:43:20.4961 debug   daemon/server-router/TUN writer : -> TUN tcp 10.1.139.137:44393 -> 10.1.128.0:48118, sq 53731119, an 227665213, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:317)
```

This issue seems to only affect persistently established connections like connected Postgres pools and Redis clients. If I connect a Pg session and take more than 60s between my requests, the connection fails (503 on Redis, and hang on Pg pool). But in the same connected shell, I can quit and reconnect without issue.

**Comment by frankgu968** [comment] 2021-08-11 16:29
Update: tested this on 2.4.0 and the behavior is the same

**Comment by frankgu968** [comment] 2021-08-15 02:34
After running some more tests, I've noticed that whenever the disconnection/hang behavior is observed on the intercept, some traffic to MGR (traffic manager?) does not get any response: 
```
2021/08/13 17:47:51.6405 debug   daemon/server-router/TUN writer : -> TUN tcp 10.127.138.144:42373 -> 10.127.128.0:50346, sq 1957971358, an 685933049, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:316)
2021/08/13 17:47:56.2162 debug   daemon/server-router/TUN reader : <- TUN tcp 10.127.128.0:46818 -> 10.127.171.103:5432, sq 3476541052, an 527558082, wz 501, len 29, flags=ACK,PSH (from pkg/tun/tcp/handler.go:569)
2021/08/13 17:47:56.2163 debug   daemon/server-router/TUN writer : -> TUN tcp 10.127.171.103:5432 -> 10.127.128.0:46818, sq 527558082, an 3476541081, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:316)
2021/08/13 17:47:56.2163 debug   daemon/server-router/TUN reader : -> MGR tcp 10.127.128.0:46818 -> 10.127.171.103:5432, len 29 (from pkg/tun/tcp/tmgr.go:76)
```

For reference, a successful request looks like this: 
```
2021/08/13 17:46:50.2456 debug   daemon/server-router/TUN reader : <- TUN tcp 10.127.128.0:46818 -> 10.127.171.103:5432, sq 3476541023, an 527556799, wz 501, len 29, flags=ACK,PSH (from pkg/tun/tcp/handler.go:569)
2021/08/13 17:46:50.2457 debug   daemon/server-router/TUN writer : -> TUN tcp 10.127.171.103:5432 -> 10.127.128.0:46818, sq 527556799, an 3476541052, wz 2048, len 0, flags=ACK (from pkg/client/daemon/tunrouter.go:316)
2021/08/13 17:46:50.2458 debug   daemon/server-router/TUN reader : -> MGR tcp 10.127.128.0:46818 -> 10.127.171.103:5432, len 29 (from pkg/tun/tcp/tmgr.go:76)
2021/08/13 17:46:50.3185 debug   daemon/server-router/MGR stream : <- MGR tcp 10.127.171.103:5432 -> 10.127.128.0:46818, len 1283 (from pkg/connpool/stream.go:62)
```

No other relevant log entries are present in the `connector.log` and the `traffic-agent` logs. 

Given the precision of 60s and the lack of explicit deadlines, it is highly possible that this is due to a default gRPC timeout.

**Comment by thallgren** [comment] 2021-08-17 06:09
Closing as duplicate of #1993

**Closed as completed by thallgren** 2021-08-17 06:09 UTC
