### ISSUE TITLE
error in running telepresence

### ISSUE THREAD

**Issue by kesavkolla** [telepresenceio/telepresence#970] opened 2019-03-29 11:41 UTC
### What were you trying to do?

ran telepresense command

### What did you expect to happen?

Got error

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.97`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.14.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux kesavmatebook 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 101, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
5efb1b91
   8.6 TEL | [11] Capturing: kubectl --context kubernetes-admin@kubernetes --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1553859591-3182566-9277 --image=datawire/telepresence-k8s:0.97 --labels=telepresence=29a3baea85aa463e944933725efb1b91
   9.2  11 | kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
   9.4  11 | deployment.apps/telepresence-1553859591-3182566-9277 created
   9.4 TEL | END SPAN deployment.py:61(create_new_deployment)    1.7s
   9.4 TEL | BEGIN SPAN remote.py:154(get_remote_info)
   9.4 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   9.4 TEL | [12] Capturing: kubectl --context kubernetes-admin@kubernetes --namespace default get deployment -o json --export --selector=telepresence=29a3baea85aa463e944933725efb1b91
  10.1 TEL | END SPAN remote.py:78(get_deployment_json)    0.6s

```

**Comment by richarddli** [comment] 2019-03-29 11:42
dupe of 966

**Closed by richarddli** 2019-03-29 11:42 UTC
