### ISSUE TITLE
Telepresence doesn't work if localhost doesn't resolve

### ISSUE THREAD

**Issue by thedevelopnik** [telepresenceio/telepresence#749] opened 2018-08-22 18:04 UTC
### What were you trying to do?

Run the `$ telepresence` command. This was freshly installed on a new machine.

### What did you expect to happen?

it would create a connection into the cluster

### What happened instead?

I get the traceback below.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.92`
Python version: `3.7.0 (default, Aug 17 2018, 21:14:48) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.10.5-gke.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 64, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/connect/__init__.py", line 158, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/connect/__init__.py", line 115, in connect
    ssh.wait()
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/connect/ssh.py", line 82, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
in/true
  37.2 TEL | [125] exit 255 in 0.02 secs.
  37.5 TEL | [126] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 57989 telepresence@localhost /bin/true
  37.5 TEL | [126] exit 255 in 0.02 secs.
  37.7 TEL | [127] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 57989 telepresence@localhost /bin/true
  37.8 TEL | [127] exit 255 in 0.02 secs.
  38.0 TEL | [128] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 57989 telepresence@localhost /bin/true
  38.0 TEL | [128] exit 255 in 0.02 secs.
  38.3 TEL | [129] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 57989 telepresence@localhost /bin/true
  38.3 TEL | [129] exit 255 in 0.02 secs.
  38.6 TEL | [130] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 57989 telepresence@localhost /bin/true
  38.6 TEL | [130] exit 255 in 0.02 secs.

```

**Comment by ark3** [comment] 2018-08-22 18:35
Could you please post the full telepresence.log as a Gist? Thank you!

**Comment by thedevelopnik** [comment] 2018-08-22 18:45
https://gist.github.com/thedevelopnik/19e04ee6e166205db8dda0c3f13fd8d5

**Comment by ark3** [comment] 2018-08-22 19:19
We debugged this on [Slack](https://d6e.co/slack). The summary is that there was no entry for localhost in /etc/hosts. Telepresence should notice this and complain rather than crashing mysteriously.

**Comment by SOberhoff** [comment] 2018-09-13 16:33
I'm running into the same issue. Can you elaborate on what the issue is and how to fix it?

**Comment by ark3** [comment] 2018-10-31 18:38
See also #783

**Comment by ark3** [comment] 2018-12-13 22:19
I replaced localhost with 127.0.0.1 in #868. Helpers may still fail if localhost does not resolve, but at least Telepresence itself should be okay. I'll close this, but please re-open if it's appropriate.

**Closed by ark3** 2018-12-13 22:19 UTC
Labels: crash instead of error, good first issue
