### ISSUE TITLE
[v2] Can't uninstall traffic-agent

### ISSUE THREAD

**Issue by andrewnazarov** [telepresenceio/telepresence#1658] opened 2021-04-11 13:41 UTC
After upgrading to v2.1.2 it's no longer possible to uninstall traffic-agent. Same problem with the most recent v2.1.4

Here I've got traffic-agent installed (the older version was in use back then):
```
> telepresence list
...
core-instance-frontend                    : ready to intercept (traffic-agent already installed)
...
```

Trying to uninstall this:
```
telepresence uninstall --all-agents
telepresence: error: unable to locate port http in container frontend in Deployment core-instance-frontend.core
```

A yaml file of a Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "133"
    meta.helm.sh/release-name: core-instance-frontend
    meta.helm.sh/release-namespace: core
    telepresence.getambassador.io/actions: '{"version":"2.0.3","ReferencedService":"core-instance-frontend","hide_container_port":{"container_name":"frontend","port_name":"http","hidden_name":"tel2mv-http"},"add_traffic_agent":{"container_port_name":"http","container_port_proto":"TCP","app_port":3000,"image_name":"docker.io/datawire/tel2:2.0.3"}}'
  creationTimestamp: "2021-01-12T09:52:52Z"
  generation: 133
  labels:
    app.kubernetes.io/instance: core-instance-frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    helm.sh/chart: frontend-2.23.0
  name: core-instance-frontend
  namespace: core
  resourceVersion: "273497088"
  selfLink: /apis/apps/v1/namespaces/core/deployments/core-instance-frontend
  uid: e366d745-7f92-47c7-81a7-c19584ff9c6d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: core-instance-frontend
      app.kubernetes.io/name: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: bad3554a2b070a8c70b03df42a17acafcf28abf530a71fd000867977d197cac2
        fluentbit.io/exclude: "false"
      creationTimestamp: null
      labels:
        app.kubernetes.io/application: XXXX
        app.kubernetes.io/instance: core-instance-frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/version: XXXX-21193-cb6d96fa
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: core-instance-frontend
        image: eu.gcr.io/XXXX/frontend:XXXX-21193-cb6d96fa
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: frontend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        startupProbe:
          failureThreshold: 90
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - agent
        env:
        - name: TELEPRESENCE_CONTAINER
          value: frontend
        - name: LOG_LEVEL
          value: debug
        - name: AGENT_NAME
          value: core-instance-frontend
        - name: AGENT_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: AGENT_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: APP_PORT
          value: "3000"
        - name: MANAGER_HOST
          value: traffic-manager.ambassador
        image: docker.io/datawire/ambassador-telepresence-agent:1.3.0
        imagePullPolicy: IfNotPresent
        name: traffic-agent
        ports:
        - containerPort: 9900
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/stat
            - /tmp/agent/ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-25T00:29:52Z"
    lastUpdateTime: "2021-03-25T00:29:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-12T09:52:52Z"
    lastUpdateTime: "2021-03-25T21:43:58Z"
    message: ReplicaSet "core-instance-frontend-6d8758cfb8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 133
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by aliusmiles** [comment] 2021-04-15 10:23
I've seen this "unable to locate port" error plus "object does not contain 'traffic-annotations' volume", but fixed by cleaning up all telepresence elements for k8s cluster then just running telepresence again:

```sh
kubectl delete ns ambassador
kubectl edit deploy/name # then manually remove telepresence-agent container
```

looks like it's necessary to run `telepresence uninstall --everything` before updating it. Might be worth mentioning in upgrade docs perhaps?

**Comment by LukeShu** [comment] 2021-04-15 15:43
With 2.1.5 there _is_ an issue with removing agents installed by older versions (https://github.com/telepresenceio/telepresence/issues/1666 / https://github.com/telepresenceio/telepresence/pull/1667), but otherwise, the upgrade is a red herring.

The issue is that something else overwrote what Telepresence did, and so it's in a weird half-installed state.

One container says
```yaml
        name: frontend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
```
and the other container also says
```
        name: traffic-agent
        ports:
        - containerPort: 9900
          name: http
          protocol: TCP
```
They shouldn't both have `name: http`!  Telepresence had renamed the one in `frontend` to `name: tel2mv-http`, and then something changed it back.

(And also, the error message for this wasn't great until recently.)

That's bad for two reasons: 1) it means that Telepresence isn't going to be properly intercepting all the traffic, and 2) as you see, it confuses Telepresence during `uninstall`.

In the right-now-term, as a workaround, @aliusmiles suggests, you can manually remove the agent container from the deployment (and also remove the `telepresence.getambassador.io/actions` annotation!) to uninstall that agent; then `telepresence uninstall` should be able to remove the manager just fine.

In the short-term, I think we can improve Telepresence to better detect when this has happened, and warn you.

In the longer-term, I think borrowing the admissions-controller approach from our old Service Preview product gives us the best approach for avoiding this situation altogether.

**Comment by KenxinKun** [comment] 2021-08-11 16:04
We're seeing a similar behaviour with our `grpc-web-port` being renamed to `tm-grpc-web-por`.
When we attempt for the first time `telepresence intercept` on a clean deployment it works just fine but after a while it stops working (i.e. it returns the original service response, not the intercepted one), and the `telepresence uninstall` commands fails with not being able to find the renamed port.
Our deployment is through Terraform and also contains Istio, which might be what's renaming the ports back?

**Comment by luminoso** [comment] 2022-01-05 21:53
I think I have this issue. I cannot uninstall the traffic agent.
If I try to intercept it starts the interception but there's no network traffic.

```
> telepresence uninstall -a
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /home/luminoso/.cache/telepresence/logs /home/luminoso/.config/telepresence ''
[sudo] password for luminoso: 
Launching Telepresence User Daemon
Connected to context gke_factory-85a4bb73_europe-west4-b_gke-factory-cluster (https://34.91.32.235)
Telepresence Root Daemon quitting... done
Telepresence User Daemon quitting... done
telepresence: error: 1 error occurred:
        * Deployment name="cair" namespace="staging": unable to locate port "tm-cair" in container "cair"



See logs for details (1 error found): "/home/luminoso/.cache/telepresence/logs/daemon.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7818018/telepresence_logs.zip)

**Comment by slavick** [comment] 2022-04-26 22:48
﻿I managed to solve this issue today. My specific error message was:

```
telepresence: error: 1 error occurred:
	* Deployment name="<service>" namespace="<ns>": unable to locate port "tm-http" in container "<service>"
```

It reads this `tm-http` from the namespace annotations in the deployment yaml. In my case, I confirmed there was no `tm-http` port specified, but there was `http`.

Steps:
1. `kubectl -n <ns> edit deploy/<service>` and replace `tm-http` with `http` in the annotation
2. Save the file, quit the editor, and confirm the terminal output shows the changes were applied
3. `telepresence uninstall --everything`
4. `telepresence list` to confirm that my service finally (mercifully) shows `traffic-agent not yet installed`

**Comment by dehypnosis** [comment] 2022-06-15 06:15
I am manually deleting agents every time for now by editing Deploment specification.
Is this issue still being investigated???

**Comment by thallgren** [comment] 2022-06-17 04:27
This is no longer an issue in telepresence versions >= 2.6.0. Telepresence no longer modify the services and deployments.

**Closed by thallgren** 2022-06-17 04:27 UTC
Labels: t:bug, v2

**Comment by Duanjax** [comment] 2022-11-09 09:01
```telepresence uninstall --everything``` worked for me.

**Comment by erceth** [comment] 2023-05-19 20:12
`telepresence helm uninstall` command (previously `telepresence uninstall --everything`)

https://www.getambassador.io/docs/telepresence/latest/install/manager#uninstall
