### ISSUE TITLE
Cannot leave intercept - not found

### ISSUE THREAD

**Issue by lkoniecz** [telepresenceio/telepresence#2540] opened 2022-04-20 10:19 UTC
**Describe the bug**
Cannot leave intercepted service

**To Reproduce**
```
telepresence connect
telepresence intercept player-center-adapter-reward --port 80:80
telepresence list

...
player-center-adapter-reward       : intercepted
    Intercept name    : player-center-adapter-reward
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:80
    Volume Mount Point: /var/folders/1w/6yhp567x54339r5x6dz9d4yw0000gp/T/telfs-2395838353
    Intercepting      : all TCP connections
...

telepresence leave player-center-adapter-reward
telepresence: error: Intercept named "player-center-adapter-reward" not found
```

**Expected behavior**
Telepresence leaves intercept

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
Client: v2.5.6 (api v3)
Root Daemon: v2.5.6 (api v3)
User Daemon: v2.5.6 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 ```
ProductName:	macOS
ProductVersion:	12.3.1
```
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
```
AWS EKS 1.21
```

**Additional context**

**Comment by thallgren** [comment] 2022-04-25 14:17
Did a long time pass between the last `list` and the attempt to `remove`?
Can you provide the `connector.log` for that time-span? 
Is this an intermittent problem, or something that you can reproduce every time?

**Comment by lkoniecz** [comment] 2022-04-26 06:24
I dont really remember. I no longer have access to connector.log as this happened on a different workstation that I have no longer access to.

Rather an intermittent case rather than permanent problem. 

Wasn't git by it since then.

**Comment by thallgren** [comment] 2022-04-26 08:02
I'm closing this, as I cannot reproduce it and we don't have anything to act on. Feel free to reopen if it happens again and you can provide some logs.

**Closed as completed by thallgren** 2022-04-26 08:02 UTC
