### ISSUE TITLE
Service-less deployments in Telepresence2

### ISSUE THREAD

**Issue by eridiumdev** [telepresenceio/telepresence#2255] opened 2021-12-07 13:06 UTC
**Please describe your use case / problem.**
With Telepresence1, one could swap a deployment, e.g.
```
telepresence --namespace my-namespace --swap-deployment my-deployment --run-shell
```
And it would work, even if deployment is not backed by any Service.

In Telepresence2, this results in following error:
```
Failed to establish intercept: found no services with a selector matching labels map[app:my-deployment] in namespace my-namespace
```

**Describe the solution you'd like**
I understand, this is not the most common use case, in my example, app inside a pod is subscribed to a RabbitMQ queue, and `swap-deployment` is exactly the thing I need in such case.

**Describe alternatives you've considered**
Another option - downscaling actual deployment + doing a bunch of port-forwarding. Or doing a single command in Telepresence1 :)

**Versions (please complete the following information)**
  - Telepresence: client: v2.4.4 (api v3)
  - Kubernetes: 1.19.14-gke.1900

**Comment by andrewnazarov** [comment] 2021-12-08 09:01
We have the same use case with many microservices using rabbitMQ and we would like to have a possibility (a flag maybe) to scale down/remove the remote pod.

**Comment by andrewnazarov** [comment] 2021-12-09 19:06
This is also related to https://github.com/telepresenceio/telepresence/issues/1646

**Comment by cindymullins-dw** [comment] 2023-02-07 22:17
There is [some guidance](https://www.getambassador.io/docs/telepresence/latest/reference/restapi) on using Telepresence with message queues.  Is this helpful to you at all?

**Comment by gbg-sany** [comment] 2023-06-14 14:00
The newer version has the `--local-only` is probably what u looking https://github.com/telepresenceio/telepresence.io/blob/master/docs/v2.5/howtos/outbound.md#using-local-only-intercepts

**Comment by cindymullins-dw** [comment] 2023-08-15 22:56
I think even in this case you still need a Service in order to make an intercept.  As I understand the local-only flag won’t do any rerouting but it will get access to any namespace you’re intercepting in.  As @eridiumdev noted, the swap-deployment is not available w the new version of Telepresence.  Will mark as a feature request.

**Comment by thallgren** [comment] 2024-08-19 13:50
Duplicate of #1647

**Closed as completed by thallgren** 2024-08-19 13:50 UTC
Labels: feature
