### ISSUE TITLE
Can't connect to services when using cloudflare's warp client

### ISSUE THREAD

**Issue by gabrielqs** [telepresenceio/telepresence#2834] opened 2022-10-25 19:55 UTC
I currently run telepresence on our EKS clusters. I can connect to services on those clusters, as well as intercept them, when I'm connected to our OpenVPN instance.
Recently we started testing [Cloudflare's warp client
](https://developers.cloudflare.com/warp-client/). I can connect to the cluster using kubectl, but can't connect to any services using telepresence.

```
> telepresence test-vpn
Telepresence Daemons have already quit
Please disconnect from your VPN now and hit enter once you're disconnected...

Please connect to your VPN now and hit enter once you're connected...


---------- Test Results:
✅ pod subnet 172.23.0.0/17 is clear of VPN
✅ svc subnet 10.100.0.0/16 is clear of VPN

Still having issues? Please create a new github issue at https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md
 Please make sure to add the following to your issue:
 * Run `telepresence loglevel debug`, try to connect, then run `telepresence gather_logs`. It will produce a zipfile that you should attach to the issue.
 * Which VPN client are you using?
 * Which VPN server are you using?
 * How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf
 
> telepresence connect
Connected to context <REDACTED>

> telepresence loglevel debug

> curl kubernetes.default
curl: (28) Failed to connect to kubernetes.default port 80 after 75184 ms: Operation timed out

> telepresence gather-logs
```

Logs are attached. resolv.conf attached, though i'm not sure it's being used by telepresence. I've attached the output

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9863562/telepresence_logs.zip)

**To Reproduce**
1. When I run `telepresence connect`, the `curl kubernetes.default` when connected to cloudflare's warp client
2. I see `curl: (28) Failed to connect to kubernetes.default port 80 after 75184 ms: Operation timed out`

**Expected behavior**
I'd expect telepresence to work while connected to cloudflare's warp client, knowing kubectl does.

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
Client: v2.8.2 (api v3)
Root Daemon: v2.8.2 (api v3)
User Daemon: v2.8.2 (api v3)
``` 

 - Operating system of workstation running `telepresence` commands: `MacOS Monterey 12.6`
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]: `EKS 1.22`

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using?
 `Cloudflare's Warp Client`
 - Which VPN server are you using?
 Cloudflared, running in a pod within the same cluster
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf
[resolv.conf.txt](https://github.com/telepresenceio/telepresence/files/9863564/resolv.conf.txt)
[scutil-dns.txt](https://github.com/telepresenceio/telepresence/files/9863561/scutil-dns.txt)

**Additional context**
Warp works on split tunnels. I have it configured to resolve our internal DNS records, and each private vpc cidr block is associate with one instance of the cloudflared binary, running in the clusters.
Given that, i _think_ the test-vpn command is lying when it says:
`✅ pod subnet 172.23.0.0/17 is clear of VPN`
I know for a fact 172.23.0.0/16 is part of the traffic routed by the warp client at the cloudflared pod ("vpn server", kind of) running within my private infrastructure.

**Comment by cindymullins-dw** [comment] 2022-10-31 23:03
HI @gabrielqs , assuming the test-vpn is not accurate in this case, what happens if you add /16 to never_proxy?  If you know that subnet is in fact being used by the VPN have you tried adding it as a test?

**Comment by gabrielqs** [comment] 2022-10-31 23:18
hello @cindymullins-dw , thanks for the response!
I hadn't noticed this configuration and will give it a try. I am a bit curious however, wouldn't i really need the TUN device to proxy requests to that VPC cidr block if i want to send requests to the TUN device?
In any case I will give it a try and report back. Thanks again.

**Comment by thallgren** [comment] 2023-02-21 20:24
Closing this due to lack of info.

**Comment by moshevayner** [comment] 2024-08-23 19:38
Hey @gabrielqs !
Did you ever manage to get this to work?
I've been struggling with the same issue ever since we started using Cloudflare WARP.
@thallgren & @cindymullins-dw  - any additional info I can provide for debug assistance?

Thanks!

**Comment by thallgren** [comment] 2024-08-23 20:15
Hey @moshevayner, yes. there are some things you could do that would be helpful. If you could please use the latest OSS client (2.19.1), turn on debug level logging in your config.yml, then try a connect. After it fails, please provide the logs produced by the `telepresence gather logs` command.

If you have time, you could also try the new `--proxy-via` option, (docs [here](https://www.getambassador.io/docs/telepresence/latest/reference/vpn#proxy-via-and-using-ip-addresses-directly))  to avoid the conflicting subnets.

**Comment by moshevayner** [comment] 2024-08-24 02:36
Hey @thallgren !
OK, so after a long afternoon of deep debugging, I think I was able to figure out what's the issue on our end.

Here's our scenario: 
We run on AWS, on a dedicated VPC - CIDR for the VPC is `10.200.0.0/16`
On that VPC, we have a Kubernetes cluster, which uses AWS VPC CNI plugin, meaning- the pods get an IP from the same CIDR range of the VPC (or, a smaller subset of it, to be accurate - `10.200.0.0/17` is the defined range for the cluster's pod network).

On Cloudflare side- we have a ZeroTrust tunnel configured with the CIDR range of that VPC (`10.200.0.0/16`) with connectors running within the VPC, to provide us access from our machines while connected via WARP client. 

The problem is that when Telepresence connects, it tries to take over the same range because of the pod network, but WARP client takes precedence and whenever we try to access a pod within the cluster through telepresence, WARP still tries to route it through the ZeroTrust tunnel instead of Telepresence.

The only way I was able to bypass that, is by temporarily configuring a Split Tunnel on Cloudflare side. This got Telepresence to start intercepting traffic properly, however- it broke the access to all other resources within the VPC because of the CIDR overlap. 

Alternatively, switching WARP mode to [DoH](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/warp-modes/#gateway-with-doh) instead of the default [WARP](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/configure-warp/warp-modes/#gateway-with-doh) also helped- but then again- on the account of not being able to access other resources within the same VPC while in this mode..

I hope I was able to explain myself correctly?
Does that make sense?

Thanks!

**Comment by thallgren** [comment] 2024-08-24 03:53
Hey @moshevayner. Thanks for all that info. That was very helpful.

 I think you have two options.
1. Use the `--proxy-via` to move the CIDR that Telepresence will use on you workstation. This option controls the Telepresence DNS, and will alter the IP addresses to a virtual CIDR that doesn't interfere with the Cloudflare CIDRs.
OR
2. Connect using `--docker` and intercept using `--docker-run` or `--docker-build`. That way, the Telepresence Virtual Network Device is confined to a container. It will require that the local process that you're using to receive intercepted traffic must live in a container too, but that will have some advantages (remote mounts from root, to name one). I wrote a [blog post](https://www.getambassador.io/blog/docker-and-jetbrains-telepresence-integrations) about this a while back that might be of interest.

In any case, I'll close this ticket because it's a classic CIDR conflict, and we do provide solutions for it.

**Closed as completed by thallgren** 2024-08-24 03:53 UTC
