### ISSUE TITLE
Leave, or personal intercepts, returns "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111"

### ISSUE THREAD

**Issue by matsgm** [telepresenceio/telepresence#3398] opened 2023-10-25 11:20 UTC
**Describe the bug**

When using telepresence, after leaving the error "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111" is shown in the browser then trying to access the service.

1. Run telepresence and intercept
2. I see it working
3. After i leave interception
4. See error "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111"

**Expected behavior**
The regular service should show the service

**Versions:**
 - v2.16.1 (all)
 - macOS 13.5.1 (22G90)
 - Azure Kubernetes Services kubernetes 1.26.6

**Additional context**
- Nginx ingress.
- It is the same problem when trying to access the "public" service when using a preview URL.
- The fix is to run ```telepresence uninstall --agent [SERVICE]```, which don't relly fix the personal interception problem

**Comment by cindymullins-dw** [comment] 2023-11-20 18:22
@matsgm , can you send us the results of ‘`telepresence gather logs’'?

**Comment by matsgm** [comment] 2023-11-21 07:36
> @matsgm , can you send us the results of ‘`telepresence gather logs’'?

HI. I'm in dialog with the support. I've sent them the logs.

**Comment by cindymullins-dw** [comment] 2023-12-18 18:00
Hi @matsgm, I've heard from support we need some additional info from you.  Could you please respond on the ticket?

**Comment by matsgm** [comment] 2023-12-18 18:09
> Hi @matsgm, I've heard from support we need some additional info from you. Could you please respond on the ticket?

Replied now.

**Comment by Strayfe** [comment] 2023-12-21 14:22
I briefly mentioned this scenario in a recent bug I raised, #3460.

> Also, is there not a mechanism that informs the traffic-agent or agent sidecar that the intercept has been left or terminated?
>
> I noticed during my testing, that after leaving an intercept or quitting telepresence entirely, the /consume-here endpoint in the cluster never seems to realise that the intercept is no longer running and always returns false because it thinks an intercept is still running.

I have been doing some additional troubleshooting this morning to try and aid in the investigation of this issue.

## Setup

- Create a new cluster (`minikube`, `kind`, `AKS`, etc.)
- Clone the `emojivoto` repo: https://github.com/BuoyantIO/emojivoto
- Apply the resources to the cluster `kubectl kustomize kustomize/deployment | kubectl apply -f -`
- Install an ingress, an easy way to do this is using `minikube`: `minikube addons enable ingress`
- Configure an ingress for the `web-svc`:
```shell
kubectl apply -f - << EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-svc
  namespace: emojivoto
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: emojivoto.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: 80
EOF
```
- Add the following record to your hosts file to allow DNS to resolve: `192.168.49.2        emojivoto.local`
  _Be sure to replace the IP with the of your ingress if it is not this -------------^_
- Install telepresence: `telepresence helm install`
- Connect to the cluster `telepresence connect --namespace emojivoto`
- Load the `web-svc` from the `L5Host`: http://web-svc.emojivoto.svc.cluster.local/
- Load the resource via the ingress URL: http://emojivoto.local/

![image](https://github.com/telepresenceio/telepresence/assets/642269/b3955a94-e0bb-446a-866e-915c5bf7af77)

We now have a setup that works via an `ingress` and `L5Host` to perform the rest of the testing.

## Testing

- Start an intercept `telepresence intercept web --service web-svc --http-header=a=b`
```shell
Using Deployment web
   Intercept name         : web
   State                  : ACTIVE
   Workload kind          : Deployment
   Destination            : 127.0.0.1:8080
   Service Port Identifier: http
   Volume Mount Error     : sshfs is not installed on your local machine
   Intercepting           : HTTP requests with headers
         'a =~ b'
   Preview URL            : https://happy-hermann-4008.preview.edgestack.me
   Layer 5 Hostname       : web-svc.emojivoto.svc.cluster.local
```
- Use a browser extension (like `ModHeader`) to add the http header `a:b` to your HTTP requests
- Load the resource via the `L5Host`: http://web-svc.emojivoto.svc.cluster.local/
- Load the resource via the ingress host: http://emojivoto.local/
- Notice the redirection working as expected:

![image](https://github.com/telepresenceio/telepresence/assets/642269/4955af7a-de48-4b29-aeb2-4d165848e22b)

The fact that we see the `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error here is expected because following these steps verbatim, we have not created a `handler` instance to receive the proxied requests. 

_Optionally here you could load up an instance of the `emojivoto` solution to differentiate between a running instance or not but it matters-not to make the point here, we can see that the envoy proxy is **attempting** to forward the request which is all we need to see being demonstrated._

- Leave the intercept `telepresence leave web`
- Reload the resources and notice how now neither will return to the `emojivoto` application

![image](https://github.com/telepresenceio/telepresence/assets/642269/fae6050d-7447-42b0-bfcc-191f03002a43)

The logs in nginx pod:
```log
192.168.49.1 - - [21/Dec/2023:12:58:07 +0000] "GET / HTTP/1.1" 503 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0" 408 0.000 [emojivoto-web-svc-80] [] 10.244.0.89:8080 0 0.000 503 c722489f8c03bab4d77b16096e069d6b
192.168.49.1 - - [21/Dec/2023:12:58:07 +0000] "GET /favicon.ico HTTP/1.1" 503 0 "http://emojivoto.local/" "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0" 363 0.000 [emojivoto-web-svc-80] [] 10.244.0.89:8080 0 0.001 503 2acef6a5f4602705ee04e45b76969bb2
```

If you wait long enough after leaving the intercept, there is a chance the application will start responding correctly, but then trying to start the intercept again will no longer intercept your requests, regardless of whether you are setting the headers or not.

Like in the strange example here of where the `L5Host` is working but the ingress isn't:

![image](https://github.com/telepresenceio/telepresence/assets/642269/5afea754-7afe-4a2d-9b3f-1da99e1c4ebd)

**Comment by Strayfe** [comment] 2023-12-21 14:42
I thought it was a bit strange that last scenario I encountered so I did some more digging and I feel slightly foolish.

I believe the issue I just described is, believe it or not... **browser caching**.

After terminating the intercept, if you `CTRL`+`F5`, the page loads straight away... 

Have you tried this @matsgm ?

If this doesn't work for you then I may look even more foolish as our issues may differ slightly with similar symptoms.

**Comment by thallgren** [comment] 2023-12-22 11:29
Another piece of related info that might be helpful regarding intercepts that have ended.

We recently (in 2.17) introduced a new setting that will allow the agent to remember personal intercept headers for a while _after the intercept has ended_, so that continued use of those headers will render an 503 instead of just silently switching over to the unintercepted pod.

You can read more about this setting [here](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#enable-errors-when-attempting-to-access-an-intercept-that-has-expired).

**Comment by Strayfe** [comment] 2023-12-22 14:30
Interesting!

I cannot see any configured defaults in the `values.yaml`, nor are they listed in the `README.md` for the the telepresence helm chart.

Do we know what the default behaviour of this feature is? 

I would assume that based off my troubleshooting, it is disabled by default and the issue is likely a caching problem, however, the final screenshot I sent does demonstrate the 503 being returned in one window and not in the other which is a confusing scenario to me. When the 503 is returned, a force refresh does clear the 503 and load the resource as expected.

**Comment by thallgren** [comment] 2023-12-23 06:16
Not listing them in the README.md is an oversight on our part. It's a pro-only feature, and believe it or not, it is listed in the pro version of the README.md. Only problem is, that version isn't referenced from the docs. I'll look into this.

And yes, the default is that the feature is turned off.

**Comment by thallgren** [comment] 2023-12-28 15:35
We've made some recent updates to the Helm chart. This particular feature is not present in the OSS Helm chart. You will however find [here](https://artifacthub.io/packages/helm/datawire/telepresence) (under Enterprise configuration).

**Comment by thallgren** [comment] 2024-02-05 09:13
Closing this, as I believe the original issue has been resolved by the [expiredNotifications](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config#enable-errors-when-attempting-to-access-an-intercept-that-has-expired) new setting.

**Closed as completed by thallgren** 2024-02-05 09:13 UTC
