### ISSUE TITLE
[v2] Persistent TCP connections failing after precisely 60s since session establishment

### ISSUE THREAD

**Issue by frankgu968** [telepresenceio/telepresence#1993] opened 2021-08-17 00:31 UTC
This is a more generalized version of https://github.com/telepresenceio/telepresence/issues/1933

To replicate: 
1. On a fresh k8s cluster (occurs on both EKS and GCP clusters), install a postgres instance
2. `telepresence connect` to the cluster
3. Run `psql -h pg-headless.default -p 5432 -U postgres -d postgres` and connect to the database
4. Run `select NOW()` and start a timer
Observe that after precisely 60s, if you issue another `select NOW()` statement in the same psql session, it hangs indefinitely. However, on a different terminal, run the `psql` command again and observe that a new session can be run again!

**Comment by frankgu968** [comment] 2021-08-17 00:43
Tested this with the Bitnami pg chart, CloudSQL, and RDS. Fairly certain this is a TCP-layer issue. This does not require any intercepts to be active; the traffic manager proxy seems to be the source of the issue.

**Comment by vsimon** [comment] 2021-08-17 01:14
Thank you Frank. I was scratching my head today why mysql connections would inexplicably time out. Each time I quit/connect, things work..then after awhile i get timeouts until I quit/connect again. This is on 2.4.0.

Any known good versions in case rolling back can be a workaround?

**Comment by frankgu968** [comment] 2021-08-17 02:20
Since 2.3.x, the connection method was changed so the virtual network device configuration may be the culprit. We currently rolled back to 2.2.2 and the connections are mostly stable. I am investigating the issue as well as I suspect this has to do with some TCP-level stuff in the system. Will update this thread if/when I find out more about the issue.

**Comment by thallgren** [comment] 2021-08-17 06:03
The problem was due to a hardcoded idle timer which made the traffic-manager terminate its end of the tunnel after 60 seconds. The problem is fixed in PR #1994.

**Comment by AlaaMouch** [comment] 2021-08-19 19:28
If anyone needs an urgent fix and can't wait until v2.4.1, this issue seems to be fixed in the latest [nightly release](https://www.telepresence.io/docs/latest/install/#installing-nightly-versions-of-telepresence).

**Comment by efunk** [comment] 2021-08-31 12:40
Fix released with Telepresence 2.4.1.

**Closed as completed by efunk** 2021-08-31 12:40 UTC
