### ISSUE TITLE
SSH isn't starting / unable to SSH

### ISSUE THREAD

**Issue by andrewvy** [telepresenceio/telepresence#267] opened 2017-08-09 21:14 UTC
### What were you trying to do?

Trying to `telepresence --run-shell` to connect to a local minikube instance. (Running in VirtualBox). (This recorded error is after trying from 6.3 source)

### What did you expect to happen?

A shell should be started! :) The deployment shows up, the pod boots up fine too. Seems like a networking issue somewhere, happy to figure out how to debug this further.

I did try to see if a bare `kubectl port-forward` worked, and it definitely does.

### What happened instead?

Oddly enough, it's unable to SSH into the pod.

### Automatically included information

Command line: `['cli/telepresence', '--run-shell']`
Version: `0.63`
Python version: `3.6.2 (default, Aug  9 2017, 13:53:54) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]`
kubectl version: `Client Version: v1.7.3`
oc version: `oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.100:8443
kubernetes v1.7.0`
OS: `Darwin vy.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "cli/telepresence", line 133, in call_f
    return f(*args, **kwargs)
  File "cli/telepresence", line 2177, in go
    runner, args
  File "cli/telepresence", line 1361, in start_proxy
    processes, socks_port, ssh = connect(runner, remote_info, args)
  File "cli/telepresence", line 1013, in connect
    ssh.wait()
  File "cli/telepresence", line 863, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
063119-ff2wg', '50501:8022'],)...Running: (['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '50501', 'telepresence@localhost', '/bin/true'],)... Forwarding from 127.0.0.1:50501 -> 8022
Forwarding from [::1]:50501 -> 8022
Listening...
2017-08-09T20:57:25+0000 [-] Loading ./forwarder.py...
2017-08-09T20:57:25+0000 [-] SOCKSv5Factory starting on 9050
2017-08-09T20:57:25+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7fe11d9e2518>
2017-08-09T20:57:25+0000 [-] DNSDatagramProtocol starting on 9053
2017-08-09T20:57:25+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fe11d9f1588>
2017-08-09T20:57:25+0000 [-] Loaded.
2017-08-09T20:57:25+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/usr/bin/python3.6 3.6.1) starting up.
2017-08-09T20:57:25+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.

```

**Comment by ark3** [comment] 2017-08-10 18:00
Sorry that you ran into a problem! I agree that it's probably a networking issue somewhere. Does this happen every time, or is it a transient issue? May I see the full telepresence.log from `cli/telepresence --run-shell --verbose`? That will include a lot of output from `ssh` that may pinpoint the issue. 

Thanks for the bug report.

**Comment by andrewvy** [comment] 2017-08-10 20:48
```
Looks like we've found our pod!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'get', 'pod', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '-o', 'json'],)... ran!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'get', 'pod', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '-o', 'json'],)... ran!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'get', 'pod', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '-o', 'json'],)... ran!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'get', 'pod', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '-o', 'json'],)... ran!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'get', 'pod', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '-o', 'json'],)... ran!
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'logs', '-f', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '--container', 'telepresence-1502397574-916533-22810'],)...Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'port-forward', 'telepresence-1502397574-916533-22810-681558719-f1dm2', '60933:8022'],)...Running: (['ssh', '-F', '/dev/null', '-vv', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '60933', 'telepresence@localhost', '/bin/true'],)... OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /dev/null
debug2: resolving "localhost" port 60933
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to localhost [::1] port 60933.
debug1: connect to address ::1 port 60933: Connection refused
debug1: Connecting to localhost [fe80::1%lo0] port 60933.
debug1: connect to address fe80::1%lo0 port 60933: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 60933.
debug1: connect to address 127.0.0.1 port 60933: Connection refused
debug1: Connecting to localhost [185.27.174.169] port 60933.
Listening...
2017-08-10T20:36:28+0000 [-] Loading ./forwarder.py...
2017-08-10T20:36:28+0000 [-] SOCKSv5Factory starting on 9050
2017-08-10T20:36:28+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f6b61f6a438>
2017-08-10T20:36:28+0000 [-] DNSDatagramProtocol starting on 9053
2017-08-10T20:36:28+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f6b61f7b4a8>
2017-08-10T20:36:28+0000 [-] Loaded.
2017-08-10T20:36:28+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/usr/bin/python3.6 3.6.1) starting up.
2017-08-10T20:36:28+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
Forwarding from 127.0.0.1:60933 -> 8022
Forwarding from [::1]:60933 -> 8022
debug1: connect to address 185.27.174.169 port 60933: Operation timed out
ssh: connect to host localhost port 60933: Operation timed out
Running: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'working', 'delete', '--ignore-not-found', 'all', '--selector=telepresence=daba778c-01fa-4098-a3ab-95e4bac2f814'],)... ran!
```

It looks like it must be the `kubectl port-forward` somehow?

**Comment by ark3** [comment] 2017-08-17 18:39
I've been trying to reproduce a failure and telepresence log similar to yours above, but have not yet succeeded. I suspect a race condition that I need to time just so. To help me figure this out, I'm working on some improvements to Telepresence's logging that will be in the next release. I'll ask you to try this again at that point, probably next week. Thanks for your patience.

**Comment by ark3** [comment] 2017-09-27 21:21
@andrewvy Could you please send telepresence.log using the latest Telepresence? Release 0.67 added enhanced logging that may help us diagnose the problem.

**Comment by donnyyung** [comment] 2021-07-23 12:22
I believe this is no longer an issue in Telepresence 2 since we don't use ssh. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Closed by donnyyung** 2021-07-23 12:22 UTC
Labels: blocked, t:bug
