### ISSUE TITLE
Remove a global intercept that was created by another user

### ISSUE THREAD

**Issue by ghost** [telepresenceio/telepresence#2919] opened 2022-12-06 09:17 UTC
**Please describe your use case / problem.**
A User creates a global intercept. Their machine is then unavailable on the network for a while (disconnected, sleep, hibernated etc). The target environment becomes unusable for other team members as all traffic to the intercepted service are redirected to the unavailable machine

**Describe the solution you'd like**
Get list of all global intercepts on a target environment and let other users remove one that was created by another user

**Describe alternatives you've considered**
None that I could think of

**Versions (please complete the following information)**
  - 2.9.4
  - Kubernetes Environment and Version

**Additional context**

**Comment by thallgren** [comment] 2022-12-06 10:02
There are several ways to address this.
1. Login to Ambassador Cloud and use personal intercepts. That will remove the friction that global intercepts create.
2. Limit the TTL for a workstation connection. It currently defaults to 24 hours but it can be set to a much shorter duration (30 seconds perhaps?) using the Helm chart value `client.connectionTTL`. The drawback with a short TTL is that if you have ongoing connections (and/or intercepts) and close the lid of your laptop, they will be lost fairly quickly.
3. If you have sufficient cluster credentials, then use `kubectl` to scale the traffic-manager deployment to zero and then back up to one. That will effectively kill all connections (and intercepts).

I'm closing this ticket because things works as designed and there are no current plans to change this.

**Closed as completed by thallgren** 2022-12-06 10:02 UTC
