### ISSUE TITLE
Daemons shutdown when intercepting without previously connecting or starting the local process

### ISSUE THREAD

**Issue by douglascamata** [telepresenceio/telepresence#2248] opened 2021-12-02 16:54 UTC
**Describe the bug**

Daemons are shutting down and the intercept isn't being created whenever I try to run the `intercept` command without having previously started the daemons or the local process (that should receive intercepted traffic).

if I previously start the daemons with `telepresence connect` I see the CONN errors, but the intercept gets created and the daemon does not quit.

**To Reproduce**

0. I run `telepresence quit`
1. When I run `telepresence intercept ...`
2. I see `See logs for details (2 errors found): "/Users/douglascamata/Library/Logs/telepresence/connector.log"`
3. So I look at the logs
4. See error: 

```
2021-12-02 17:31:19.8655 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-12-02 17:31:20.0062 debug   connector/background-manager/dial-request-watcher :    CONN tcp 127.0.0.1:39292 -> 127.0.0.1:9090, dialing
2021-12-02 17:31:20.0066 error   connector/background-manager/dial-request-watcher : !! CONN tcp 127.0.0.1:39292 -> 127.0.0.1:9090, failed to establish connection: dial tcp4 127.0.0.1:9090: connect: connection refused
2021-12-02 17:31:20.0119 debug   connector/background-manager/dial-request-watcher :    CONN tcp 127.0.0.1:47932 -> 127.0.0.1:9090, dialing
2021-12-02 17:31:20.0121 error   connector/background-manager/dial-request-watcher : !! CONN tcp 127.0.0.1:47932 -> 127.0.0.1:9090, failed to establish connection: dial tcp4 127.0.0.1:9090: connect: connection refused
2021-12-02 17:31:24.6905 debug   connector/server-grpc/conn=1/CreateIntercept-5 : returned
2021-12-02 17:31:25.1457 debug   connector/server-grpc/conn=1/UserNotifications-1 : returned
2021-12-02 17:31:25.1469 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021-12-02 17:31:25.1469 debug   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited without error
2021-12-02 17:31:25.4016 debug   connector/server-grpc/conn=3/UserNotifications-6 : called
2021-12-02 17:31:25.4017 debug   connector/server-grpc/conn=3/Quit-7 : called
2021-12-02 17:31:25.4018 debug   connector/server-grpc/conn=3/Quit-7 : returned
2021-12-02 17:31:25.4018 debug   connector/quit : goroutine "/connector/quit" exited without error
2021-12-02 17:31:25.4019 info    connector/background-k8swatch:shutdown_logger : shutting down (gracefully)...
2021-12-02 17:31:25.4019 debug   connector/background-system/refresh : goroutine "/connector/background-system/refresh" exited without error
2021-12-02 17:31:25.4019 info    connector:shutdown_logger : shutting down (gracefully)...
2021-12-02 17:31:25.4019 debug   connector/background-manager/remain : telling manager to remove intercept my-cool-intercept
2021-12-02 17:31:25.4020 debug   connector/background-manager/intercept-port-forward : goroutine "/connector/background-manager/intercept-port-forward" exited without error
2021-12-02 17:31:25.4019 debug   connector/background-manager/agent-watcher : goroutine "/connector/background-manager/agent-watcher" exited without error
2021-12-02 17:31:25.4019 debug   connector/background-init : goroutine "/connector/background-init" exited without error
2021-12-02 17:31:25.4019 info    connector/background-system:shutdown_logger : shutting down (gracefully)...
2021-12-02 17:31:25.4019 debug   connector/background-k8swatch/namespaces : goroutine "/connector/background-k8swatch/namespaces" exited without error
2021-12-02 17:31:25.4019 debug   connector/background-manager/dial-request-watcher : goroutine "/connector/background-manager/dial-request-watcher" exited without error
2021-12-02 17:31:25.4021 debug   connector/background-k8swatch : goroutine "/connector/background-k8swatch" exited without error
2021-12-02 17:31:25.4019 info    connector/background-manager:shutdown_logger : shutting down (gracefully)...
2021-12-02 17:31:25.4022 debug   connector/background-metriton : goroutine "/connector/background-metriton" exited without error
2021-12-02 17:31:25.4022 debug   connector/server-grpc/conn=3/UserNotifications-6 : returned
2021-12-02 17:31:25.4033 debug   connector/background-system/server-http : goroutine "/connector/background-system/server-http" exited without error
2021-12-02 17:31:25.4033 debug   connector/background-system : goroutine "/connector/background-system" exited without error
2021-12-02 17:31:25.6791 debug   connector/background-manager/remain : goroutine "/connector/background-manager/remain" exited without error
2021-12-02 17:31:25.6792 debug   connector/background-manager : goroutine "/connector/background-manager" exited without error
2021-12-02 17:31:25.6806 debug   connector/server-grpc : gRPC server ended
2021-12-02 17:31:25.6807 debug   connector/server-grpc : goroutine "/connector/server-grpc" exited without error
```

**Expected behavior**

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client: v2.4.7 (api v3)
Root Daemon: v2.4.7 (api v3)
User Daemon: v2.4.7 (api v3)

- Traffic Manager version: 1.11.5

 - Operating system of workstation running `telepresence` commands
 MacOS 11.6

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 v1.19.14

**Comment by thallgren** [comment] 2021-12-07 14:28
The expected behavior is that the daemons return the state they had before you do a `telepresence intercept`. If they weren't started, they will quit when the intercept ends. If they were running (as the result of a `telepresence connect`), the will continue running and will exit when you do a `telepresence quit`.

The connection error seems to indicate that you start an intercept on port 9090 but there's no process running on your local workstation that listens to that port.

I'm closing this ticket because I interpret what you describe as the expected behavior. Feel free to reopen with additional info if I missed something.

**Comment by thallgren** [comment] 2021-12-08 09:54
@douglascamata I obviously misread this bug-report. Please convey the exact message that you get when you do a `telepresence intercept` without a preceeding `telepresence connect`.

I think the interesting part of the `connector.log` will be found before the line:
```
2021-12-02 17:31:24.6905 debug   connector/server-grpc/conn=1/CreateIntercept-5 : returned
```
There should be something there to indicate why the intercept failed.

The `daemon.log` might be useful too, to see what's going on with the actual connection (or simply use `telepresence gather-logs` to get them all).

**Comment by douglascamata** [comment] 2021-12-08 11:15
@thallgren after an upgrade of the **Traffic Manager** to **1.11.6**, the logs have changed. So I went through both scenarios again (with pre-started daemons and without). Here are the requested details:

## No daemons started

The output of my intercept creation:

```
An update of telepresence from version 2.4.7 to 2.4.8 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context k8s-cluster (...)
Launching browser authentication flow...
Login successful.
Telepresence Root Daemon quitting... done
Telepresence User Daemon quitting... done
telepresence: error: Failed to establish intercept: the intercept timed out.  The current timeout 5s can be configured as "timeouts.intercept" in "/Users/douglascamata/Library/Application Support/telepresence/config.yml"

See logs for details (2 errors found): "/Users/douglascamata/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

In `connector.log` file I have:

```
2021-12-08 11:46:34.6945 info    connector/background-manager : Existing Traffic Manager 2.4.5 not owned by cli or does not need upgrade, will not modify
2021-12-08 11:46:34.6962 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081")
2021-12-08 11:46:34.6963 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador)
2021-12-08 11:46:34.9847 debug   connector/background-manager : k8sPortForwardDialer.dial(ctx, traffic-manager-c665545c7-z5nks.ambassador, 8081)
2021-12-08 11:46:34.9848 debug   connector/background-manager : k8sPortForwardDialer.spdyDial(ctx, Pod./traffic-manager-c665545c7-z5nks.ambassador)
2021-12-08 11:46:36.2623 debug   connector/background-manager/intercept-port-forward : posting search paths [argocd cert-manager default kube-node-lease kube-public kube-system monitoring traffic-manager] and namespaces []
2021-12-08 11:46:36.2633 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-12-08 11:46:36.2633 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-12-08 11:46:36.4279 debug   connector/server-grpc/conn=1/Connect-2 : returned
2021-12-08 11:46:36.8361 debug   connector/server-grpc/conn=2/daemon->manager : goroutine "/connector/server-grpc/conn=2/daemon->manager" exited without error
2021-12-08 11:46:37.6743 debug   connector/server-grpc/conn=1/UserNotifications-1 : returned
2021-12-08 11:46:37.6754 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.6755 debug   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited without error
2021-12-08 11:46:37.9308 debug   connector/server-grpc/conn=3/UserNotifications-3 : called
2021-12-08 11:46:37.9308 debug   connector/server-grpc/conn=3/Quit-4 : called
2021-12-08 11:46:37.9311 debug   connector/server-grpc/conn=3/Quit-4 : returned
2021-12-08 11:46:37.9311 debug   connector/quit : goroutine "/connector/quit" exited without error
2021-12-08 11:46:37.9312 info    connector/background-k8swatch:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.9312 debug   connector/background-init : goroutine "/connector/background-init" exited without error
2021-12-08 11:46:37.9313 info    connector:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.9312 debug   connector/background-metriton : goroutine "/connector/background-metriton" exited without error
2021-12-08 11:46:37.9314 debug   connector/background-manager/dial-request-watcher : goroutine "/connector/background-manager/dial-request-watcher" exited without error
2021-12-08 11:46:37.9313 debug   connector/background-manager/agent-watcher : goroutine "/connector/background-manager/agent-watcher" exited without error
2021-12-08 11:46:37.9314 debug   connector/background-systema/refresh : goroutine "/connector/background-systema/refresh" exited without error
2021-12-08 11:46:37.9314 debug   connector/background-k8swatch/namespaces : goroutine "/connector/background-k8swatch/namespaces" exited without error
2021-12-08 11:46:37.9314 info    connector/background-systema:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.9314 debug   connector/background-manager/intercept-port-forward : goroutine "/connector/background-manager/intercept-port-forward" exited without error
2021-12-08 11:46:37.9314 info    connector/background-manager:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.9316 debug   connector/background-k8swatch : goroutine "/connector/background-k8swatch" exited without error
2021-12-08 11:46:37.9317 debug   connector/server-grpc/conn=3/UserNotifications-3 : returned
2021-12-08 11:46:37.9327 debug   connector/background-systema/server-http : goroutine "/connector/background-systema/server-http" exited without error
2021-12-08 11:46:37.9328 debug   connector/background-systema : goroutine "/connector/background-systema" exited without error
2021-12-08 11:46:38.1418 debug   connector/background-manager/remain : goroutine "/connector/background-manager/remain" exited without error
2021-12-08 11:46:38.1419 debug   connector/background-manager : goroutine "/connector/background-manager" exited without error
2021-12-08 11:46:38.1435 debug   connector/server-grpc : gRPC server ended
2021-12-08 11:46:38.1436 debug   connector/server-grpc : goroutine "/connector/server-grpc" exited without error
```

And in the `daemon.log`:

```
2021-12-08 11:46:37.6746 debug   daemon/server-grpc/conn=1 : Received gRPC Quit
2021-12-08 11:46:37.6750 debug   daemon/server-router/TUN reader : goroutine "/daemon/server-router/TUN reader" exited without error
2021-12-08 11:46:37.6752 debug   daemon/server-router : goroutine "/daemon/server-router" exited without error
2021-12-08 11:46:37.6751 info    daemon/daemon-quit : Shutting down connector
2021-12-08 11:46:37.6753 info    daemon/server-dns/Server:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.6753 debug   daemon/server-dns/Server/127.0.0.1:57540 : Shutting down DNS server
2021-12-08 11:46:37.6755 debug   daemon/daemon-quit : goroutine "/daemon/daemon-quit" exited without error
2021-12-08 11:46:37.6753 debug   daemon/server-dns/SearchPaths : goroutine "/daemon/server-dns/SearchPaths" exited without error
2021-12-08 11:46:37.6753 debug   daemon/watch-cluster-info : goroutine "/daemon/watch-cluster-info" exited without error
2021-12-08 11:46:37.6753 info    daemon/server-dns:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.6754 debug   daemon/server-dns/Server/127.0.0.1:57540 : goroutine "/daemon/server-dns/Server/127.0.0.1:57540" exited without error
2021-12-08 11:46:37.6753 info    daemon:shutdown_logger : shutting down (gracefully)...
2021-12-08 11:46:37.6756 debug   daemon/server-dns/Server : goroutine "/daemon/server-dns/Server" exited without error
2021-12-08 11:46:37.6769 debug   daemon/server-grpc : gRPC server ended
2021-12-08 11:46:37.6769 debug   daemon/server-grpc : goroutine "/daemon/server-grpc" exited without error
2021-12-08 11:46:37.6793 debug   daemon/server-dns : goroutine "/daemon/server-dns" exited without error
2021-12-08 11:46:37.6794 debug   daemon/background-metriton : goroutine "/daemon/background-metriton" exited without error
```

At the end, the daemons aren't running (confirmed with `telepresence status`) and the intercept doesn't exist.

## Pre-started daemon

Circling back to the full tests because of the change in the version of the Traffic Manager, I started the daemons with `telepresence connect` and tried the same intercept creation command. 

Here's the output of the intercept command:

```
telepresence: error: Failed to establish intercept: the intercept timed out.  The current timeout 5s can be configured as "timeouts.intercept" in "/Users/douglascamata/Library/Application Support/telepresence/config.yml"

See logs for details (2 errors found): "/Users/douglascamata/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

And the contents of `connector.log`:

```
2021-12-08 12:00:17.4712 info    connector/background-manager : Existing Traffic Manager 2.4.5 not owned by cli or does not need upgrade, will not modify
2021-12-08 12:00:17.4747 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081")
2021-12-08 12:00:17.4751 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador)
2021-12-08 12:00:17.8791 debug   connector/background-manager : k8sPortForwardDialer.dial(ctx, traffic-manager-c665545c7-z5nks.ambassador, 8081)
2021-12-08 12:00:17.8791 debug   connector/background-manager : k8sPortForwardDialer.spdyDial(ctx, Pod./traffic-manager-c665545c7-z5nks.ambassador)
2021-12-08 12:00:19.3497 debug   connector/background-manager/intercept-port-forward : posting search paths [argocd cert-manager default kube-node-lease kube-public kube-system monitoring traffic-manager] and namespaces []
2021-12-08 12:00:19.3519 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-12-08 12:00:19.5299 debug   connector/server-grpc/conn=1/Connect-2 : returned
2021-12-08 12:00:19.5323 debug   connector/server-grpc/conn=1/UserNotifications-1 : returned
2021-12-08 12:00:20.0631 debug   connector/server-grpc/conn=2/daemon->manager : goroutine "/connector/server-grpc/conn=2/daemon->manager" exited without error
2021-12-08 12:00:53.0885 debug   connector/server-grpc/conn=3/UserNotifications-3 : called
2021-12-08 12:00:53.0886 debug   connector/server-grpc/conn=3/Connect-4 : called
2021-12-08 12:00:53.4018 debug   connector/server-grpc/conn=3/Connect-4 : returned
2021-12-08 12:00:53.5716 debug   connector/server-grpc/conn=3/Login-5 : called
2021-12-08 12:00:54.0583 debug   connector/server-grpc/conn=3/Login-5 : returned
2021-12-08 12:00:54.1054 debug   connector/server-grpc/conn=3/GetCloudAPIKey-6 : called
2021-12-08 12:00:54.1055 debug   connector/server-grpc/conn=3/GetCloudAPIKey-6 : returned
2021-12-08 12:00:55.3514 debug   connector/server-grpc/conn=3/CreateIntercept-7 : called
2021-12-08 12:00:55.5034 debug   connector/server-grpc/conn=3/CreateIntercept-7 : Deployment app.container already has an installed and up-to-date agent
2021-12-08 12:00:55.6414 info    connector/server-grpc/conn=3/CreateIntercept-7 : Waiting for agent for Deployment app.container
2021-12-08 12:00:55.6422 info    connector/server-grpc/conn=3/CreateIntercept-7 : Agent found or created for Deployment app.container
2021-12-08 12:00:55.6423 debug   connector/server-grpc/conn=3/CreateIntercept-7 : creating intercept intercept-app-container
2021-12-08 12:00:55.7781 debug   connector/background-manager/intercept-port-forward : posting search paths [argocd cert-manager default kube-node-lease kube-public kube-system monitoring traffic-manager] and namespaces []
2021-12-08 12:00:55.7790 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-12-08 12:00:55.7807 debug   connector/server-grpc/conn=3/CreateIntercept-7 : created intercept intercept-app-container
2021-12-08 12:00:55.9743 debug   connector/background-manager/dial-request-watcher :    CONN tcp 127.0.0.1:55648 -> 127.0.0.1:9090, dialing
2021-12-08 12:00:55.9743 debug   connector/background-manager/dial-request-watcher :    CONN tcp 127.0.0.1:38834 -> 127.0.0.1:9090, dialing
2021-12-08 12:00:55.9751 error   connector/background-manager/dial-request-watcher : !! CONN tcp 127.0.0.1:55648 -> 127.0.0.1:9090, failed to establish connection: dial tcp4 127.0.0.1:9090: connect: connection refused
2021-12-08 12:00:55.9751 error   connector/background-manager/dial-request-watcher : !! CONN tcp 127.0.0.1:38834 -> 127.0.0.1:9090, failed to establish connection: dial tcp4 127.0.0.1:9090: connect: connection refused
2021-12-08 12:01:00.6479 debug   connector/server-grpc/conn=3/CreateIntercept-7 : returned
2021-12-08 12:01:01.1685 debug   connector/server-grpc/conn=3/UserNotifications-3 : returned
2021-12-08 12:01:01.8530 debug   connector/background-manager/intercept-port-forward : Started forward for {Name:app-container PodIP:10.56.4.203}
2021-12-08 12:01:01.8530 error   connector/background-manager/intercept-port-forward/10.56.4.203:44613 : No mount point found for intercept "app-container"
```

The `daemon.log` is fine, there's nothing weird there.

At the end, the daemons are still running and my intercept is created (confirmed with `telepresence status`).

**Comment by thallgren** [comment] 2021-12-08 11:21
Ok, so it's probably the intercept timeout of 5 seconds that is far too short given that the smart-agent actually spend that time trying to figure out if the client supports http2 (when no client is started yet). That's a bug for sure.

@douglascamata can you try increasing the "timeouts.intercept" in "/Users/douglascamata/Library/Application Support/telepresence/config.yml to at least 10 seconds and check if the problem persists?

**Comment by douglascamata** [comment] 2021-12-08 11:23
@thallgren I'll try this. Not very confident it will work out though because I see the timeout error below in both scenarios.
```
telepresence: error: Failed to establish intercept: the intercept timed out.  The current timeout 5s can be configured as "timeouts.intercept" in "/Users/douglascamata/Library/Application Support/telepresence/config.yml"
```

**Comment by douglascamata** [comment] 2021-12-08 11:32
Wow, increasing the timeout to 15s solved the issue. 🎉

**Comment by thallgren** [comment] 2022-02-21 11:29
No longer an issue since #2273

**Closed as completed by thallgren** 2022-02-21 11:29 UTC
