### ISSUE TITLE
Intercepts multiple ports in a service

### ISSUE THREAD

**Issue by movsb** [telepresenceio/telepresence#2121] opened 2021-09-29 08:26 UTC
**Please describe your use case / problem.**

I have a service with two ports, GRPC and HTTP. I want to intercept both of the ports. Currently, I don't know how.

**Describe the solution you'd like**

I'd like the `-p` flag of `intercept` can have multiple ports specified.

```shell-session
telepresence intercept --namespace xxx --service yyy --workload zzz name  -p 7080:7080 -p 7081:7081
```

**Describe alternatives you've considered**

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)

    ```-
    Client: v2.4.4 (api v3)
    Root Daemon: v2.4.4 (api v3)
    User Daemon: v2.4.4 (api v3)
    ```

  - Kubernetes Environment and Version

**Additional context**
Add any other context about the feature request here.

**Comment by donnyyung** [comment] 2021-09-29 20:02
Hey @movsb thanks for the issue. We already have an issue open for this so I will close this + link to the duplicated ticket: https://github.com/telepresenceio/telepresence/issues/1607

**Comment by donnyyung** [comment] 2021-09-29 20:02
Duplicate of https://github.com/telepresenceio/telepresence/issues/1607

**Closed as completed by donnyyung** 2021-09-29 20:02 UTC
