### ISSUE TITLE
DNS resolution on macOS fails for various tools

### ISSUE THREAD

**Issue by trietsch** [telepresenceio/telepresence#2682] opened 2022-07-08 14:02 UTC
**Describe the bug**
DNS resolution on macOS 12.3 does not seem to work properly after connecting to a Kubernetes cluster (GKE in my case). cURL succeeds to resolve URLs, Google Chrome as well, but JVM based applications, as well as Go applications, [Evans](https://github.com/ktr0731/evans), and the Kafka command line utilities do not seem to be able to resolve hostnames (`<service-name>.<namespace>:<port>`).
It seems that most applications and tools don't utilize the correct DNS resolver, as they consult the upstream DNS resolver (Cloudflare 1.1.1.1 in my case).

**To Reproduce**
1. `telepresence connect`
2. Connected to the GKE cluster
3. Try `curl some-host.mynamespace/hello` -> works
4. Try `evans -r repl --host some-host.mynamespace` -> fails

**Expected behavior**
No matter what tool I use, they should all be able to utilize the DNS that Telepresence offers.

**Important note**
This behavior does not exist for Telepresence v1 (the deprecated version)

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
Client: v2.6.8 (api v3)
Root Daemon: v2.6.8 (api v3)
User Daemon: v2.6.8 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 macOS 12.3
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
GKE v1.21.12-gke.1500

**Additional context**
Laptop is an M1 Macbook Pro (ARM based)
Verified that the files in `/etc/resolver` exist for all namespaces, as defined in the [docs](https://www.getambassador.io/docs/telepresence/latest/reference/routing/#dns-resolution)

**Comment by ptsteadman** [comment] 2022-08-02 19:51
Using `nslookup` also fails to resolve the domain:
```
➜  dev git: curl -vvv mighty-mouse.thundercats
*   Trying 172.20.40.176:80...
* Connected to mighty-mouse.thundercats (172.20.40.176) port 80 (#0)
> GET / HTTP/1.1
> Host: mighty-mouse.thundercats
> User-Agent: curl/7.79.1
> Accept: */*
>
➜  dev git: nslookup mighty-mouse.thundercats
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find mighty-mouse.thundercats: NXDOMAIN
```

It seems like the issue is that it is trying to resolve the dns using the 192.168.1.1 resolver rather than the telepresence resolver.

**Comment by njayp** [comment] 2022-08-02 22:24
Telepresence currently provides dns on mac by adding custom dns resolvers to `/etc/resolvers/`. nslookup does not use these resolvers. We might be able to follow https://apple.stackexchange.com/questions/74639/do-etc-resolver-files-work-in-mountain-lion-for-dns-resolution/385218#385218 to support nslookup

**Comment by thallgren** [comment] 2022-08-27 06:05
@njayp that won't help. Using `/etc/resolver` is supported. Commands like `nslookup` and `dig` are not supported. From the `nslookup` manpage:
```
Mac OS X NOTICE
   The nslookup command does not use the host name and address resolution or the DNS query routing
   mechanisms used by other processes running on Mac OS X.  The results of name or address queries
   printed by nslookup may differ from those found by other processes that use the Mac OS X native
   name and address resolution mechanisms.  The results of DNS queries may also differ from queries
   that use the Mac OS X DNS routing library.
```

**Comment by thallgren** [comment] 2022-08-27 06:10
@ptsteadman as I pointed out in my previous comment, `nslookup` is not fully supported on macOS. Try using `dscacheutil -q host -a name mighty-mouse.thundercats`

**Comment by thallgren** [comment] 2022-11-13 06:39
Closing this because macOS DNS works as intended.

**Closed as completed by thallgren** 2022-11-13 06:39 UTC

**Comment by trietsch** [comment] 2022-11-13 08:33
@thallgren how come DNS for Telepresence Legacy is working as expected and the new Telepresence is not resolving properly?
This DNS issue makes the new Telepresence unusable for me and that's why I'm still using Telepresence Legacy.
