### ISSUE TITLE
Add support for intercepting multiple ports

### ISSUE THREAD

**Issue by lkoniecz** [telepresenceio/telepresence#2555] opened 2022-04-29 11:30 UTC
**Please describe your use case / problem.**
Deployement has 2 or more business ports. Currently only one can be intercepted which prevents me from testing both endpoints simultaneously.

**Describe the solution you'd like**
Add an option for repeated --port argument

**Describe alternatives you've considered**
None

**Versions (please complete the following information)**
```An update of telepresence from version 2.5.6 to 2.5.8 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client: v2.5.6 (api v3)
Root Daemon: v2.5.6 (api v3)
User Daemon: v2.5.6 (api v3)
```

**Additional context**
Add any other context about the feature request here.

**Comment by thallgren** [comment] 2022-04-30 05:33
Duplicate of #1607

**Closed as completed by thallgren** 2022-04-30 05:33 UTC
