### ISSUE TITLE
telepresence ignores include-suffixes setting

### ISSUE THREAD

**Issue by lkoniecz** [telepresenceio/telepresence#2529] opened 2022-04-14 11:39 UTC
**Describe the bug**

Added following snippet to my kube config
```
- cluster:
      certificate-authority-data: cert_data
      server: server_uir
      extensions:
      - extension:
          dns:
            include-suffixes:
            - .svc
        name: telepresence.io
  name: cluster_name
```
telepresence status does not reflect that change and show empty include-suffixes

```
Root Daemon: Running
  Version   : v2.5.5 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (2 subnets)
    - 54.236.162.187/32
    - 52.22.5.94/32

```

**Expected behavior**
Include suffixes includes domain suffixes

**Versions (please complete the following information):**

```
Client: v2.5.5 (api v3)
Root Daemon: v2.5.5 (api v3)
User Daemon: v2.5.5 (api v3)
```

```Linux INV-13762 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

```EKS 1.23```

problem was already reported here: https://github.com/telepresenceio/telepresence/issues/1943

**Comment by thallgren** [comment] 2022-04-22 05:21
I'm not able to reproduce this. A copy/paste of your example works just fine (".svc" shows up in the status output). Did you quit/connect after the change was made?

Bug 1943 uses incorrect indentation. The `extensions` must be indented to the same level as the cluster's `server`.

**Comment by lkoniecz** [comment] 2022-04-22 06:17
Yes, I did all that, including workstation restart.

**Comment by thallgren** [comment] 2022-04-22 11:13
Then I don't know what to say. The extension mechanism works as intended. Can you add other properties to it such as `also-proxy`?

**Comment by lkoniecz** [comment] 2022-04-22 13:40
I will try that and let you know.

**Comment by thallgren** [comment] 2022-04-25 14:18
@lkoniecz any further input on this?

**Comment by lkoniecz** [comment] 2022-04-26 06:25
Not from my side as I did not have a chance to test it. Do you want to close it soon? I will retest it by tomorrow.

**Comment by thallgren** [comment] 2022-04-26 08:04
I don't want tickets around that we cannot reproduce. Especially if the logic is proven to work (as in this case). So yes, I'd like to close this soon.

**Comment by lkoniecz** [comment] 2022-04-26 08:23
the root cause was telepresence inability to resolve namespace.svc adresses - https://github.com/telepresenceio/telepresence/issues/1722

I have a workaround: https://github.com/telepresenceio/telepresence/issues/1722#issuecomment-939293783 but before modifying charts I tried more telepresence native solution.

anyways I can no longer reproduce it here

```
Root Daemon: Running
  Version   : v2.5.6 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: [.svc]
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (2 subnets)
    - 52.22.5.94/32
    - 54.236.162.187/32
```

please close it

**Closed as completed** 2022-04-30 05:34 UTC
