### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by stefan-culafic-ck** [telepresenceio/telepresence#2027] opened 2021-08-30 18:57 UTC
### What were you trying to do?
Start local dev environment
(please tell us)

### What did you expect to happen?
Start local dev environment
(please tell us)

### What happened instead?
swap-deployment failed
(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'mono-www-blue:ck-service', '--namespace', 'mt-770', '--container-to-host', '9000', '--container-to-host', '4140', '--container-to-host', '4142', '--container-to-host', '9110', '--mount', '/tmp/remote', '--docker-run', '--rm', '--name', 'mono-tp-local', '--mount', 'type=bind,source=/tmp/remote/etc/configs,target=/etc/configs', '--mount', 'type=bind,source=/var/folders/wt/xphks_sd5336trt1kg6r9g_w0000gp/T/tmpp16ja05n/entrypoint.sh,target=/usr/local/bin/entrypoint.sh', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/admax,target=/var/www/git-repos/cs/admax', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/cli,target=/var/www/git-repos/cs/cli', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/config,target=/var/www/git-repos/cs/config', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/config_overrides,target=/var/www/git-repos/cs/config_overrides', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/docroot,target=/var/www/git-repos/cs/docroot', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/logs,target=/var/www/git-repos/cs/logs', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/services,target=/var/www/git-repos/cs/services', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/sql,target=/var/www/git-repos/cs/sql', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/src,target=/var/www/git-repos/cs/src', '--mount', 'type=bind,source=/Users/sculafic.cont/Documents/code/ck_ck/src-generated,target=/var/www/git-repos/cs/src-generated', '-e', 'CK_HOST=www.creditkarma.com', '-e', 'CK_RETROVISION_ADDR=retrovision.ck-service:3000', '-e', 'CK_RETROVISION_SERVER_ADDR=retrovision-server:8080', '-e', 'CK_GEARMAND=gearmand.ck-system:4730', '-e', 'CK_MEMCACHE_1=mono-mcrouter-default.mono-bkg:5000', '-e', 'CK_MEMCACHE_2=mono-mcrouter-default.mono-bkg:5000', '-e', 'CK_IS_PRODUCTION=false', '-e', 'CK_PRINT_ERRORS=true', '-e', 'CK_TESTING=true', '-e', 'CK_LOCAL_TESTING=true', '-e', 'CK_ENVIRONMENT=test', '-e', 'DATACENTER_NAME=cktest-back-end', '-e', 'DATACENTER=cktest-back-end', '-e', 'DOCKER=1', '-e', 'CK_ENABLE_CONFIG_OVERRIDES=true', '-p', '30443:443', '-p', '38080:8080', '--mount', 'type=bind,source=/var/folders/wt/xphks_sd5336trt1kg6r9g_w0000gp/T/tmpp16ja05n/01-xdebug.ini,target=/etc/php.d/01-xdebug.ini', 'gold.artifactory.corp.creditkarma.com/ck/ck:0.0.1_v21.34B.00-1629764858-f09d0e8eac0a']`
Version: `0.109`
Python version: `3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.22.1 // Server Version: v1.20.8-gke.900`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin C02XR6B8JGH6 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 52, in main
    launch = outbound.setup(runner, args)
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 183, in setup
    return setup_container(runner, args)
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 141, in setup_container
    reveal=True,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 487, in get_output
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 430, in _run_command_sync
    None if

**Comment by thallgren** [comment] 2021-09-01 09:06
There's not much we can do with a bug report like this. We need to know how it failed. Was it a timeout? A permission problem? A network problem? All this tells us is "swap-deployment failed".

Is there any way we can reproduce the failure?

**Comment by thallgren** [comment] 2021-09-03 10:46
Closing due to lack of info.

**Closed as completed by thallgren** 2021-09-03 10:46 UTC
Labels: crash instead of error, v1
