### ISSUE TITLE
DNS Errors after connecting with telepresence on Windows

### ISSUE THREAD

**Issue by mbrunneritlabs** [telepresenceio/telepresence#3619] opened 2024-06-13 15:27 UTC
Versions: We tried different versions. No combination worked so far. 
Currently we have: 

  Version    : v2.19.6 (My machine = Win 11 pro, Build 22631.3593)

Traffic Manager: Connected
  Version      : v2.19.4

I am trying to intercept services in our k8s cluster from my windows machine.
While intercepting and debugging my services i cannot connect to our database cluster due to DNS problems. 

Running nslookup www.google.com doesnt work while being connected with telepresence. 

I get: 

nslookup www.google.com
Server:  UnKnown
Address:  1X.2XX.X.1XX   // The Xs are added by me. 

*** www.google.com UnKnown not found: Non-existent domain.

After quitting telepresence it works fine again. 

All our colleagues running MacOS do not have this problem.
All our colleagues with Windows have the same issue. 

It seems something goes wrong with the DNS on Windows while being connected with telepresence. 

Any ideas how to solve this?

Thanks!

**Comment by thallgren** [comment] 2024-06-14 14:44
Did this problem start after an upgrade to 2.19.6? If so, what version did you use prior to the upgrade?

**Comment by mbrunneritlabs** [comment] 2024-06-14 14:53
We tried various versions between 2.11.1 and 2.19.6 in the cluster and on client. 

The behaviour was always that in worked on MacOS but the DNS was broken on different Windows machines after connecting. 

We thought that it might be the same problem as described in this issue, but the instructions were not clear enough to fix it. 

https://github.com/telepresenceio/telepresence/issues/2429

Again it seems that after connecting with telepresence on windows it seems, that the DNS names are routed to the cluster for some reason and they cant be resolved. 

My example is as follows:

I have code in my service that has a connectionstring defined for a database. 
If i debug this code on my machine without telepresence everything works fine and my database connection can be established.

If I intercept the service in my cluster from my machine with telepresence and debug it, the database connections fails as it cannot be resolved.

**Comment by thallgren** [comment] 2024-06-17 03:47
Can you try a command like `curl -L www.google.com` and see if that works? I suspect it will. The reason is that the `nslookup` command will select the _primary DNS resolver_ and give up if it doesn't work, and that's not what a normal network lookup would do. The `nslookup` is very special in this respect. It will not traverse the full list of DNS servers.

The _primary DNS resolver_ is the one that has the lowest metric, and Windows will automatically assign a low metric value to a virtual network device such as the one that Telepresence creates. You can see the metric values of your adapters using Powershell:
```
Get-NetIPInterface
```
Run this command with Telepresence connected, and you'll see that "tel0" (the interface that is added) has the lowest `InterfaceMetric`.

Let's assume that the _second lowest_ metric is 25 and that "tel0" has `ifIndex` of 10 in the list. To prove the `nslookup` behavior described above, you can change the metric of interface 10 to something higher, like this:
```
Set-NetIPInterface -InterfaceIndex 10 -InterfaceMetric 30
```
This will put the interface with the second lowest metric back as the primary one.  Now try `nslookup www.google.com` again, and it will resolve correctly.

We could of course ensure that Telepresence gets a higher metric value, and therefore is moved down on the list, but then `nslookup` would instead be unable to find things in the cluster, so that would probably be even worse.

Just to make `nslookup` work, we could make Telepresence use a fallback instead of returning  a name error on domains that it doesn't find, but I don't want to do that because this is already implemented in the DNS system. The `nslookup` command just doesn't use it.

**Comment by mbrunneritlabs** [comment] 2024-06-17 11:54
Thanks for explaining. 

I double checked and it is not a general DNS problem.

Calling www.google.com works fine in my service.

BUT now I understand a bit deeper where my failing database connections comes from.

We are creating a mongoDB Client in the startup phase of our service with MongoClient.connect(...)

I digged deep into their code and somewhere they call "resolveTxt" of a Node DNS function. 

https://www.geeksforgeeks.org/node-js-dns-resolvetxt-method/

This call crashes for some reason  when using telepresence.

Whats interesting is, that when debugging slowly sometimes it works. 

So I assume some kind of race condition between the Node DNS Resolver, Mongo Client and Telepresence!?

**Comment by mbrunneritlabs** [comment] 2024-06-17 12:02
I can reproduce this error without mongo db involved.

Just call this in app.ts of my service.
```

dns.resolveTxt('MY MONGO DB STRING', (err, record) => {
    console.log('resolve txt callback');
    if (err) {
      console.log('err');
      console.log(err);
    }
    if (record) {
      console.log('record');
    }
  });


```

It fails all the time, except if i wait a few seconds in a breakpoint.

**Comment by thallgren** [comment] 2024-06-17 13:05
It would be interesting to see what Telepresence does with that TXT query. It should resolve it.

Can you provide the relevant parts of the `daemon.log`?

**Comment by mbrunneritlabs** [comment] 2024-06-17 15:09
When i run 
`telepresence gather-logs` and open the `daemon.log` file: 

I only see entries for my connect command  like `Adding pod subnet` etc. 

But I do not see any later entries when I make the failing `dns.resolvetxt` call in the node library. It ends with the conncect logs.

**Comment by thallgren** [comment] 2024-06-17 17:03
Try using `telepresence loglevel debug --local-only` and then run again. There's no need to run `gather-logs`. You'll find the log file under `%USERPROFILE%\AppData\Local\telepresence\logs`.

**Comment by mbrunneritlabs** [comment] 2024-06-17 18:53
Thanks. 

So i see an entry for the failing call. 


```
2024-06-17 20:48:39.5487 debug   daemon/session/dns/Server : ServeDNS 11919 TXT    geeksforgeeks.org.
2024-06-17 20:48:39.5487 debug   daemon/session/dns/Server : 11919 TXT    geeksforgeeks.org. -> NXDOMAIN 
```

Close to that i also see this log ( I replaced X)

`2024-06-17 20:48:53.4960 error   daemon/session/watch-cluster-info :    CONN udp 1X.2XX.5.0:6XXXX -> 1XX.0.0.1:5XXXstream-to-conn loop ended because a write error occurred: write udp 1X.2XX.5.2XX:5X: connection was refused`

**Comment by mbrunneritlabs** [comment] 2024-06-17 19:00
I added a loop to the start of my app, where I call the dns.resolveTxt function of node and then i get this in the logs:

```
2024-06-17 20:59:01.6840 debug   daemon/session/dns/Server : ServeDNS 12969 TXT    geeksforgeeks.org.
2024-06-17 20:59:01.6840 debug   daemon/session/dns/Server : ServeDNS  6898 TXT    geeksforgeeks.org.
2024-06-17 20:59:01.6840 debug   daemon/session/dns/Server : ServeDNS  9531 TXT    geeksforgeeks.org.
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : ServeDNS 30363 TXT    geeksforgeeks.org.
2024-06-17 20:59:01.6840 debug   daemon/session/dns/Server : 12969 TXT    geeksforgeeks.org. -> NXDOMAIN 
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : 30363 TXT    geeksforgeeks.org. -> NXDOMAIN 
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server :  6898 TXT    geeksforgeeks.org. -> NXDOMAIN 
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : ServeDNS 12317 TXT    geeksforgeeks.org.
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : 12317 TXT    geeksforgeeks.org. -> NXDOMAIN 
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server :  9531 TXT    geeksforgeeks.org. -> NXDOMAIN 
```

**Comment by thallgren** [comment] 2024-06-18 05:28
A ".org" address will not get resolved by Telepresence unless you explicitly tell it to, because it's in the default `excludeSuffixes` list, so besides the UDP failure, those logs are to be expected. The address should be resolved by your DNS system though, with or without Telepresence connected. Do you see a difference in that respect?

**Comment by mbrunneritlabs** [comment] 2024-06-18 06:58
Yes. Without telepresence connection everything works fine. 
The .org address was just an example. Normally the database is resolved there. 

When I have telepresence connected the function in the above mentioned Node DNS Library fails all the time. 

What is very weird is, that it works if I set a breakpoint right after the call. 

I am not sure exactly what is going on, but it seems like a race condition..

**Comment by thallgren** [comment] 2024-06-18 07:05
Yes, it's probably timing related. The DNS lookup takes slightly longer to complete when Telepresence is involved, because it is consulted first. The lookup then proceeds to the next DNS resolver which succeeds. Weird that a breakpoint _after_ the call helps though, but perhaps you have some backoff/retry logic that needs a delay in order to function.

**Comment by mbrunneritlabs** [comment] 2024-06-18 10:01
Yes but i think the node dns function is an elemental low level function that shouldnt break when being connected to telepresence right? 

I want to summarize what I found:

- The root cause is the Node DNS Resolver function
-  It is implemented like that   
```
const dns = require('dns').promises;
const addresses = await dns.resolveSrv(`_mongodb._tcp.XXXXX.qmxmb.mongodb.net`);
```
Case 1: 
So without telepresence connected it resolves correctly.
Interesting: dns.getServers() gives one DNS Server (192.XXX.XX)

Case 2: 
When connected to telepresence dns.getServer() outputs 2 DNS Server. The first one being 10.244.XXX.XX and the second one being the same as the first one (I think my local one)

When calling the resolve function in this case it throws an error. It seems like it doesnt really look in the second one or throws before.

Case 3:
While being connected to telepresence i tried setting the dns server with dns.setServer() to Case 1.
This makes the DB Connection work, but I dont think its the right approach. 

```
const dns = require('dns').promises;
dns.setServers(['XXXX', 'XXX']);
const addresses = await dns.resolveSrv(`_mongodb._tcp.XXXXX.qXXXX.mongodb.net`);
```

**Comment by mbrunneritlabs** [comment] 2024-06-18 11:42
Why does it even try to resolve the mongo string at the cluster?

when running telepresence status I see:

`Exclude suffixes: [.com .io .net .org .ru]`

Shouldnt this make the .net address of my mongo database always be resolved locally?

**Comment by thallgren** [comment] 2024-06-20 07:35
I don't think it tries to resolve the .net address in the cluster. An entry like this:
```
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : ServeDNS 30363 TXT    geeksforgeeks.org.
```
tells us that the client's DNS server received the query. And this:
```
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : 30363 TXT    geeksforgeeks.org. -> NXDOMAIN
```
was the response to that query, which means that it was rejected immediately and never sent to the cluster. If it were, you'd see an entry like:
```
2024-06-17 20:59:01.6845 debug   daemon/session/dns/Server : Lookup TXT "geeksforgeeks.org."
```
but that never happens.

**Comment by thallgren** [comment] 2024-06-20 07:39
It's strange though, that your dns system gives up on the first server when it has multiple services to query. Would it be possible for you to create a reproducer that I can try on my Windows box?

**Comment by mbrunneritlabs** [comment] 2024-06-20 11:53
[Telepresence_DNS_Error.zip](https://github.com/user-attachments/files/15913123/Telepresence_DNS_Error.zip)

Thanks a lot. Attached a very small Project.

To start the code: 

Install Node Version Manager and install Node 20. (nvm i 20)
Run npm i (npm required)

Start "Launch Program" in launch.json

This call in app.ts fails when connected to telepresence and works if not. 

>   const addresses = await dns.resolveSrv(`www.test.com`);

**Comment by thallgren** [comment] 2024-06-20 13:56
Thanks. I was able to reproduce the problem. AFAICT, the behavior of the `dns.resolveSrv` is the same as for `nslookup`, i.e. it just doesn't do a normal resolve. Instead it just uses the first resolver in the list. And the [documentation](https://nodejs.org/api/dns.html) confirms this.

Excerpt from `dns.lookup` function:

> To perform name resolution the way other applications on the same system do, use [dns.lookup()](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback).

and then further down:
> All other functions in the node:dns module connect to an actual DNS server to perform name resolution. They will always use the network to perform DNS queries. These functions do not use the same set of configuration files used by [dns.lookup()](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback) (e.g. /etc/hosts). Use these functions to always perform DNS queries, bypassing other name-resolution facilities.

This means that if you want to benefit from more dynamic DNS in your app, you must use `lookup` (and presumably `lookupService`). The `resolveXXX` methods will not go through the required motions.

**Comment by mbrunneritlabs** [comment] 2024-06-20 15:20
Ok I understand. Thanks for looking into that. 

Unfortunately the problematic function is called in a Mongo Database Library...

So you would say this a problem in their library? 

If so maybe opening an issue there would be next step. 

Practically this means you cannot use Mongo Database Library and telepresence on Windows...

**Comment by thallgren** [comment] 2024-06-24 12:49
@mbrunneritlabs, I'm working on a solution for this that shows some promise where the Telepresence DNS uses the former top-entry of the DNS-server list as its fallback. By doing so, the `nslookup` works, because the fallback server is utilized when Telepresence doesn't find an entry. This also makes the `resolveSrv` call in your reproducer work.

I'm going to create a test version for this. Would you be able to download it (from our regular download site) and try it out?

**Comment by mbrunneritlabs** [comment] 2024-06-24 14:07
@thallgren 
Sounds great! Thanks for your effort. 

Sure if a version is available I can test it.

**Comment by thallgren** [comment] 2024-06-26 06:24
@mbrunneritlabs, a `2.20.0-test.3` release is now available from our [download site](https://www.getambassador.io/docs/telepresence/latest/install?os=windows). You can download it by replacing "latest" with "2.20.0-test.3" in the download URL.

I'm looking forward to  your feedback.

**Comment by mbrunneritlabs** [comment] 2024-06-26 10:14
Thanks!

When trying to intercept with your version I get: telepresence intercept: error: telepresence cloud daemon is not running

Do I need to upgrade the version in my cluster?

**Comment by thallgren** [comment] 2024-06-26 10:57
No, that's not necessary. Try this:
```
telepresence quit -s
del "%USERPROFILE%\AppData\Local\Telepresence\cloudd-address.json"
```
If you still experience a problem, try quit -s again and then terminating all processes named telepresence, in case something is lingering on your machine.

**Comment by mbrunneritlabs** [comment] 2024-06-27 07:42
Thanks!

It seems the version works on my windows machine. No more database connection errors :)

**Comment by thallgren** [comment] 2024-06-27 09:42
Thanks for verifying that.

**Comment by thallgren** [comment] 2024-07-21 07:19
Closing this now, because changes were delivered in release 2.19.1.

**Closed as completed by thallgren** 2024-07-21 07:19 UTC
