### ISSUE TITLE
transport: Error while dialing dial unix /tmp/telepresence-connector.socket: connect: connection refused

### ISSUE THREAD

**Issue by deveshgithub** [telepresenceio/telepresence#1818] opened 2021-06-24 20:00 UTC
### sw_vers 
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	        20E241

### kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.16) exceeds the supported minor version skew of +/-1

### telepresence version
Client: v2.3.2 (api v3)
Root Daemon: v2.3.2 (api v3)
User Daemon: not running

### telepresence connect
Connecting to traffic manager...
Disconnecting...failed
telepresence: error: connector.Connect: failed to start traffic manager: failed to create MutatingWebhookConfiguration agent-injector-webhook-ambassador.: MutatingWebhookConfiguration.admissionregistration.k8s.io "agent-injector-webhook-ambassador" is invalid: webhooks[0].admissionReviewVersions: Invalid value: []string{"v1"}: must include at least one of v1beta1
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/telepresence-connector.socket: connect: connection refused"

**Comment by adamgoose** [comment] 2021-06-29 16:24
I'm running into the same thing. I suspect that the issue has more to do with the Kubernetes Cluster version, as we're both on 1.16.

**Comment by adamgoose** [comment] 2021-06-29 17:40
Probably a dupe of #1809

**Comment by thallgren** [comment] 2021-06-30 13:33
Closing as duplicate of #1809

**Closed as completed by thallgren** 2021-06-30 13:33 UTC
