### ISSUE TITLE
telepresence intercept command does not work with service with two TCP ports

### ISSUE THREAD

**Issue by FedericoDelSaz** [telepresenceio/telepresence#3413] opened 2023-11-02 15:52 UTC
**Describe the bug**
I have tried to intercept service with two ports, first one is number  8080 TCP name http and second one 8090 TCP name http-management.
I  would just like to intercept 8080.

EKS: 1.24
Telepresence version: I have tested with 2.15.0  and 2.16.1
Telepresence CLI: I have tested with 2.15.0 and 2.16.1

I have tested with services with one port and telepresence works. I have adapt my service and deployment and I have removed 8090 port and readiness and leaveness setup, and It has worked. any idea?

I have tested to apply: kubectl patch deployment traffic-manager -n telepresence -p '{"spec":{"template":{"spec":{"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true}}}}' and nothing.

```
telepresence loglevel debug

* reproduce the error *

telepresence intercept my-service-name --port 8080:http

telepresence intercept: error: connector.CreateIntercept: request timed out while waiting for agent my-service-name.my-service-namespace to arrive: Events that may be relevant:
AGE   TYPE      REASON      OBJECT                                          MESSAGE
30s   Warning   Unhealthy   pod/my-service-name6   Readiness probe failed: HTTP probe failed with statuscode: 503
30s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: HTTP probe failed with statuscode: 503
30s   Warning   Unhealthy   pod/my-service-name  Readiness probe failed: HTTP probe failed with statuscode: 503
14s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

13s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: Get "http:///healthz/ready": dial tcp :15021: connect: connection refused
14s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

14s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

14s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

14s   Warning   Unhealthy   pod/my-service-name   Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory


k describe configmap telepresence-agents

Name:         telepresence-agents
Namespace:   my-service-namespace
Labels:       app.kubernetes.io/created-by=traffic-manager
              app.kubernetes.io/name=telepresence-agents
              app.kubernetes.io/version=2.15.0
Annotations:  <none>

Data
====
my-service-name:
----
agentImage: /telepresence/datawire/tel2:2.16.1
agentName: my-service-name
containers:
- Mounts: null
  envPrefix: A_
  intercepts:
  - agentPort: 9900
    containerPort: 8080
    containerPortName: http
    protocol: TCP
    serviceName: my-service-name
    servicePort: 8080
    servicePortName: http
    serviceUID: 
  - agentPort: 9901
    containerPort: 8090
    containerPortName: http-management
    protocol: TCP
    serviceName: my-service-name
    servicePort: 8090
    servicePortName: http-management
    serviceUID: 
  mountPoint: /tel_app_mounts/my-service-name
  name: my-service-name
logLevel: debug
managerHost: traffic-manager.telepresence
managerPort: 8081
namespace: my-service-namemespace
pullPolicy: Always
tracingPort: 15766
workloadKind: Deployment
workloadName: my-service-name


BinaryData
====

Events:  <none>
-----------------------------------

traffic-agent logs

2023-11-02 15:43:05.0256 info    Traffic Agent v2.16.1
2023-11-02 15:43:05.0260 debug   Logging at this level "debug"
2023-11-02 15:43:05.0261 info    Adding exported mounts for container my-service-name
2023-11-02 15:43:05.0274 info    ftp-server : FTP server listening on :43961
2023-11-02 15:43:05.0279 debug   forward-my-service-name:8090 : Forwarding from :9901
2023-11-02 15:43:05.0280 debug   forward-my-service-name:8080 : Forwarding from :9900
2023-11-02 15:43:05.0281 info    ftp-server : Starting FTP server
2023-11-02 15:43:05.0287 info    ftp-server : Listening... : address=":43961"
2023-11-02 15:43:05.0287 info    ftp-server : Starting...

**Comment by FedericoDelSaz** [comment] 2023-11-06 07:02
│ 2023-11-06 05:18:08.9897 info    Traffic Agent v2.16.1                                               │
│ 2023-11-06 05:18:08.9903 debug   Logging at this level "debug"                                       │
│ 2023-11-06 05:18:08.9903 info    Adding exported mounts for container y-service-name          │
│ 2023-11-06 05:18:08.9921 info    ftp-server : FTP server listening on :40233                         │
│ 2023-11-06 05:18:08.9922 info    ftp-server : Starting FTP server                                    │
│ 2023-11-06 05:18:08.9922 info    ftp-server : Listening... : address=":40233"                        │
│ 2023-11-06 05:18:08.9922 info    ftp-server : Starting...                                            │
│ 2023-11-06 05:18:08.9925 debug   forward-y-service-name:8080 : Forwarding from :9900

**Comment by cindymullins-dw** [comment] 2023-11-06 20:09
Hi @FedericoDelSaz , can you share your Service with us, so we can see how your ports are assigned?

**Comment by thallgren** [comment] 2023-11-06 21:53
We have CI-tests that verify that using multiple ports work as expected, so this must be something else. From the looks of it, the traffic-agent starts up and forwards both ports but it never reaches the ready state because it hangs when trying to connect to the traffic-manager. You should see a message saying "Connected to Manager 2.16.1". My guess is that you have some policy that prevents the traffic-agent from calling the traffic-manager.

**Comment by FedericoDelSaz** [comment] 2023-11-07 14:42
@thallgren 
The problem is that sometimes it works and sometimes it doesn't, basically with the springboot application because with the node telepresence application it always works. You're right, maybe something is preventing the connection between traffic-agent and traffic-manager, but I've had a look at the network policy and we don't have it. I've thought about deploying telepresence inside the application namespace, but I think it's not necessary because I've deployed the application node with a port and telepresence always works, so maybe it's an application problem.

I have managed to run intercept on the spring boot application but I have to follow the following steps:
1. intercept the application, it doesn't work and I get an error message: eadiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory.
2. I have to redeploy the telepresence by modifying, for example, the arrival time number (it doesn't matter if I increase or decrease the timeout value), and suddenly I get traffic-agent ready. 

To solve the possible port problem I used the following annotations:
telepresence.getambassador.io/inject-service-name: application-name telepresence.getambassador.io/inject-service-port: port-name

and in service I have followed: Injected init-container does not work correctly in [telepresence troubleshooting](https://www.getambassador.io/docs/telepresence/latest/troubleshooting#injected-init-container-doesnt-function-properly).  

service.yaml

`apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: 
    meta.helm.sh/release-namespace: 
  labels:
    helm.sh/chart: 
  name: 
  namespace: 
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: http-management
    port: 8090
    protocol: TCP
    targetPort: http-management
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}`

----
agentImage: elepresence/datawire/tel2:2.16.1
agentName: 
containers:
- Mounts: null
  envPrefix: A_
  intercepts:
  - agentPort: 9900
    containerPort: 8080
    containerPortName: http
    protocol: TCP
    serviceName: 
    servicePort: 8080
    servicePortName: http
    serviceUID: 
  mountPoint: /tel_app_mounts/
  name: 
logLevel: info
managerHost: traffic-manager.telepresence
managerPort: 8081
namespace:
pullPolicy: Always
tracingPort: 15766
workloadKind: Deployment
workloadName:
`

**Comment by FedericoDelSaz** [comment] 2023-11-07 15:33
################################################################################
  ## Deployment Configuration
  ################################################################################
  logLevel: info
  timeouts:
    agentArrival: 60s

    webhook:
      port: 8443
      timeoutSeconds: 30

  ################################################################################
  ## Telepresence traffic-agent configuration
  ################################################################################
  agent:
    logLevel: info
    appProtocolStrategy: http2Probe

**Comment by thallgren** [comment] 2023-11-07 21:23
Your configuration looks correct. I don't think that's the problem. Your agent cannot talk to the manager and therefore fails to reach the ready state, nothing you do will help unless you solve that problem. 

What does the traffic-manager log look like? Do you see any "ArriveAsAgent called" messages there?

**Comment by FedericoDelSaz** [comment] 2023-11-08 09:59
Traffic-manager logs:

traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.7855 debug   httpd/conn=127.0.0.1:8081 : PrepareIntercept called : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.8084 debug   agent-configs : MODIFIED telepresence-agents.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.8084 debug   agent-configs : add sample-application-dev2i.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.8525 info    agent-configs : Successfully rolled out sample-application-dev2i.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.8945 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.8951 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request CREATE sample-application-dev2i-85dfbcb767-.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9031 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9048 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE sample-application-dev2i-75df874dd8-5dmxr.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9083 info    agent-injector/conn=172.25.21.159:8443 : Injecting traffic-agent into pod sample-application-dev2i-85dfbcb767-.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9084 info    agent-injector/conn=172.25.21.159:8443 : Injecting 7 patches into pod sample-application-dev2i-85dfbcb767-.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9085 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:34.9124 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.0039 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.0051 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request CREATE sample-application-dev2i-85dfbcb767-.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.0196 info    agent-injector/conn=172.25.21.159:8443 : Injecting traffic-agent into pod sample-application-dev2i-85dfbcb767-.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.0201 info    agent-injector/conn=172.25.21.159:8443 : Pod sample-application-dev2i-85dfbcb767-.application-name already has container traffic-agent and it isn't modified
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.0201 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:35.4495 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: HTTP probe failed with statuscode: 503 : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:36.8514 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:37.4557 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: HTTP probe failed with statuscode: 503 : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:38.1472 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:39.1782 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:39.4539 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: HTTP probe failed with statuscode: 503 : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.1012 debug   podWatcher calling updateSubnets with [172.25.0.0/17]
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.1840 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.1854 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE sample-application-dev2i-75df874dd8-5dmxr.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.1946 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2068 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2078 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE sample-application-dev2i-75df874dd8-5dmxr.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2193 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2281 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2292 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE sample-application-dev2i-75df874dd8-5dmxr.application-name
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.2389 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:41.7649 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:43.5870 info    httpd/conn=127.0.0.1:8081 : Warning FailedGetResourceMetric failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:43.5978 info    httpd/conn=127.0.0.1:8081 : Warning FailedComputeMetricsReplicas invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:44.2272 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.4637 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6035 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6041 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE mcc-dev1-process-message-overdue-status-28323930-9lpn4.dc-app-xsp
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6042 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6189 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6200 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE mcc-dev1-process-message-overdue-status-28323930-9lpn4.dc-app-xsp
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6201 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6334 debug   agent-injector/conn=172.25.21.159:8443 : Received webhook request...
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6342 debug   agent-injector/conn=172.25.21.159:8443 : Handling admission request DELETE mcc-dev1-process-message-overdue-status-28323930-9lpn4.dc-app-xsp
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:45.6342 debug   agent-injector/conn=172.25.21.159:8443 : Webhook request handled successfully
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:46.1012 debug   podWatcher calling updateSubnets with [172.25.0.0/17]
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:53.3697 debug   httpd/conn=127.0.0.1:8081 : LookupDNS zoomfraro213zc.fra.zoom.us. AAAA : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:53.3697 debug   httpd/conn=127.0.0.1:8081 : LookupDNS zoomfrarp213zc.fra.zoom.us. AAAA : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:53.3715 debug   httpd/conn=127.0.0.1:8081 : LookupDNS on traffic-manager: zoomfraro213zc.fra.zoom.us. AAAA -> NOERROR : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:53.3716 debug   httpd/conn=127.0.0.1:8081 : LookupDNS on traffic-manager: zoomfrarp213zc.fra.zoom.us. AAAA -> NOERROR : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:54.2476 debug   httpd/conn=127.0.0.1:8081 : LookupDNS zoomfraro107mmr.fra.zoom.us. AAAA : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:54.2500 debug   httpd/conn=127.0.0.1:8081 : LookupDNS on traffic-manager: zoomfraro107mmr.fra.zoom.us. AAAA -> NOERROR : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:55.4676 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:56.1011 debug   podWatcher calling updateSubnets with [172.25.0.0/17]
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:58.6082 info    httpd/conn=127.0.0.1:8081 : Warning FailedGetResourceMetric failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:00:58.6186 info    httpd/conn=127.0.0.1:8081 : Warning FailedComputeMetricsReplicas invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:01:15.4658 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:01:25.4491 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: HTTP probe failed with statuscode: 500 : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"
traffic-manager-999899ccc-ktclg 2023-11-08 10:01:25.4643 info    httpd/conn=127.0.0.1:8081 : Warning Unhealthy Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
traffic-manager-999899ccc-ktclg  : session_id="d6bf1112-d41d-4dc5-88ac-8c063ee093f9"

telepresence intercept output:

telepresence intercept: error: connector.CreateIntercept: request timed out while waiting for agent application-name-application-application-name.application-name to arrive: Events that may be relevant:
AGE   TYPE      REASON                         OBJECT                                             MESSAGE
59s   Warning   Unhealthy                      pod/application-name-application-application-name-75df874dd8-5dmxr      Readiness probe failed: HTTP probe failed with statuscode: 503
59s   Warning   Unhealthy                      pod/application-name-application-application-name-75df874dd8-5dmxr      Readiness probe failed: HTTP probe failed with statuscode: 503
56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

59s   Warning   Unhealthy                      pod/application-name-application-application-name-75df874dd8-5dmxr      Readiness probe failed: HTTP probe failed with statuscode: 503
51s   Warning   FailedGetResourceMetric        horizontalpodautoscaler/application-name-application-application-name   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
51s   Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/application-name-application-application-name   invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

51s   Warning   FailedGetResourceMetric        horizontalpodautoscaler/application-name-application-application-name   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
51s   Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/application-name-application-application-name   invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

9s    Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: HTTP probe failed with statuscode: 500
56s   Warning   Unhealthy                      pod/application-name-application-application-name-85dfbcb767-4g9vs      Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory

**Comment by FedericoDelSaz** [comment] 2023-11-13 10:02
any update ?

**Comment by thallgren** [comment] 2023-11-15 14:48
No. The problem remains. Your traffic-agent is unable to talk to  your traffic-manager.

**Comment by cindymullins-dw** [comment] 2023-12-18 17:39
@FedericoDelSaz, could this be a networking issue.  Do you have a network policy that prevents the traffic agent in one namespace from talking to a traffic manager in another namespace for example?

**Comment by thallgren** [comment] 2024-01-10 09:53
Closing this as we have no way of reproducing the problem. Feel free to reopen if you can provide a reproducer.

**Closed as completed by thallgren** 2024-01-10 09:53 UTC
