### ISSUE TITLE
Requests to traffic manager are throttled allowing only one requests per 100ms per URL

### ISSUE THREAD

**Issue by AlexBrohshtut** [telepresenceio/telepresence#2459] opened 2022-03-08 15:26 UTC
**Describe the bug**
Requests to `traffic-manager` are throttled.

We tried different scenarios, and it seems like this:
* Requests to the same URL made within **LESS THAN** 100ms window are throttled and processed every 5 seconds
* Requests to the same URL made within **MORE THAN** 100ms window are not throttled and working good
* Requests to the different URLs are not being throttled despite being sent at the same time

Maybe it is misconfiguration of client / traffic-manager / telepresence? 

**To Reproduce**
Connect to telepresence to intercept all traffic 
Run following Node snippets (URLs can be any, as long as they are within the cluster): 

The following code produces two requests and waits until they are completed:

```js
(async function() {
  for (let j = 0; j < 20; j++) {
    const promises = [];
    for (let i = 1; i <= 2; i++) {
      promises.push(async () => {
        const res = await axios.get('http://elasticsearch:9200/');
        console.log(`${new Date().toISOString()} statusCode: ${res.status}, i: ${i}, j: ${j}`);
      });
    }

    await Promise.all(promises.map((p) => p()));
  }
})();

```

Output below clearly shows 5 seconds delay between requests:
```log
node test.js                                                                                                
2022-03-08T14:51:11.640Z statusCode: 200, i: 1, j: 0
2022-03-08T14:51:16.606Z statusCode: 200, i: 2, j: 0

2022-03-08T14:51:21.921Z statusCode: 200, i: 1, j: 1
2022-03-08T14:51:21.921Z statusCode: 200, i: 2, j: 1

2022-03-08T14:51:22.422Z statusCode: 200, i: 1, j: 2
2022-03-08T14:51:24.832Z statusCode: 200, i: 2, j: 2

2022-03-08T14:51:25.332Z statusCode: 200, i: 1, j: 3
2022-03-08T14:51:30.129Z statusCode: 200, i: 2, j: 3

2022-03-08T14:51:35.581Z statusCode: 200, i: 2, j: 4
2022-03-08T14:51:35.582Z statusCode: 200, i: 1, j: 4

```

Modified code sends 3 requests at once to different endpoints:
```js
const axios = require('axios');

(async function() {
  for (let j = 0; j < 20; j++) {
    const promises = [];
    for (let i = 1; i <= 1; i++) {
      promises.push(async () => {
        const res = await axios.get('http://elasticsearch:9200/');
        console.log(`${new Date().toISOString()} statusCode: ${res.status}, i: ${i}, j: ${j}`);
      });
      promises.push(async () => {
        const res = await axios.get('http://elasticsearch6:9200/');
        console.log(`${new Date().toISOString()} statusCode: ${res.status}, i: ${i}, j: ${j}`);
      });
      promises.push(async () => {
        const res = await axios.get('http://elasticsearch7:9200/');
        console.log(`${new Date().toISOString()} statusCode: ${res.status}, i: ${i}, j: ${j}`);
      });
    }

    await Promise.all(promises.map((p) => p()));
  }
})();
```

The output shows that no throttling was observed: 
```
2022-03-08T14:57:04.689Z statusCode: 200, i: 1, j: 0
2022-03-08T14:57:04.874Z statusCode: 200, i: 1, j: 0
2022-03-08T14:57:04.908Z statusCode: 200, i: 1, j: 0

2022-03-08T14:57:05.244Z statusCode: 200, i: 1, j: 1
2022-03-08T14:57:05.244Z statusCode: 200, i: 1, j: 1
2022-03-08T14:57:05.245Z statusCode: 200, i: 1, j: 1

2022-03-08T14:57:05.579Z statusCode: 200, i: 1, j: 2
2022-03-08T14:57:05.580Z statusCode: 200, i: 1, j: 2
2022-03-08T14:57:05.580Z statusCode: 200, i: 1, j: 2

```

Same code, but requests are sent 100ms one after another:
```js
const axios = require('axios');

(async function() {
  for (let j = 0; j < 20; j++) {
    const promises = [];
    for (let i = 1; i <= 2; i++) {
      promises.push(async () => {
        return new Promise((resolve) => {
          setTimeout(() => {
            axios.get('http://elasticsearch:9200/').then((res) => {
              console.log(
                `${new Date().toISOString()} statusCode: ${res.status}, i: ${i}, j: ${j}`
              );
              resolve();
            });
          }, 100);
        });
      });
    }

    await Promise.all(promises.map((p) => p()));
  }
})();
```

Output:
```
2022-03-08T15:20:10.086Z statusCode: 200, i: 1, j: 0
2022-03-08T15:20:10.087Z statusCode: 200, i: 2, j: 0
2022-03-08T15:20:10.480Z statusCode: 200, i: 1, j: 1
2022-03-08T15:20:10.482Z statusCode: 200, i: 2, j: 1
2022-03-08T15:20:10.925Z statusCode: 200, i: 2, j: 2
2022-03-08T15:20:10.925Z statusCode: 200, i: 1, j: 2
2022-03-08T15:20:11.364Z statusCode: 200, i: 1, j: 3
2022-03-08T15:20:11.384Z statusCode: 200, i: 2, j: 3

```

**Expected behavior**
Requests are not being throttled

**Versions (please complete the following information):**
```
Client: v2.5.3 (api v3)
Root Daemon: v2.5.3 (api v3)
User Daemon: v2.5.3 (api v3)
```
 - macOS Monterey
 - AWS Kubernetes

Thanks.

**Comment by thallgren** [comment] 2022-03-10 16:28
I'm not able to reproduce this. The first sample gives me the following outout:
```
2022-03-10T16:24:22.425Z statusCode: 200, i: 1, j: 0
2022-03-10T16:24:22.427Z statusCode: 200, i: 2, j: 0
2022-03-10T16:24:22.436Z statusCode: 200, i: 2, j: 1
2022-03-10T16:24:22.436Z statusCode: 200, i: 1, j: 1
2022-03-10T16:24:22.443Z statusCode: 200, i: 2, j: 2
2022-03-10T16:24:22.443Z statusCode: 200, i: 1, j: 2
2022-03-10T16:24:22.451Z statusCode: 200, i: 2, j: 3
2022-03-10T16:24:22.451Z statusCode: 200, i: 1, j: 3
2022-03-10T16:24:22.464Z statusCode: 200, i: 2, j: 4
2022-03-10T16:24:22.465Z statusCode: 200, i: 1, j: 4
2022-03-10T16:24:22.476Z statusCode: 200, i: 2, j: 5
2022-03-10T16:24:22.476Z statusCode: 200, i: 1, j: 5
2022-03-10T16:24:22.485Z statusCode: 200, i: 2, j: 6
2022-03-10T16:24:22.486Z statusCode: 200, i: 1, j: 6
2022-03-10T16:24:22.492Z statusCode: 200, i: 2, j: 7
2022-03-10T16:24:22.493Z statusCode: 200, i: 1, j: 7
2022-03-10T16:24:22.501Z statusCode: 200, i: 2, j: 8
2022-03-10T16:24:22.501Z statusCode: 200, i: 1, j: 8
2022-03-10T16:24:22.516Z statusCode: 200, i: 2, j: 9
2022-03-10T16:24:22.516Z statusCode: 200, i: 1, j: 9
2022-03-10T16:24:22.524Z statusCode: 200, i: 1, j: 10
2022-03-10T16:24:22.525Z statusCode: 200, i: 2, j: 10
2022-03-10T16:24:22.532Z statusCode: 200, i: 2, j: 11
2022-03-10T16:24:22.532Z statusCode: 200, i: 1, j: 11
2022-03-10T16:24:22.541Z statusCode: 200, i: 2, j: 12
2022-03-10T16:24:22.542Z statusCode: 200, i: 1, j: 12
2022-03-10T16:24:22.547Z statusCode: 200, i: 2, j: 13
2022-03-10T16:24:22.547Z statusCode: 200, i: 1, j: 13
2022-03-10T16:24:22.553Z statusCode: 200, i: 1, j: 14
2022-03-10T16:24:22.554Z statusCode: 200, i: 2, j: 14
2022-03-10T16:24:22.567Z statusCode: 200, i: 2, j: 15
2022-03-10T16:24:22.567Z statusCode: 200, i: 1, j: 15
2022-03-10T16:24:22.573Z statusCode: 200, i: 2, j: 16
2022-03-10T16:24:22.573Z statusCode: 200, i: 1, j: 16
2022-03-10T16:24:22.579Z statusCode: 200, i: 1, j: 17
2022-03-10T16:24:22.579Z statusCode: 200, i: 2, j: 17
2022-03-10T16:24:22.587Z statusCode: 200, i: 2, j: 18
2022-03-10T16:24:22.588Z statusCode: 200, i: 1, j: 18
2022-03-10T16:24:22.593Z statusCode: 200, i: 2, j: 19
2022-03-10T16:24:22.594Z statusCode: 200, i: 1, j: 19
```
So all requests are sent within 180 ms.

@AlexBrohshtut  can you please provide the daemon.log and if possible the log from the traffic-manager that covers a run of the first sample? You must use `telepresence loglevel debug` prior to the run.

**Comment by AlexBrohshtut** [comment] 2022-03-10 16:52
Here is the [daemon.log](https://github.com/telepresenceio/telepresence/files/8225400/daemon.log)
Unfortunately, I don't have traffic-manager logs. Where they are at the pod?

**Comment by thallgren** [comment] 2022-03-11 00:57
The logs of the traffic-manager can be obtained using `telepresence gather-logs` (it will actually collect all logs), or specificly using `kubectl -n ambassador logs traffic-manager-xxxx` (where xxxx is the generated part of the pod's name).

I'm looking at your `daemon.log` though, and from what I can see, the requests aren't serialized by Telepresence. They arrive that way, and with 9 seconds apart. Each request then takes about a second and a half to complete. This makes me suspect your DNS. It seems to take a while before the DNS request finds it way to the telepresence resolver.

Can you try running telepresence with a limited set of namespaces and see if that makes a difference?
```console
$ telepresence connect --mapped-namespaces=alexb-dev
```

**Comment by AlexBrohshtut** [comment] 2022-03-11 05:56
I ran:

```bash
telepresence2 connect --mapped-namespaces=alexb-dev
telepresence2 intercept alexb-dev-service-discovery -l --namespace alexb-dev
```

Then the results are as following:
```bash
2022-03-11T05:49:50.049Z statusCode: 200, i: 1, j: 0
2022-03-11T05:49:52.370Z statusCode: 200, i: 2, j: 0
2022-03-11T05:49:52.726Z statusCode: 200, i: 1, j: 1
2022-03-11T05:49:57.682Z statusCode: 200, i: 2, j: 1
2022-03-11T05:49:58.037Z statusCode: 200, i: 2, j: 2
2022-03-11T05:49:58.038Z statusCode: 200, i: 1, j: 2
2022-03-11T05:49:58.389Z statusCode: 200, i: 1, j: 3
2022-03-11T05:50:03.393Z statusCode: 200, i: 2, j: 3
2022-03-11T05:50:03.767Z statusCode: 200, i: 2, j: 4
2022-03-11T05:50:03.768Z statusCode: 200, i: 1, j: 4
2022-03-11T05:50:04.121Z statusCode: 200, i: 1, j: 5
2022-03-11T05:50:04.122Z statusCode: 200, i: 2, j: 5
2022-03-11T05:50:04.479Z statusCode: 200, i: 1, j: 6
2022-03-11T05:50:09.478Z statusCode: 200, i: 2, j: 6
2022-03-11T05:50:09.834Z statusCode: 200, i: 1, j: 7
2022-03-11T05:50:14.813Z statusCode: 200, i: 2, j: 7
2022-03-11T05:50:15.179Z statusCode: 200, i: 2, j: 8
2022-03-11T05:50:15.180Z statusCode: 200, i: 1, j: 8
2022-03-11T05:50:15.535Z statusCode: 200, i: 2, j: 9
2022-03-11T05:50:15.535Z statusCode: 200, i: 1, j: 9
2022-03-11T05:50:15.913Z statusCode: 200, i: 1, j: 10
```

Then I tried to run it on the IP instead of URL, using `await axios.get('http://172.20.84.176:9250/')` and it is actually worked good: 
```bash
2022-03-11T06:01:09.525Z statusCode: 200, i: 1, j: 0
2022-03-11T06:01:09.526Z statusCode: 200, i: 2, j: 0
2022-03-11T06:01:09.877Z statusCode: 200, i: 1, j: 1
2022-03-11T06:01:09.888Z statusCode: 200, i: 2, j: 1
2022-03-11T06:01:10.270Z statusCode: 200, i: 1, j: 2
2022-03-11T06:01:10.271Z statusCode: 200, i: 2, j: 2
2022-03-11T06:01:10.629Z statusCode: 200, i: 1, j: 3
2022-03-11T06:01:10.629Z statusCode: 200, i: 2, j: 3
2022-03-11T06:01:10.939Z statusCode: 200, i: 2, j: 4
2022-03-11T06:01:10.939Z statusCode: 200, i: 1, j: 4
```

Log files:
[connector.log](https://github.com/telepresenceio/telepresence/files/8229515/connector.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/8229520/daemon.log)
[traffic-manager-c6cf5bdff-2zbh6.ambassador.log](https://github.com/telepresenceio/telepresence/files/8229523/traffic-manager-c6cf5bdff-2zbh6.ambassador.log)
 


Thank you for trying to help 🙏🏻

**Comment by thallgren** [comment] 2022-03-11 08:55
The fact that everything works well when using the IP confirms my suspicion. I also don't see anything that would cause these problems in the traffic-manager log.

Do you have any other software installed on your workstation that adds a DNS resolver? If you do `ls /etc/resolver` at a time when Telepresence is not connected, what files do you see?

**Comment by AlexBrohshtut** [comment] 2022-03-11 16:02
```
 ls /etc/resolver                                                                                                                    ✔  17:59:59
telepresence.alexb-dev.local            telepresence.local                      telepresence.parallel.local             
telepresence.gregory-dev.local              telepresence.rocket.local               telepresence.yahel1.local
telepresence.hadas-tele-v2-2.local      telepresence.ohad23.local               telepresence.roman.local
telepresence.hstests.local              telepresence.ohad24.local               telepresence.tel2-search.local
telepresence.kube-system.local          telepresence.ohad26.local               telepresence.telepresence-v2-demo.local

cat /etc/resolver/telepresence.kube-system.local                                                                                    ✔  18:00:04
# Generated by telepresence
port 50291
domain kube-system
nameserver 127.0.0.1

cat /etc/resolver/telepresence.alexb-dev.local                                                                                      ✔  18:00:25
# Generated by telepresence
port 50291
domain alexb-dev
nameserver 127.0.0.1

cat /etc/resolver/telepresence.local                                                                                                ✔  18:00:32
# Generated by telepresence
port 50291
domain cluster.local
nameserver 127.0.0.1
search alexb-dev.svc.cluster.local cluster.local

 cat /etc/resolver/telepresence.parallel.local                                                                                       ✔  18:00:46
# Generated by telepresence
port 65077
domain parallel
nameserver 127.0.0.1
```

**Comment by thallgren** [comment] 2022-03-12 07:18
Are you seeing those files when telepresence is _not_ connected? If so, please remove all files with the `telepresence.` prefix (the cat output doesn't look right. All telepresence files should redirect to the same port).

**Comment by AlexBrohshtut** [comment] 2022-03-12 09:40
I've removed all files
Connected again, seen that there are file-per-namespace in `/etc/resolvers/telepresence.<NAMESPACE>.local`
Content was:
```
# Generated by telepresence
port 58928
domain <NAMESPACE>
nameserver 127.0.0.1
```

Ran script - result was the same, with 5sec delay
Disconnected from tele and all files were removed.

[traffic-manager-c6cf5bdff-2zbh6.ambassador.log](https://github.com/telepresenceio/telepresence/files/8237384/traffic-manager-c6cf5bdff-2zbh6.ambassador.log)
[daemon.log](https://github.com/telepresenceio/telepresence/files/8237385/daemon.log)
[connector.log](https://github.com/telepresenceio/telepresence/files/8237386/connector.log)

**Comment by AlexBrohshtut** [comment] 2022-03-13 09:16
We tried with and without VPN - the result is the same.

**Comment by AlexBrohshtut** [comment] 2022-03-13 09:16
We tried with and without VPN - the result is the same.

**Comment by AlexBrohshtut** [comment] 2022-03-13 13:24
We did a couple of more experiments:
* The issue happens only on something that is DNS resolved from the k8s cluster (this we already knew) - e.g. google.com is resolves instantly
* The issue doesn't reproduce on Ubuntu 20.04
* It does seem to be related to the DNS

Do you have any ideas about what this could be?

**Comment by AlexBrohshtut** [comment] 2022-03-17 06:24
@thallgren is there anything more we can check? The issue is still present. Do we have some way to make logs of Telepresence more verbose to understand where the delay is?

**Comment by thallgren** [comment] 2022-03-18 08:41
Can you verify that this happens on all macOS workstations, or is it just one?
Did you run `telepresence test-vpn`?

**Comment by AlexBrohshtut** [comment] 2022-03-18 09:12
This happens on all macOS workstations in the company.

`test-vpn` results:
```
---------- Test Results:
❌ pod subnet 10.200.32.0/19 is masking VPN-routed CIDR 0.0.0.0/1.This usually means Telepresence will be able to connect to your cluster, but hosts on your VPN may be inaccessible while telepresence is connected; to resolve:
	* Move pod subnet 10.200.32.0/19 to a subnet not mapped by the VPN
		* If this is not possible, ensure that any hosts in CIDR 0.0.0.0/1 are placed in the never-proxy list
❌ svc subnet 172.20.0.0/16 is masking VPN-routed CIDR 128.0.0.0/1.This usually means Telepresence will be able to connect to your cluster, but hosts on your VPN may be inaccessible while telepresence is connected; to resolve:
	* Move svc subnet 172.20.0.0/16 to a subnet not mapped by the VPN
		* If this is not possible, ensure that any hosts in CIDR 128.0.0.0/1 are placed in the never-proxy list
```

**Comment by cindymullins-dw** [comment] 2022-12-17 03:43
@AlexBrohshtut , have you perhaps tried removing the pod subnets or setting never-proxy to see if that improves connectivity?  We see your tests with and without VPN give same results but for our assessment, it would be helpful to know if updating these settings makes any difference.

**Comment by AlexBrohshtut** [comment] 2022-12-18 08:23
Unfortunately, this is not within my reach anymore.
Anyway, the workaround we implemented is to resolve the DNS one when the service is starting - on the config file level.

**Comment by thallgren** [comment] 2022-12-21 11:38
I'm closing this. We've made numerous improvements to the TUN device and tunneling since March and I think this has been addressed. Feel free to reopen if the problem reemerges.

**Closed as completed by thallgren** 2022-12-21 11:38 UTC

**Comment by maksnester** [comment] 2023-01-04 13:42
@thallgren The problem is still here. 

MacOS Monteray, M1 chip. 

```
Enhanced Client: v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
Traffic Manager: v2.9.3
```
