### ISSUE TITLE
is not a socket

### ISSUE THREAD

**Issue by zhangwanlong** [telepresenceio/telepresence#3191] opened 2023-05-19 08:53 UTC
PS C:\Users\030T0029> telepresence connect
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
telepresence connect: error: connector.Connect: "C:\\Users\\030T0029\\AppData\\Local\\telepresence\\rootd.socket" is not a socket

**Comment by cindymullins-dw** [comment] 2023-05-22 17:49
What version of Telepresence are you using?  Could you please try `‘telepresence quit -s’` and then try to connect again with ‘telepresence connect’ and let us know if you get the same error.

**Comment by zhangwanlong** [comment] 2023-05-23 01:02
抱歉还是无法访问





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telepresenceio/telepresence"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 凌晨1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [telepresenceio/telepresence] is not a socket (Issue #3191)





 
What version of Telepresence are you using?  Could you [lease try ‘telepresence quit -s’ and then try to connect again with ‘telepresence connect’ and let us know if you get the same error.

**Comment by lchkid** [comment] 2023-06-21 02:33
Same problem

win10 1809 (17763.316)

telepresence.exe version
Client     : v2.14.0
Root Daemon: not running
User Daemon: not running

telepresence connect
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
telepresence connect: error: connector.Connect: "C:\\Users\\Administrator\\AppData\\Local\\telepresence\\rootd.socket" is not a socket

**Comment by cindymullins-dw** [comment] 2023-06-23 23:16
If you could try removing the socket with `sudo rm /var/run/telepresence-daemon.socket`?

**Comment by lchkid** [comment] 2023-06-25 07:44
> If you could try removing the socket with `sudo rm /var/run/telepresence-daemon.socket`?

That was a windows device, so there was no such directory.

We finally switched to working on a mac device.

**Comment by cindymullins-dw** [comment] 2023-07-10 22:23
@zhangwanlong , could you share your Telepresence logs so we can see where this error is originating?

**Comment by thallgren** [comment] 2023-09-13 02:01
This is related to https://github.com/golang/go/issues/33357. The fix (from July last year) has not been merged yet. We should add a workaround.

**Comment by ChrisWalkerNGC** [comment] 2023-09-15 11:57
I'm seeing this issue too.  

Env: Windows 10 Enterprise.

**Comment by thallgren** [comment] 2023-09-20 11:14
@ChrisWalkerNGC I'm trying to reproduce this on a Windows 10 Enterprise without success. Perhaps Microsoft fixed this bug? What version are you on? I'm using version 22H2.

**Comment by thallgren** [comment] 2023-09-21 12:33
@zhangwanlong @lchkid @ChrisWalkerNGC, I'm inclined to close this ticket as a won't-fix, because I think the root cause is a bug in older versions of Windows 10 Enterprise. Can you please try and upgrade your Windows and check if the problem persists?

**Comment by mattiasclaesson** [comment] 2023-09-26 11:01
Same issue on...
Windows 10 Pro
Version: 1903
OS build 18362.900

using telepresence version
Client     : v2.15.1
Root Daemon: not running
User Daemon: not running

Tried to remove the file with 0 size, but no difference.

**Comment by thallgren** [comment] 2023-09-27 09:35
@mattiasclaesson can you please try and upgrade your Windows 10 Pro to a later version and see if the problem persists? I'm not able to reproduce with 22H2.

**Comment by mattiasclaesson** [comment] 2023-09-27 10:38
> @mattiasclaesson can you please try and upgrade your Windows 10 Pro to a later version and see if the problem persists? I'm not able to reproduce with 22H2.

I think this hardware will be replaced in a few months, will not upgrade as its running out of disk already.

**Comment by cindymullins-dw** [comment] 2023-11-11 05:40
Closing as it appears this issue has already been addressed by Microsoft, in which case additional workarounds on the Telepresence side would quickly become out of date.

**Closed as completed by cindymullins-dw** 2023-11-11 05:40 UTC

**Comment by jiangsanyin** [comment] 2024-12-26 07:44
> PS C:\Users\030T0029> telepresence connect Launching Telepresence User Daemon Launching Telepresence Root Daemon telepresence connect: error: connector.Connect: "C:\Users\030T0029\AppData\Local\telepresence\rootd.socket" is not a socket

same issue happend in windows server 2019. I change my workstation to windows11 and this problem is gone and works well.
![image](https://github.com/user-attachments/assets/02ccd678-9801-4436-bad4-8ef348f61053)
