### ISSUE TITLE
Add support for argo rollouts

### ISSUE THREAD

**Issue by mkantzer** [telepresenceio/telepresence#3640] opened 2024-07-02 17:04 UTC
**Please describe your use case / problem.**
I'm using Argo Rollouts to control my replicasets / pods.
They have a similar shape to a `Deployment`, but with some additional fields in their `spec` that make them function. Fundamentally though, they are still using a Pod Template Spec to spin up replicasets.

**Describe the solution you'd like**
Telepresence detects a Rollout in the same way it would a Deployment, and use it in the same way.

**Describe alternatives you've considered**
I've instead been targeting replicasets, but those do not have stable names, and it's causing issues for my developers who need to start keeping track of which ones are live.

**Versions (please complete the following information)**
OSS Client             : v2.18.0
OSS Daemon in container: v2.18.0
Traffic Manager        : v2.20.0-test.4
Traffic Agent          : docker.io/datawire/ambassador-telepresence-agent:1.14.5

**Additional context**
Add any other context about the feature request here.

**Comment by cindymullins-dw** [comment] 2024-07-08 23:48
@mkantzer, thanks for the suggestion.  I'll mark this as a feature request.  Currently, [supported workloads](https://www.getambassador.io/docs/telepresence/latest/reference/intercepts#supported-workloads) are deployments, replica sets and stateful sets.

**Comment by thallgren** [comment] 2024-07-09 15:35
I believe this is a duplicate of #2406.

**Comment by thallgren** [comment] 2024-08-16 11:41
Closed by #3651

**Closed as completed by thallgren** 2024-08-16 11:41 UTC
Labels: feature
