### ISSUE TITLE
 Invalid value: []string{"v1"}: must include at least one of v1beta1

### ISSUE THREAD

**Issue by Himer** [telepresenceio/telepresence#1809] opened 2021-06-22 09:25 UTC
./telepresence connect

Launching Telepresence Daemon v2.3.2 (api v3)
Connecting to traffic manager...
Disconnecting...failed
Telepresence Daemon quitting...done
telepresence: error: connector.Connect: failed to start traffic manager: failed to create MutatingWebhookConfiguration agent-injector-webhook-ambassador.: MutatingWebhookConfiguration.admissionregistration.k8s.io "agent-injector-webhook-ambassador" is invalid: webhooks[0].admissionReviewVersions: Invalid value: []string{"v1"}: must include at least one of v1beta1
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/telepresence-connector.socket: connect: connection refused"

**Comment by LukeShu** [comment] 2021-07-01 17:22
Which version of Kubernetes are you on?  Which version of `kubectl` do you have? (`kubectl version`)

**Comment by LukeShu** [comment] 2021-07-01 17:42
I'm closing this as a duplicate of https://github.com/telepresenceio/telepresence/issues/1795 .  If you're seeing it with Kubernetes 1.17 or newer, please re-open it.

**Comment by sachinkumarsingh092** [comment] 2021-09-20 05:37
@LukeShu can you please close this.

**Closed as completed** 2021-09-20 05:39 UTC
Labels: v2
