### ISSUE TITLE
telepresence connect: error: "C:\\Users\\030T0029\\AppData\\Local\\telepresence\\rootd.socket" is not a socket

### ISSUE THREAD

**Issue by zhangwanlong** [telepresenceio/telepresence#3189] opened 2023-05-19 07:12 UTC
本地是win10 系统，去用telepresence.exe connect 链接的时候，提示is not a socket

PS E:\goweb\kubesphere2\cmd\ks-apiserver> telepresence gather-logs
telepresence gather-logs: error: "C:\\Users\\030T0029\\AppData\\Local\\telepresence\\userd.socket" is not a socket

**Comment by cindymullins-dw** [comment] 2023-05-22 17:47
Have you tried running 'telepresence connect' without using the .exe suffix?

**Comment by thallgren** [comment] 2023-06-11 00:27
Duplicate of #3191

**Closed as completed by thallgren** 2023-06-11 00:27 UTC

**Comment by felixliulei** [comment] 2024-09-20 00:38
Requesting help with an error encountered while using telepresence connect: "Launching Telepresence User Daemon"

telepresence connect: error: connector service did not start: "C:\Users\cd\AppData\Local\telepresence\userd.socket" is not a socket

The telepresence version you are using is v2.19.6.

**Comment by thallgren** [comment] 2024-09-21 05:49
@felixliulei this is a bug in Windows and it was fixed a long time ago. You'll need to update your windows version.
