### ISSUE TITLE
[v2] traffic-manager auto upgrade/downgrade causes connection issues for teams  

### ISSUE THREAD

**Issue by peteroneilljr** [telepresenceio/telepresence#1689] opened 2021-04-26 17:42 UTC
Telepresence connections are interrupted when multiple team members run `telepresence connect` to the same cluster when using different versions of telepresence. The member with the newest version of telepresence will upgrade the traffic-manager to the latest version, but once the next member joins with a previous version of telepresence, the traffic-manager is forced to downgrade disrupting any existing connections.

**Comment by jackybh** [comment] 2021-04-26 18:04
Thank Peter for raising this.  We were experiencing disconnecting issue in the past 3 weeks (see https://github.com/telepresenceio/telepresence/issues/1652), and last week I found the root cause was related to this. Everytime when a client with different version tried to connect to the `traffic-manager`,  an update was triggered on `traffic-manager` and `ScalingReplicaSet` event was fired (See below)

```
 ----    ------             ----               ----                   -------
  Normal  ScalingReplicaSet  88s (x8 over 24h)  deployment-controller  Scaled up replica set traffic-manager-64858f494f to 1
  Normal  ScalingReplicaSet  86s (x7 over 20h)  deployment-controller  Scaled down replica set traffic-manager-c9dbd857 to 0
```

We also found there were `telepresence` clients: `Client` and `Daemon`, upgrading `telepresence` will not upgrade `Daemon` if it is running. You have to run `telepresence quit` to kill it first before upgrade.

**Comment by scottillogical** [comment] 2021-04-28 20:22
I think this is a duplicate of #1617

**Comment by cindymullins-dw** [comment] 2023-05-09 22:39
This was the case but shouldn’t be an issue anymore.  The traffic manager won’t be automatically upgraded by another user and now requires a deliberate upgrade.

**Closed by cindymullins-dw** 2023-05-09 22:39 UTC
Labels: v2
