### ISSUE TITLE
Failed to start with permission Error: [Errno 13] in WSL

### ISSUE THREAD

**Issue by melastmohican** [telepresenceio/telepresence#1176] opened 2019-10-31 15:48 UTC
systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

telepresence

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 39, in main
    runner = Runner(args.logfile, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 134, in __init__
    os.makedirs(tmp_dir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/c'

cat telepresence.log
   0.0 TEL | Telepresence 0.103 launched at Thu Oct 31 08:35:15 2019
   0.0 TEL |   /usr/bin/telepresence
   0.0 TEL | uname: uname_result(system='Linux', node='LOGIC-0571', release='4.4.0-17134-Microsoft', version='#706-Microsoft Mon Apr 01 18:13:00 PST 2019', machine='x86_64', processor='x86_64')
   0.0 TEL | Platform: linux
   0.0 TEL | WSL: True
   0.0 TEL | Python 3.6.7 (default, Oct 22 2018, 11:32:17)
   0.0 TEL | [GCC 8.2.0]

**Comment by akeyboardlife** [comment] 2019-11-01 04:30
I think we got the same problem.

Duplicate of #1175

**Comment by melastmohican** [comment] 2019-11-01 04:39
I do not understand why temp dir is set to /c/temp for WSL:

# Docker for Mac doesn't share TMPDIR, so make sure we use /tmp
# Docker for Windows can't access /tmp, so use a directory it can
        tmp_dir = "/tmp"
        if self.is_wsl:
            tmp_dir = "/c/temp"

/tmp is present in this version of Ubuntu on WSL. Maybe we need to check if /tmp exists before trying to create /c/temp which btw is /mnt/c/temp really.

**Comment by akeyboardlife** [comment] 2019-11-01 04:46
They had other problems.

#1148

**Comment by robross0606** [comment] 2020-05-21 19:45
Same problem here

**Closed** 2020-05-28 13:08 UTC
