### ISSUE TITLE
tel-agent-init failed

### ISSUE THREAD

**Issue by hanzhc** [telepresenceio/telepresence#3744] opened 2024-12-12 02:27 UTC
$ kubectl logs -f cnap-image-management-cnap-addon-8454fc48b-2j889 -c tel-agent-init -n cnap-addon-system
2024-12-12 02:22:41.1578 info    Traffic Agent Init v2.20.1
2024-12-12 02:22:41.4190 error   failed to insert --uid-owner rule in OUTPUT: running [/sbin/iptables -t nat -I OUTPUT 3 -m owner --uid-owner 0 -j RETURN --wait]: exit status 4: iptables v1.8.10 (nf_tables):  RULE_INSERT failed (No such file or directory): rule in chain OUTPUT

2024-12-12 02:22:41.4190 error   quit: failed to insert --uid-owner rule in OUTPUT: running [/sbin/iptables -t nat -I OUTPUT 3 -m owner --uid-owner 0 -j RETURN --wait]: exit status 4: iptables v1.8.10 (nf_tables):  RULE_INSERT failed (No such file or directory): rule in chain OUTPUT

telepresence version
OSS Client     : v2.20.1
OSS Root Daemon: v2.20.1
OSS User Daemon: v2.20.1
Traffic Manager: v2.20.1

**Comment by thallgren** [comment] 2024-12-12 10:03
Please check the output of `kubectl version`. This sounds like a duplicate of #3276.

**Closed as completed** 2024-12-14 17:04 UTC
