### ISSUE TITLE
Slow dns lookup in telepresence 2

### ISSUE THREAD

**Issue by Martin-4Spaces** [telepresenceio/telepresence#2607] opened 2022-05-23 12:12 UTC
I'm migrating from legacy telepresence to telepresence 2 and i'm encountering a significant performance decrease.
It seems to be related to dns lookups.

Here is an example showing nslookup of another service running in remote cluster.

Telepresence V1
```
root@portal-403a1c65ab1d4e58b0d5fce02423dec3-7b7c698d7b-msbk9:/tmp# time nslookup auth.martin.svc.cluster.local
Server:         10.16.0.10
Address:        10.16.0.10#53
Non-authoritative answer:
Name:   auth.martin.svc.cluster.local
Address: 10.16.0.90
real    0m0.416s
user    0m0.007s
sys     0m0.010s
```

Telepresence V2
```
root@e2e5dc0d4940:/var/www/html# time nslookup auth.martin.svc.cluster.local
Server:         192.168.65.5
Address:        192.168.65.5#53
Non-authoritative answer:
Name:   auth.martin.svc.cluster.local
Address: 10.16.0.90
real    0m15.069s
user    0m0.008s
sys     0m0.009s
```

0,4 sec vs 15 sec is significant. What can be the cause of this?

This is the command used to intercept
`telepresence intercept <remote deployment name> --namespace <namespace name> --port 80 --mechanism=tcp --docker-run -- --rm -v$(pwd):/var/www/html <local docker container name>`

**Comment by thallgren** [comment] 2022-05-23 12:14
Where is your cluster running? Is there any chance it may have access to your workstations network?

**Comment by Martin-4Spaces** [comment] 2022-05-23 12:15
Google Cloud Kubernetes (GKE).
No, only connection between remote cluster and workstation is telepresence.

**Comment by thallgren** [comment] 2022-05-24 05:20
Which version of Telepersence 2 are you running? Does the logs say anything? Try:
```console
$ telepresence loglevel debug
$ telepresence intercept ...
$ telepresence gather-logs
```

**Comment by Martin-4Spaces** [comment] 2022-05-24 05:49
```
 telepresence version
An update of telepresence from version 2.6.3 to 2.6.4 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client: v2.6.3 (api v3)
Root Daemon: v2.6.3 (api v3)
User Daemon: v2.6.3 (api v3)
```
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8759815/telepresence_logs.zip)

I started the session at 07:31:58 and performed three wgets to a remote service (auth.martin.svc.cluster.local -> 10.16.0.90).
At 07:32:48, 07:33:10, 07:33:26 (CEST).
The response was approx. 15 seconds every time.
I have studied the logs but without finding an answer to the latency.

**Comment by Martin-4Spaces** [comment] 2022-05-24 05:54
Updating to 2.6.4 did not solve it.

**Comment by thallgren** [comment] 2022-05-24 08:18
I see that the Telepresence DNS server receives the request, sends it to the cluster, and then returns the IP. It takes about 40ms. Then, for some reason, it takes an additional 15 seconds before the TUN device receives a connect request for the returned IP. This makes me suspect there's something going on outside of Telepresence that affects the resolution somehow. What platform are you running the client on?

**Comment by Martin-4Spaces** [comment] 2022-05-24 08:26
It sounds like progress. Thank you for your time so far!
The client runs on macOS 12.4. Its a mainstream development computer with Docker, IDE and browser and nothing else speciel installed. No VPN used during the test session. No custom DNS servers or proxies configured.
Telepresence is installed with brew.
I could try to install the same setup on another MacBook. It will take a couple of hours. Would it help?

**Comment by thallgren** [comment] 2022-05-24 08:35
When telepresence is disconnected, do you have any files under `/etc/resolver` ?

**Comment by Martin-4Spaces** [comment] 2022-05-24 08:36
```
➜  Desktop telepresence quit
Telepresence Network disconnecting...done
Telepresence Traffic Manager disconnecting...done
➜  Desktop ls -l /etc/resolver
total 0
```

**Comment by thallgren** [comment] 2022-05-24 08:48
Spinning up another machine might help track things down. I don't think we have a generic problem with slow DNS and GKE or anything like that, so it's not unlikely that another machine would work just fine.

**Comment by Martin-4Spaces** [comment] 2022-05-24 08:50
I'll set it in motion and get back to you.

**Comment by Martin-4Spaces** [comment] 2022-05-24 10:04
The results..
I performed the same test (wget auth.martin.svc.cluster.local -> 10.16.0.90).
At 09.45.04, 09.45.12, 09.45.18, 09.45.24.
[telepresence_logs 2.zip](https://github.com/telepresenceio/telepresence/files/8761576/telepresence_logs.2.zip)
The response time is 5-6 seconds. 
The two test devices used
- MacBook Pro 2,3 GHz Quad-Core Intel Core i7, 32 GB 3733 (Result: 15 sec)
- MacBook 1,3 GHz Dual-Core Intel Core i5, 8 GB 1867 MHz LPDDR3 (Result: 5 sec)

5 seconds does also sound as a long time. But this is an old and slow computer. I would never use it for development purposes. So I'm not sure if the 5 seconds is to be expected. 
Anyway, this proves your point. This is not a generic problem between GKE and macOS.

I will try to eliminate the differences of these two computers and hopefully discover what makes the issue.

**Comment by thallgren** [comment] 2022-05-24 10:27
I agree that five seconds is a very long time, and the symptoms are very similar. The DNS lookup is really fast (50ms here) and the there's a 5 second wait until the connect arrives. Telepresence seems to do absolutely nothing between those events.

**Comment by thallgren** [comment] 2022-05-24 10:36
4 pods are deleted from the cluster during the wait between DNS resolution and actual connect (statistics, portal, product, and menu), not sure if that's significant.

**Comment by Martin-4Spaces** [comment] 2022-05-24 10:39
The mentioned services are running kubernetes jobs every minute. It could just be the scheduled pods spinning up and down. 
Do you see the same behaviour in all four tests?

I'm working on testing against another cluster (not GKE).

**Comment by thallgren** [comment] 2022-05-24 10:45
I see a similar behavior in the traffic-manager logs. It receives a `LookupHost` which it responds to fairly quicky. It's always followed by a sequence of CREATE/DELETE events from the mutating webhook (noops since intercepts aren't active). But it could definitely be a coincidence.

**Comment by Martin-4Spaces** [comment] 2022-05-24 11:15
@thallgren 
Here I did a test from the original computer and a cluster located at Elastx.
[elastx test.zip](https://github.com/telepresenceio/telepresence/files/8762100/elastx.test.zip)
11:11:18, 11:11:20, 11:11:21.
No delay at all!

**Comment by Martin-4Spaces** [comment] 2022-05-24 11:23
I might have something here.
I cannot use ".svc.cluster.local" in the Elastx cluster. I dont know why. But I can reach deployments without.
So I tried to do the same with the GKE cluster.
![TradingPlatform-Portal_–_package_json](https://user-images.githubusercontent.com/9819124/170023471-29d31cb0-2965-4a60-b711-3c6af41bccc8.png)
[gke.zip](https://github.com/telepresenceio/telepresence/files/8762163/gke.zip)

Does this make any sense?

**Comment by thallgren** [comment] 2022-05-24 11:41
That's interesting. I'm sure it makes sense, just can't figure it out :-)

Not all clusters use `.cluster.local` as their suffix. From the looks of it, your Elastx cluster uses `klartboard-cluster1.local`, so you should be able to use `.svc.klartboard-cluster1.local` instead. Would be interesting to see if you see the same difference there.

In case you're wondering, the actual cluster domain is listed in the `connect.log` right after Telepresence connects.

**Comment by Martin-4Spaces** [comment] 2022-05-24 11:54
Thank you for explaining. 
Actually I cant get `.svc.klartboard-cluster1.local` to work.

```
/tmp # wget deploy-backend.deploy.svc.klartboard-cluster1.local
--2022-05-24 11:49:49--  http://deploy-backend.deploy.svc.klartboard-cluster1.local/
Resolving deploy-backend.deploy.svc.klartboard-cluster1.local (deploy-backend.deploy.svc.klartboard-cluster1.local)... failed: Try again.
wget: unable to resolve host address 'deploy-backend.deploy.svc.klartboard-cluster1.local'

/tmp # wget deploy-backend.deploy
--2022-05-24 11:50:42--  http://deploy-backend.deploy/
Resolving deploy-backend.deploy (deploy-backend.deploy)... 10.233.56.7
Connecting to deploy-backend.deploy (deploy-backend.deploy)|10.233.56.7|:80... connected.
HTTP request sent, awaiting response... 200 OK
```

But it doesn't matter - I think. :) 

I can tweak my application to escape the cluster suffix. 
But it would be nice to find the actual cause of this. Is there anything else I can do in my end to provide more info?

**Comment by thallgren** [comment] 2022-05-24 12:41
I'm surprised that doesn't work. That's a bug in itself.
I'm running some more tests on my Powerbook and see if I can reproduce anything similar to what you're experiencing. Thanks for being so helpful with info and logs. Much appreciated.

**Comment by Martin-4Spaces** [comment] 2022-05-24 12:52
Agreed. I tried from inside the cluster with the exact same host (suffix klartboard-cluster1.local) and it works fine.
Created a separate issue for this https://github.com/telepresenceio/telepresence/issues/2611.

**Comment by jhancock4d** [comment] 2022-12-05 19:23
I'm also getting this in windows. Is there a way to manually set what dns servers it forwards to?  Basically all external requests while telepresence is running are timing out and then resolve to standard DNS.

**Comment by thallgren** [comment] 2024-02-04 15:19
Closing this, as I think all issues mentioned here has since been resolved.

**Closed as completed by thallgren** 2024-02-04 15:19 UTC
