### ISSUE TITLE
Telepresence logging unnecessarily reveals information about the cluster contents

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#523] opened 2018-03-22 16:30 UTC
... and it does so unconditionally. It would be useful to be able to suppress information about unrelated cluster objects. This would allow more users to submit log files to us to help with debugging.

**Comment by exarkun** [comment] 2018-03-23 12:12
Did you notice something in particular or is this an umbrella issue for changing Telepresence logs to exclude _all_ information not directly related to some decision Telepresence is making?

**Comment by ark3** [comment] 2018-03-23 17:00
The list of pods is what stuck out to me because it seems like it's all over the file. Other cluster info is limited to the top of the file, where it can easily be edited or deleted. I think we can drop the pod info unless `--verbose` is on, or something like that. I should probably narrow the issue.

**Comment by donnyyung** [comment] 2021-07-23 14:16
When users report logs with Telepresence 2, they still obscure some information, so this still seems to be an issue.

**Comment by thallgren** [comment] 2021-09-04 06:01
Closing as duplicate of #2007

**Closed by thallgren** 2021-09-04 06:01 UTC
Labels: exploration, v2
