### ISSUE TITLE
agent-injector-webhook-ambassador not starting on kube 1.16

### ISSUE THREAD

**Issue by sokoow** [telepresenceio/telepresence#2019] opened 2021-08-26 12:07 UTC
I get this when trying to launch on kube 1.16: 

```
$ telepresence connect
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
wTelepresence Root Daemon quitting... done
telepresence: error: connector.Connect: failed to start traffic manager: failed to create MutatingWebhookConfiguration agent-injector-webhook-ambassador.: MutatingWebhookConfiguration.admissionregistration.k8s.io "agent-injector-webhook-ambassador" is invalid: webhooks[0].admissionReviewVersions: Invalid value: []string{"v1"}: must include at least one of v1beta1

See logs for details (4 errors found): "/home/mint/.cache/telepresence/logs/connector.log"
```

**Comment by thallgren** [comment] 2021-08-26 21:59
Closing as duplicate of #1795

**Closed as completed by thallgren** 2021-08-26 21:59 UTC

**Comment by zhaobei** [comment] 2022-01-05 02:53
mee too 
![image](https://user-images.githubusercontent.com/55879962/148153361-59f2ee54-0b14-4031-a182-6461c54f8238.png)
