### ISSUE TITLE
Cannot connect Telepresence to a specific namespace

### ISSUE THREAD

**Issue by aommm** [telepresenceio/telepresence#2191] opened 2021-11-02 07:35 UTC
**Describe the bug**
Hi!

I used to be able to `curl http://my-service` in Telepresence 1:
```
> telepresence --namespace=my-k8s-namespace
> curl http://my-service
```

But with Telepresence 2, it seems like the `--namespace` option is no longer available. 
Do we always have to specify the namespace name when connecting to services now?
```
> telepresence connect
> curl http://my-service.my-k8s-namespace
```

This is something between a question and a feature request. Apologies if I didn't use the correct channel!

**Comment by thallgren** [comment] 2021-11-02 10:32
Namespace is available in Telepresence 2, but not as an argument to connect. The connect puts your workstation "in the cluster" in a namespace agnostic manner. When you create an intercept (in some namespace), then the network mappings change so that your workstation is "in the cluster and in the intercepted namespace".

If you want your workstation to be in a namespace but you don't want to intercept a service in the cluster, then you can create a `--local-only` intercept for that namespace.

I'm closing this as the what you describe is the intended behavior. Please see our docs on [DNS resolution](https://www.telepresence.io/docs/latest/reference/dns/) for more info.

**Closed as completed by thallgren** 2021-11-02 10:32 UTC
