### ISSUE TITLE
No mounts on telepresence local container

### ISSUE THREAD

**Issue by sebasb21** [telepresenceio/telepresence#2554] opened 2022-04-28 11:47 UTC
Hi, we have been trying to migrate from Telepresence Legacy to v2 since we got new M1 Macs.

We usually intercepted (swapped deployments) with a local container and everything was good. But with v2 everything seems to work except the mounts, so we do not have secrets etc etc...

I see an error log in `Logs/telepresence/connector.log`

```
info    connector/session/intercept-port-forward/10.8.6.12:43017 : Mounting file system for intercept "score-matching" at "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-142387180"
info    connector/session/intercept-port-forward/10.8.6.12:43017 : started command /opt/homebrew/bin/sshfs sshfs -F none -f -C -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o slave -o follow_symlinks -o allow_root localhost:/tel_app_mounts /var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-142387180 : exec.pid="6590"
error   connector/session/intercept-port-forward/10.8.6.12:43017 : mount_macfuse: failed to mount /private/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-142387180@/dev/macfuse0: Operation not permitted
error   connector/session/intercept-port-forward/10.8.6.12:43017 : fuse: mount failed with errro: 1
```

The message seems pretty clear but i have failed to walk around it, that dev seems to be accesible but maybe im looking in the wrong place.....

**Comment by sebasb21** [comment] 2022-04-28 14:38
Upgraded to a beta of macFUSE 4.3.0 now the intercept fails to load, no error logs but some other logs: 

```
2022-04-28 15:33:32.5982 info    connector/session/intercept-port-forward/10.8.6.12:43017 : Mounting file system for intercept "score-matching" at "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1160693569"
2022-04-28 15:33:32.7085 info    connector/session/intercept-port-forward : Terminating forwards for 10.8.6.12
2022-04-28 15:33:32.7114 info    connector/session/intercept-port-forward : started command ["umount" "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1160693569"] : dexec.pid="1973"
2022-04-28 15:33:32.7115 info    connector/session/intercept-port-forward :  : dexec.pid="1973" dexec.stream="stdout+stderr" dexec.data="umount: /var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1160693569: not currently mounted\n"
2022-04-28 15:33:32.7115 info    connector/session/intercept-port-forward :  : dexec.pid="1973" dexec.stream="stdin" dexec.err="EOF"
2022-04-28 15:33:32.7116 info    connector/session/intercept-port-forward : finished with error: exit status 1 : dexec.pid="1973"
2022-04-28 15:33:32.7117 info    connector/session/intercept-port-forward : Removed file system mount "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1160693569"
2022-04-28 15:33:33.1381 info    connector/session:shutdown_logger : shutting down (gracefully)...
```

**Comment by thallgren** [comment] 2022-05-02 03:53
The "umount" is there as a precaution, in case the sshfs doesn't umount correctly. The fact that it fails is usually OK. The fact that forwards are terminating just 0.1 second after the mount is not normal though. Can you see any other log output that can explain why that happens?

**Comment by sebasb21** [comment] 2022-05-03 08:14
Sorry my second comment was not a very good one, more accuretaly there is NO ADDITIONAL logs, the problem still manifest as the first comment: So with the new version of macfuse the logs go like this: 

```2022-04-28 15:49:57.9557 info    connector/session/intercept-port-forward/10.8.6.12:43017 : Mounting file system for intercept "score-matching" at "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1852296684"
2022-04-28 15:49:57.9582 info    connector/session/intercept-port-forward/10.8.6.12:43017 : started command /opt/homebrew/bin/sshfs sshfs -F none -f -C -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o slave -o follow_symlinks -o allow_root localhost:/tel_app_mounts /var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1852296684 : exec.pid="3454"
2022-04-28 15:49:57.9705 error   connector/session/intercept-port-forward/10.8.6.12:43017 : mount_macfuse: failed to mount /private/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1852296684@/dev/macfuse0: Operation not permitted
2022-04-28 15:49:57.9706 error   connector/session/intercept-port-forward/10.8.6.12:43017 : fuse: mount failed with errro: 1
2022-04-28 15:49:58.2255 info    connector/session/intercept-port-forward : Terminating forwards for 10.8.6.12
2022-04-28 15:49:58.2256 info    connector/session/intercept-port-forward/10.8.6.12:43017 : ended command sshfs : exec.pid="3454"
2022-04-28 15:49:58.4898 info    connector/session:shutdown_logger : shutting down (gracefully)...
2022-04-28 15:49:59.2352 info    connector/session/intercept-port-forward : started command ["umount" "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1852296684"] : dexec.pid="3467"
2022-04-28 15:49:59.2356 info    connector/session/intercept-port-forward :  : dexec.pid="3467" dexec.stream="stdin" dexec.err="EOF"
2022-04-28 15:49:59.2358 info    connector/session/intercept-port-forward : finished with error: signal: interrupt : dexec.pid="3467"
2022-04-28 15:49:59.2362 info    connector/session/intercept-port-forward : Removed file system mount "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1852296684"
```


And the intercept ends, with the previous version the intercept would run, local container would run but mounts wont be there. Here it doesn't even starts.

So my guess is that the error logs is accurate to some point as to why mounts fail, but i have no idea how to fix it.

**Comment by thallgren** [comment] 2022-05-03 10:17
Did you try the workaround that we recommend in our troubleshooting guide?
https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#volume-mounts-are-not-working-on-macos

**Comment by sebasb21** [comment] 2022-05-03 12:08
Same result, except now with the "old" macfuse the intercept starts, but the dir is empty

```
2022-05-03 13:04:41.7926 info    connector/session/intercept-port-forward/10.8.11.60:44879 : Mounting file system for intercept "score-matching" at "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465"
2022-05-03 13:04:41.8022 info    connector/session/intercept-port-forward/10.8.11.60:44879 : started command /opt/homebrew/bin/sshfs sshfs -F none -f -C -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o slave -o follow_symlinks -o allow_root localhost:/tel_app_mounts /var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465 : exec.pid="2737"
2022-05-03 13:04:41.8214 error   connector/session/intercept-port-forward/10.8.11.60:44879 : mount_macfuse: failed to mount /private/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465@/dev/macfuse0: Operation not permitted
2022-05-03 13:04:41.8215 error   connector/session/intercept-port-forward/10.8.11.60:44879 : fuse: mount failed with errro: 1
2022-05-03 13:05:07.2614 info    connector/session/intercept-port-forward : Terminating forwards for 10.8.11.60
2022-05-03 13:05:07.2618 info    connector/session/intercept-port-forward/10.8.11.60:44879 : ended command sshfs : exec.pid="2737"
2022-05-03 13:05:07.3115 info    connector/session:shutdown_logger : shutting down (gracefully)...
2022-05-03 13:05:08.2737 info    connector/session/intercept-port-forward : started command ["umount" "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465"] : dexec.pid="2793"
2022-05-03 13:05:08.2741 info    connector/session/intercept-port-forward :  : dexec.pid="2793" dexec.stream="stdin" dexec.err="EOF"
2022-05-03 13:05:08.2742 info    connector/session/intercept-port-forward :  : dexec.pid="2793" dexec.stream="stdout+stderr" dexec.data="umount: /var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465: not currently mounted\n"
2022-05-03 13:05:08.2743 info    connector/session/intercept-port-forward : finished with error: exit status 1 : dexec.pid="2793"
2022-05-03 13:05:08.2746 info    connector/session/intercept-port-forward : Removed file system mount "/var/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-3599564465"
```

The intercept ends in the logs because i quit the shell in the container.....

**Comment by thallgren** [comment] 2022-05-03 14:24
Are you using `sudo` or doing anything else that would affect the UID of the telepresence connector daemon?

**Comment by sebasb21** [comment] 2022-05-03 21:03
No we don't, but when running the command we get asked for root privileges: 

```
Need root privileges to run: /opt/homebrew/bin/telepresence daemon-foreground.........
```

I don't think we do anything deliberate, but maybe there is some environment setup on our laptop that has

**Comment by thallgren** [comment] 2022-05-03 21:07
Yes, that's normal. The root daemon is responsible network tunneling and DNS. It's not the one that mounts the filesystem. Can you see anything out of the ordinary in the logs of the traffic-agent container in the intercepted pod?

Tip, try `telepresence loglevel debug` before you do the intercept. That'll give you more verbose logging everywhere.

**Comment by sebasb21** [comment] 2022-05-03 21:23
i don't see anything significant: 

```
2022-05-03 22:13:24.4640 info    connector/session/intercept-port-forward/10.8.11.60:44879 : Mounting file system for intercept "score-matching" at "/va
r/folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1154265766"
2022-05-03 22:13:24.4643 debug   connector/session/intercept-port-forward : search paths posted successfully
2022-05-03 22:13:24.4656 debug   connector/server-grpc/conn=6 : client Send loop started
2022-05-03 22:13:24.4656 debug   connector/server-grpc/conn=6 : manager Recv loop started
2022-05-03 22:13:24.4656 debug   connector/server-grpc/conn=6 : client Recv loop started
2022-05-03 22:13:24.4656 debug   connector/server-grpc/conn=6 : manager Send loop started
2022-05-03 22:13:24.4679 info    connector/session/intercept-port-forward/10.8.11.60:44879 : started command /opt/homebrew/bin/sshfs sshfs -F none -f -C
 -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o slave -o follow_symlinks -o allow_root localhost:/tel_app_mounts /var/
folders/b8/vy2v0mxs1mn_m43xznth0dj00000gp/T/telfs-1154265766 : exec.pid="24133"
2022-05-03 22:13:24.4836 error   connector/session/intercept-port-forward/10.8.11.60:44879 : mount_macfuse: failed to mount /private/var/folders/b8/vy2v
0mxs1mn_m43xznth0dj00000gp/T/telfs-1154265766@/dev/macfuse0: Operation not permitted
2022-05-03 22:13:24.4837 error   connector/session/intercept-port-forward/10.8.11.60:44879 : fuse: mount failed with errro: 1
2022-05-03 22:15:13.7482 debug   connector/server-grpc/conn=8/RemoveIntercept-18 : called
2022-05-03 22:15:13.7485 debug   connector/session/RemoveIntercept-0 : telling manager to remove intercept score-matching
2022-05-03 22:15:13.7881 debug   connector/server-grpc/conn=8/RemoveIntercept-18 : returned
2022-05-03 22:15:13.7883 info    connector/session/intercept-port-forward : Terminating forwards for 10.8.11.60
2022-05-03 22:15:13.7883 info    connector/session/intercept-port-forward/10.8.11.60:44879 : ended command sshfs : exec.pid="24133"
2022-05-03 22:15:13.7896 debug   connector/server-grpc/conn=8/UserNotifications-15 : returned
```

**Comment by sebasb21** [comment] 2022-05-03 21:43
this logs from the traffic-agent

```
2022-05-03 21:42:08.0551 debug   client : HandleIntercepts called
2022-05-03 21:42:08.0552 info    client : Setting intercept "d547af30-cd10-4e44-a7bf-d181ef3fb886:score-matching" as ACTIVE
2022-05-03 21:42:08.0569 debug   client : HandleIntercepts called
2022-05-03 21:42:08.0569 debug   forward : Forward target changed from :80 to intercept 'score-matching' (sebastian.boccardi@MBP-0337.local:8080) : lis=":9900"
2022-05-03 21:42:08.1320 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879, dialing
2022-05-03 21:42:08.1322 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879, dial answered
2022-05-03 21:42:08.1322 debug   client :    CLI tcp 10.8.0.0:57129 -> 10.8.11.60:44879, ReadLoop starting
2022-05-03 21:42:08.1322 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879 stream-to-conn loop started
2022-05-03 21:42:08.1322 debug   sftp-server : Serving sftp connection from 10.8.11.60:47464
2022-05-03 21:42:08.1323 debug   client :    CLI tcp 10.8.0.0:57129 -> 10.8.11.60:44879, WriteLoop starting
2022-05-03 21:42:08.1330 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879 conn-to-stream loop started
2022-05-03 21:42:43.5419 debug   client : HandleIntercepts called
2022-05-03 21:42:43.5420 info    client : The previously-active intercept has been deleted
2022-05-03 21:42:43.5420 debug   forward : Forward target changed from intercept 'score-matching' (sebastian.boccardi@MBP-0337.local:8080) to :80 : lis=":9900"
2022-05-03 21:42:44.5735 debug   client :    CLI tcp 10.8.0.0:57129 -> 10.8.11.60:44879, ReadLoop ended
2022-05-03 21:42:44.5736 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879 disconnecting
2022-05-03 21:42:44.5736 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879 conn-to-stream loop ended because the connection was closed
2022-05-03 21:42:44.5736 debug   client :    CLI tcp 10.8.0.0:57129 -> 10.8.11.60:44879, WriteLoop ended
2022-05-03 21:42:44.5737 debug   client :    CONN tcp 10.8.0.0:57129 -> 10.8.11.60:44879 stream-to-conn loop ended because there was no more input
2022-05-03 21:42:44.5738 error   sftp-server : sftp server completed because client exited
```

**Comment by thallgren** [comment] 2022-05-04 08:48
There's nothing out of the ordinary in the logs. I have tried to reproduce the problem with different macOS versions (now on Monterey 12.3.1) and versions of macFUSE ranging from 4.2.5 to 4.3.1. Plenty of reboots and permission granting involved in those installs, but in the end the mounts always works for me.

I guess you've tried using an explicit mount point? I.e. `telepresence intercept --mount /some/folder ...`? Perhaps you don't have sufficient permissions on the tempdir that is generated?

**Comment by sebasb21** [comment] 2022-05-04 10:20
we dont use the --mount flag, the tempdir gets created, so i guess it would have complete access to it if it is creating it with no issue..... might the "device" be the issue?

**Comment by sebasb21** [comment] 2022-05-04 10:46
So we are running in Monterey 12.3.1 Apple M1 pro if anyone is interested,

**Comment by sebasb21** [comment] 2022-05-05 13:28
@thallgren did you tested this in an M1 Mac? just to confirm, so we can shift into trying to understand what is it that we do on our setups to generate this......

**Comment by chaunceyjiang** [comment] 2022-05-12 06:17
I have the same problem.

**Comment by chaunceyjiang** [comment] 2022-05-12 06:19
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/17962021/168004445-91778d8b-ac99-49fe-98fc-4570e53c6177.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/17962021/168004590-a10cc502-5bd5-4a3a-9760-66b32c416e74.png">

**Comment by chaunceyjiang** [comment] 2022-05-12 06:23
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
os version 12.3.1

**Comment by sebasb21** [comment] 2022-05-12 09:33
@chaunceyjiang do you have any logs for that? any error in the logs?

**Comment by TomAdmz** [comment] 2022-05-12 21:33
Getting a similar issue on MacOS Monterey 12.3.1 . The intercept starts but the only dir that gets mounted is $TELEPRESENCE_ROOT/var/scratch, we have multiple other mounts in the pod which do not appear.

running command:
`telepresence intercept {service_name} --mount=/tmp/{service_name}/known --namespace={namespace} --context={context} --port {port} --service {service_name} -- bash`

don't see any errors in the logs about mounting issues, also tried re-running https://www.getambassador.io/docs/telepresence/latest/troubleshooting/#volume-mounts-are-not-working-on-macos



edit: I no longer have this issue with new telepresence version 2.6.0

**Comment by chaunceyjiang** [comment] 2022-05-13 01:32
> @chaunceyjiang do you have any logs for that? any error in the logs?

i don't see any errors .

**Comment by afhole** [comment] 2023-02-01 16:18
I have encountered the exact error as described by @sebasb21 in this issue.
Noting that the error includes `Operation not permitted`, on a whim I decided to promote my macOS user to an Admin, and this has solved the issue. Is this expected behaviour? As a standard user I was able to mount a directory successfully with sshfs with basic options e.g. `sshfs user@host:/Users/user /Users/user/mount` but the command used by telepresence appears to require an admin user: `sshfs -F none -f -C -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -o slave -o follow_symlinks -o allow_root localhost:/tel_app_exports/my-service /Users/user/mount`

**Comment by afhole** [comment] 2023-02-01 16:32
@chaunceyjiang I am intrigued to know if your macOS user is a standard account or an admin?

**Comment by afhole** [comment] 2023-02-02 13:15
I think I have found the solution to run as non-admin. I believe `allow_root` requires the user to be in the macfuse admin_group, which by default is the admin group (gid 80). Changing this to the staff group (gid 20) appears to solve the issue:
```
$ sudo sysctl vfs.generic.macfuse.tunables.admin_group=20
vfs.generic.macfuse.tunables.admin_group: 80 -> 20
```

See also: https://code.google.com/archive/p/macfuse/wikis/OPTIONS.wiki

**Comment by cindymullins-dw** [comment] 2024-02-06 22:35
Closing as there appears to be a workaround available.

**Closed as completed by cindymullins-dw** 2024-02-06 22:35 UTC
