### ISSUE TITLE
insecure installation instructions

### ISSUE THREAD

**Issue by jdstrand** [telepresenceio/telepresence#1829] opened 2021-06-29 18:11 UTC
Looking at https://www.telepresence.io/docs/latest/install/, the installation instructions say to run curl under sudo to download the binary into a system directory, then chmod it. This is insecure since it allows for supply chain attacks. At a minimum, the site should publish checksums (ie, sha256 or sha512) for current and past binary versions with instructions on how to verify the download.

To keep installation instructions simple, you might want to consider writing a script that performs the download, verifies the checksum, does the chmod and copies the verified binary into place. In this manner users can curl your installer, verify the installer's checksum then run it.

**Comment by LukeShu** [comment] 2021-07-01 17:06
Hi!  Checksums aren't terribly effective at guarding against supply chain attacks; if the attacker is able to modify the binary, they are very likely to also be able to modify the checksum file; they are in fact stored in the same place after all.  Checksums are good for glitches, not attacks.  To properly guard against a supply chain attack, we'd need to use signatures.

And to be clear, this is only "insecure" if our infrastructure is compromised.  Which is something we should guard against, defense in layers and all that, but working from the baseline assumption that they're not: This isn't an urgent concern.

But publishing signatures would be a good thing to do.

PS: The `GOOS=linux` builds are reproducible, if you would like to verify them that way.  The `GOOS=darwin` builds might be too, since some of the changes in 2.3.0, but I haven't actually checked.

**Comment by cindymullins-dw** [comment] 2023-04-29 02:02
Resolved in newer versions.

**Closed as completed by cindymullins-dw** 2023-04-29 02:02 UTC
Labels: v2
