### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by x1mroepke** [telepresenceio/telepresence#806] opened 2018-10-14 14:58 UTC
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
    "deployment",
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

And here are the last few lines of the logfile (see /home/michael/dersalvador/BrokerMeApp/telepresence.log for the complete logs):

   2.4   9 |                 ],
   2.4   9 |                 "restartPolicy": "Always",
   2.4   9 |                 "schedulerName": "default-scheduler",
   2.4   9 |                 "securityContext": {},
   2.4   9 |                 "terminationGracePeriodSeconds": 30,
   2.4   9 |                 "volumes": [
   2.4   9 |                     {
   2.4   9 |                         "name": "cvs-env-svc-acc-vol",
   2.4   9 |                         "secret": {
   2.4   9 |                             "defaultMode": 256,
   2.4   9 |                             "secretName": "staging-cvs"
   2.4   9 |                         }
   2.4   9 |                     }
   2.4   9 |                 ]
   2.4   9 |             }
   2.4   9 |         }
   2.4   9 |     },
   2.4   9 |     "status": {}
   2.4   9 | }
   2.4 TEL | END SPAN remote.py:73(get_deployment_json)    0.4s

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]:

**Comment by ark3** [comment] 2018-10-14 18:13
Sorry about the crash! What was your command line? What version of Telepresence? Thanks for your help.

**Comment by ark3** [comment] 2018-10-14 18:14
Oh, this is a dupe of #807. I'll close this one.

**Closed by ark3** 2018-10-14 18:14 UTC
