### ISSUE TITLE
Telepresence fails to install on macOS (amd64/arm64) and Linux (x86_64) via brew

### ISSUE THREAD

**Issue by mprimeaux** [telepresenceio/telepresence#2878] opened 2022-11-10 17:48 UTC
**Describe the bug**

I'm following [these](https://www.getambassador.io/docs/telepresence/latest/install/?os=macos#install) instructions for installing Telepresence on macOS ARM64 (Mac Studio M1 Ultra). However, I receive the following installation failure.

```shell
❯ brew install datawire/blackbird/telepresence-arm64                                                                                                       ─╯
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).

==> Downloading https://app.getambassador.io/download/tel2/darwin/arm64/2.9.0-rc.2/telepresence
Already downloaded: /Users/mprimeaux/Library/Caches/Homebrew/downloads/a34bba333dce2136ea69aaa96050f4b55578f23d559cefd6ae0a8ec524bf0b4c--2.9.0-rc.2
Error: telepresence-arm64: SHA256 mismatch
Expected: 6ccf44344576b11097bbbf8e1177035fd6efc18a403b7701218636aeed55b503
  Actual: bc80e2a70f93724a9dbfd5f34955bc1645113d7e73c8dc0149b00b09a54ca2f0
    File: /Users/mprimeaux/Library/Caches/Homebrew/downloads/a34bba333dce2136ea69aaa96050f4b55578f23d559cefd6ae0a8ec524bf0b4c--2.9.0-rc.2
To retry an incomplete download, remove the file above.
```

This fails even after performing a `brew cleanup` to remove the failed download on macOS Apple Silicon.

I then attempted to install Telepresence on my Linux (X86_64) machine and it failed with the following:

```shell
❯ brew install datawire/blackbird/telepresence
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 3 taps (datawire/blackbird, homebrew/core and homebrew/cask-versions).
==> New Formulae
tart                                                 vhs                                                  xcodes

You have 2 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

telepresence 2.8.5 is already installed but outdated (so it will be upgraded).
==> Downloading https://app.getambassador.io/download/tel2/darwin/amd64/2.9.0-rc.2/telepresence
######################################################################## 100.0%
Error: telepresence: SHA256 mismatch
Expected: 40cc51668adf2212be44c04504060198163a6bd82f73510dc1a660455a095919
  Actual: 4600d52cd1d8be73c18515f32af1eaa2ba83e08b3166cbd30d5a257fa3560bbd
    File: /home/mprimeaux/.cache/Homebrew/downloads/6a2620e371cff6a1d2442e64d6a3aa172579057556db1e6e3f04c020ca8e0916--2.9.0-rc.2
To retry an incomplete download, remove the file above.
```

Attempting after `brew cleanup` on Linux also fails with the same exception (SHA mismatch).

**To Reproduce**
1.  On macOS (Intel or ARM), run `brew cleanup`
2. Follow [these](https://www.getambassador.io/docs/telepresence/latest/install/?os=macos#install) instructions.

**Expected behavior**

Expect Telepresence to be successfully installed on macOS Intel and Silicon (ARM) and Linux (X86_64).

**Versions (please complete the following information):**
 - Output of `telepresence version`
 - Operating system of workstation running `telepresence` commands
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
 - Which VPN client are you using? NO
 - Which VPN server are you using? N/A
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf

**Additional context**

The above steps worked as described before this latest release.

**Comment by thallgren** [comment] 2022-11-11 21:45
We had a temporary glitch caused by some invalid code in our github actions. It's fixed now.

**Closed as completed by thallgren** 2022-11-11 21:45 UTC

**Comment by mprimeaux** [comment] 2022-11-12 01:06
@thallgren thanks much for your help.

**Comment by yash-sarda** [comment] 2022-11-16 12:45
@thallgren I'm getting the same issue yet while trying to install telepresence on Mac.
Is the bug still open ? 
I have tried `brew cleanup ` method as suggested in the question. I have also tried to delete the file and reinstall telepresence again. Tried `brew update` and then reinstalling. So far nothing has worked.
Ca you help ?

**Comment by mprimeaux** [comment] 2022-11-16 12:56
To fix, I had to ‘brew uninstall telepresence’ and then ‘brew install’ the ARM version.
