### ISSUE TITLE
telepresence breaks the web if k8s namespace conflicts with TLD

### ISSUE THREAD

**Issue by richardscarrott** [telepresenceio/telepresence#2395] opened 2022-02-15 14:15 UTC
When telepresence is running (or maybe more accurately, when there's generated files in /etc/resolver) I cannot visit websites using 'dev' TLDs.

1. Create k8s namespace called 'dev'
2. Connect to telepresence
3. Go to `https://shopify.dev` in web browser
EXPECT: It to load the shopify.dev website
ACTUAL: It cannot resolve the domain

```
# Generated by telepresence
port 55356
domain dev
nameserver 127.0.0.1
```

```
Client: v2.4.10 (api v3)
Root Daemon: v2.4.10 (api v3)
User Daemon: v2.4.10 (api v3)
Mac OS (M1)
Google Kubernetes Engine
```

**Comment by thallgren** [comment] 2022-02-15 14:55
That's interesting. You have a namespace that collides with a top-level domain name. What happens is that telepresence redirects the lookup to be performed by the traffic-manager in the cluster, and there, the lookup fails. You can see this by doing:

```
$ telepresence connect
$ telepresence loglevel debug
$ kubectl -n ambassador logs -f traffic-manager-<generated suffix>
```
Now go to `https:://shopify.dev` in your browser and you'll probably see `LookupHost` calls returning `NOT FOUND` in the traffic-manager's log.

If this happens, then  telepresence does what it's supposed to. It redirects all names ending with a namespace to the cluster. The problem is that the cluster's DNS the fails to resolve the name, which is odd. Does your cluster have access to your workstations DNS? I.e. is it circling back just to fail on a recursion trap?

**Comment by richardscarrott** [comment] 2022-02-15 19:30
Thanks for the reply, I'm actually unable to reproduce the issue now but I can confirm I can see `shopify.dev` being redirected to the cluster, however it successfully resolves the domain at the moment:

```
2022-02-15 19:19:57.2878 debug   httpd/conn=127.0.0.1:8081 : LookupHost on agents: shopify.dev -> 34.138.230.116
```

A number of colleagues have also experienced the same problem however, so we'll try to figure out the exact steps to reproduce; I'm wondering if it's related to coming back after my [laptop has been asleep](https://github.com/telepresenceio/telepresence/issues/2244).

**Comment by richardscarrott** [comment] 2022-02-15 20:09
Ok I managed to "reproduce" the issue, but to do so I had to power off my computer while running tele which, upon turning it back on resulted in `/etc/resolver` sticking around while the telepresence daemon's are not running:

1. Create k8s namespace called 'dev'
2. Connect to telepresence
3. Turn computer off (pull the plug out)
4. Turn computer back on
5. Go to https://shopify.dev in web browser
EXPECT: It to load the shopify.dev website
ACTUAL: It cannot resolve the domain ❌
6. Run `telepresence connect`
7. Go to https://shopify.dev in web browser
EXPECT: it to load
ACTUAL: it loads ✅
8. Run `telepresence quit`
7. Go to https://shopify.dev in web browser
EXPECT: it to load
ACTUAL: it still loads ✅

I was unable to view the debug logs in traffic-manager, but I imagine it was never getting there anyway because the tele daemon's weren't even running?

So perhaps not a huge issue, especially now I understand how to resolve it.

**Comment by thallgren** [comment] 2022-02-21 11:01
Stray entries under `/etc/resolver` is something that we really try to avoid, but if the `telepresence daemon foreground` process is killed without a chance to clean-up, well, then they will be there. I'm closing this issue because I don't think there's much else we can do than clean up the next time telepresence is started.

**Closed as completed by thallgren** 2022-02-21 11:01 UTC

**Comment by scottillogical** [comment] 2022-02-24 18:25
We had the same issue, resolved by changing the namespace name from dev to something else
