### ISSUE TITLE
Telepresence in codespace: `telepresence connect: error: connector.Connect: rot daemon is not running`

### ISSUE THREAD

**Issue by billytrend-cohere** [telepresenceio/telepresence#3722] opened 2024-11-12 07:43 UTC
**Describe the bug**

I'm trying to run telepresence in a codespace. But I see an error. The `connector.log` containers no clues:

```
2024-11-12 07:12:05.1197 info    Starting socket listener for /tmp/telepresence-connector.socket
2024-11-12 07:12:05.1199 info    ---
2024-11-12 07:12:05.1199 info    Telepresence Connector v2.19.1 (api v3) starting...
2024-11-12 07:12:05.1199 info    PID is 5590
2024-11-12 07:12:05.1199 info    
2024-11-12 07:12:05.1241 info    connector/server-grpc : gRPC server started
2024-11-12 07:12:05.1524 info    connector/session : -- Starting new session
2024-11-12 07:12:05.1524 info    connector/session : Connecting to k8s cluster...
2024-11-12 07:12:05.9750 info    connector/session : Server version v1.30.5-gke.1014003
2024-11-12 07:12:05.9751 info    connector/session : Context: gke_cohere-staging_us-central1_staging
2024-11-12 07:12:05.9751 info    connector/session : Server: https://34.134.248.136
2024-11-12 07:12:08.5994 info    connector/session : Will look for traffic manager in namespace ambassador
2024-11-12 07:12:08.5994 info    connector/session : Connected to context gke_cohere-staging_us-central1_stagin
g, namespace default (https://34.134.248.136)
2024-11-12 07:12:08.7261 info    connector/session : Connecting to traffic manager...
2024-11-12 07:12:09.8815 info    connector/session : Connected to Traffic Manager v2.19.6
2024-11-12 07:12:10.0890 info    connector/session : Configuration reloaded
2024-11-12 07:12:11.1780 info    connector/session:shutdown_logger : shutting down (gracefully)...
2024-11-12 07:17:01.8274 info    connector/session : -- Starting new session
2024-11-12 07:17:01.8281 info    connector/session : Connecting to k8s cluster...
2024-11-12 07:17:02.1596 info    connector/session : Server version v1.30.5-gke.1014003
2024-11-12 07:17:02.1596 info    connector/session : Context: gke_cohere-staging_us-central1_staging
2024-11-12 07:17:02.1596 info    connector/session : Server: https://34.134.248.136
2024-11-12 07:17:03.4734 info    connector/session : Will look for traffic manager in namespace ambassador
2024-11-12 07:17:03.4735 info    connector/session : Connected to context gke_cohere-staging_us-central1_stagin
g, namespace default (https://34.134.248.136)
2024-11-12 07:17:03.5985 info    connector/session : Connecting to traffic manager...
2024-11-12 07:17:04.9262 info    connector/session : Connected to Traffic Manager v2.19.6
2024-11-12 07:17:05.1346 info    connector/session : Configuration reloaded
2024-11-12 07:17:05.1348 info    connector/session:shutdown_logger : shutting down (gracefully)...
```

**To Reproduce**

When I run 

```
telepresence connect --request-timeout=30s --kubeconfig ~/.kube/config --context xxx
```

I get `telepresence connect: error: connector.Connect: rot daemon is not running` (rot should be root)

**Expected behavior**

When I am running locally this connects my cluster to the context

**Versions (please complete the following information):**
 - Output of `telepresence version`
 
 ```
OSS Client             : v2.19.1
OSS Daemon in container: v2.19.1
Traffic Manager        : not connected
```
 
 - Operating system of workstation running `telepresence` commands
  
 codespace using `mcr.microsoft.com/devcontainers/universal:2` container

**Comment by thallgren** [comment] 2024-11-12 14:40
Telepresence requires `NET_ADMIN` capability and access to the `/dev/net/tun` device of the host that runs the codespace container, or it will fail to configure its virtual network device. Have you been able to configure that?

**Comment by billytrend-cohere** [comment] 2024-11-13 20:13
Hi @thallgren, thanks for your reply! I have taken a look and am still hitting the same issue. Are there some logs maybe that would reveal the underlying issue?

I have modified the codespaces with the following:

```
    "build": { "dockerfile": "../Dockerfile" },
    "runArgs": [
        "--privileged",
        "--cap-add=NET_ADMIN",
        "--device=/dev/net/tun"
    ],
```

I also tried `sudo setcap cap_net_admin+ep /usr/local/bin/telepresence`

`capsh --print` appears to show `cap_net_admin`:

``` 
WARNING: libcap needs an update (cap=40 should have a name).
Current: =
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,38,39,40
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=1000(codespace) euid=1000(codespace)
gid=1000(codespace)
groups=106(ssh),107(docker),989(pipx),990(python),991(oryx),992(golang),993(sdkman),994(rvm),995(php),996(conda),997(nvs),998(nvm),999(hugo),1000(codespace)
Guessed mode: UNCERTAIN (0)
```

**Comment by thallgren** [comment] 2024-11-13 22:03
You'll find the telepresence logs under ~/.cache/telepresence/logs. The ones of interest here are connector.log and daemon.log. They will become even more interesting if you turn on debugging by adding the following to ~/.config/telepresence/config.yml, then do `telepresence quit -s` and then retry the `telepresence connect`.

```yaml
logLevels:
  userDaemon: debug
  rootDaemon: debug
```

**Comment by thallgren** [comment] 2024-11-13 22:06
Also, if possible, please try version `2.20.2`. It contains several bugfixes that might affect the connect behavior.

**Comment by billytrend-cohere** [comment] 2024-11-13 22:46
With those settings, I do not see a `daemon.log`. `cli.log` is empty and `connector.log` shows the following:

Here is the log

```
2024-11-13 22:44:13.6774 debug   connector/server-grpc/conn=2/Quit-2 : called
2024-11-13 22:44:13.6775 debug   connector/session : goroutine "/connector/session" exited
2024-11-13 22:44:13.6775 debug   connector/server-grpc/conn=2/Quit-2 : returned
2024-11-13 22:44:13.6775 info    connector:shutdown_logger : shutting down (gracefully)...
2024-11-13 22:44:13.6775 debug   connector/background-metriton : goroutine "/connector/background-metriton" exited
2024-11-13 22:44:13.6775 debug   connector/service : goroutine "/connector/service" exited
2024-11-13 22:44:13.6779 debug   connector/server-grpc : gRPC server ended
2024-11-13 22:44:13.6780 debug   connector/server-grpc : goroutine "/connector/server-grpc" exited
2024-11-13 22:44:13.6945 debug   connector/config-reload : goroutine "/connector/config-reload" exited
2024-11-13 22:44:19.1720 info    Starting socket listener for /tmp/telepresence-connector.socket
2024-11-13 22:44:19.1721 debug   Listener opened on /tmp/telepresence-connector.socket
2024-11-13 22:44:19.1722 info    ---
2024-11-13 22:44:19.1722 info    Telepresence Connector v2.19.1 (api v3) starting...
2024-11-13 22:44:19.1722 info    PID is 8233
2024-11-13 22:44:19.1722 info    
2024-11-13 22:44:19.1728 info    connector/server-grpc : gRPC server started
2024-11-13 22:44:19.2051 debug   connector/server-grpc/conn=1/Connect-1 : called
2024-11-13 22:44:19.2065 debug   connector/session : using namespace "default"
2024-11-13 22:44:19.2066 info    connector/session : -- Starting new session
2024-11-13 22:44:19.2067 info    connector/session : Connecting to k8s cluster...
2024-11-13 22:44:19.4055 info    connector/session : Server version v1.30.5-gke.1014003
2024-11-13 22:44:19.4055 info    connector/session : Context: gke_cohere-staging_us-central1_staging
2024-11-13 22:44:19.4055 info    connector/session : Server: https://34.134.248.136
2024-11-13 22:44:21.1411 info    connector/session : Will look for traffic manager in namespace ambassador
2024-11-13 22:44:21.1411 info    connector/session : Connected to context gke_cohere-staging_us-central1_staging, namespace default (https://34.134.248.136)
2024-11-13 22:44:21.2272 info    connector/session : Connecting to traffic manager...
2024-11-13 22:44:21.2273 debug   connector/session : checking that traffic-manager exists
2024-11-13 22:44:21.2854 debug   connector/session : creating port-forward
2024-11-13 22:44:21.4406 debug   connector/session : k8sPortForwardDialer.dial(ctx, Pod./traffic-manager-68548bff4b-4976v.ambassador, 8081)
2024-11-13 22:44:21.4407 debug   connector/session : k8sPortForwardDialer.spdyDial(ctx, Pod./traffic-manager-68548bff4b-4976v.ambassador)
2024-11-13 22:44:21.9049 info    connector/session : Connected to Traffic Manager v2.19.6
2024-11-13 22:44:21.9601 debug   connector/session : traffic-manager port-forward established, client was already known to the traffic-manager as "codespace@codespaces-a36db9"
2024-11-13 22:44:22.0170 debug   connector/session : Applying client configuration from cluster
2024-11-13 22:44:22.0170 debug   connector/session : cluster:
2024-11-13 22:44:22.0170 debug   connector/session :     mappedNamespaces:
2024-11-13 22:44:22.0170 debug   connector/session :         - ambassador
2024-11-13 22:44:22.0170 debug   connector/session :         - blobheart
2024-11-13 22:44:22.0171 debug   connector/session :         - bh-finetuning
2024-11-13 22:44:22.0171 debug   connector/session :         - bh-private-models
2024-11-13 22:44:22.0171 debug   connector/session :         - bh-private-models-evaluation
2024-11-13 22:44:22.0172 info    connector/session : Configuration reloaded
2024-11-13 22:44:22.8895 debug   connector/server-grpc/conn=1/Connect-1 : returned
2024-11-13 22:44:22.8895 info    connector/session:shutdown_logger : shutting down (gracefully)...
2024-11-13 22:44:22.8896 debug   connector/session/info-kicker-gke_cohere-staging_us-central1_staging-default-cn : Deleting daemon info gke_cohere-staging_us-central1_staging-default-cn.json because context was cancelled
2024-11-13 22:44:22.8896 debug   connector/session/info-watcher-gke_cohere-staging_us-central1_staging-default-cn : goroutine "/connector/session/info-watcher-gke_cohere-staging_us-central1_staging-default-cn" exited
2024-11-13 22:44:22.8899 debug   connector/session/info-kicker-gke_cohere-staging_us-central1_staging-default-cn : goroutine "/connector/session/info-kicker-gke_cohere-staging_us-central1_staging-default-cn" exited

```

**Comment by billytrend-cohere** [comment] 2024-11-13 22:49
Is it possible that the root daemon is never run? I guess it's odd that we don't see a log for it. Also, I see that it maybe does not get run in "docker mode": https://github.com/telepresenceio/telepresence/blob/fce335576845968028964a807c559f1682279f49/pkg/client/cli/connect/daemon.go#L60

Alsooo `telepresence connect` only logs `Launching Telepresence User Daemon`. Should it also be logging that it is launching the root daemon?

Can i explicitly run the root daemon?

tysm for your support with this

**Comment by billytrend-cohere** [comment] 2024-11-13 22:55
Actually i'm possibly misunderstanding docker mode. That seems to be activated by a cli flag.

It is still weird though that we never see this log during connect:

https://github.com/telepresenceio/telepresence/blob/fce335576845968028964a807c559f1682279f49/pkg/client/cli/connect/daemon.go#L25

**Comment by thallgren** [comment] 2024-11-13 22:55
Sorry. I should have mentioned that in this configuration, the root daemon will run embedded in the connector process, so there will be no daemon.log.

**Comment by billytrend-cohere** [comment] 2024-11-14 00:02
I just tried running `2.20.2` and I still see `rot daemon is not running` unfortunately.

**Comment by billytrend-cohere** [comment] 2024-11-14 01:04
I built a version with this removed:

<img width="644" alt="image" src="https://github.com/user-attachments/assets/48c81c73-fe2d-4517-93d2-9043b3ba8ae0">

And I now see the `Launching Telepresence Root Daemon`:

```
Telepresence Daemons quitting...done
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
telepresence connect: error: connector.Connect: subnet 10.0.0.0/17 overlaps with existing route "10.0.0.0/16 via 10.0.0.70 dev eth0". Please see https://www.getambassador.io/docs/telepresence/latest/reference/vpn for more information
```

This feels like progress? or have i just broken it?

**Comment by billytrend-cohere** [comment] 2024-11-14 01:33
hmm added ` --allow-conflicting-subnets 10.0.0.0/16` to the command and it all seems to be up and healthy but doing some testing

**Comment by thallgren** [comment] 2024-11-14 07:38
This is interesting. Looks like you found the culprit!

As I wrote earlier, the root daemon is not supposed to run in this configuration (i.e. when the user daemon is running in a container), instead it will be embedded into the user daemon. However, that's when the user-daemon is *running as root*, and that doesn't seem to be the case here, and as a result, [this code](https://github.com/telepresenceio/telepresence/blob/release/v2/pkg/client/cli/connect/connector.go#L260-L268) doesn't execute. The user daemon, not receiving the `--embed-network` flag, then assumes that the root daemon is already running.

So, instead of just removing the `!daemon.GetUserClient(rc).Containerized()`, you should amend it with a `&& os.Getuid() == 0`, e.g.

```go
    if err == nil && required && !(os.Getuid() == 0 && daemon.GetUserClient(rc).Containerized())
```

**Comment by billytrend-cohere** [comment] 2024-11-14 23:08
Ty for confirming, have opened a pr!

**Comment by thallgren** [comment] 2024-11-15 12:34
@billytrend-cohere I've released a 2.20.3-rc.1 version of Telepresence with the codespaces fixes included. Can you please give it a try and report back?

**Comment by thallgren** [comment] 2024-11-18 17:14
Released in version 2.20.3

**Comment by billytrend-cohere** [comment] 2024-11-19 16:51
@thallgren sorry to reopen. I'm seeing behaviour where my urls are available in the codespace terminal but not in the k3d cluster that I'm running. I do see this warning:

```
You are using the OSS client v2.20.3-51-gfce335576-YvDDgqkcZvPrPIYWs18S2A to connect to an enterprise traffic manager v2.19.6. Please consider installing an
enterprise client from [getambassador.io](http://getambassador.io/), or use "telepresence helm install" to install an OSS traffic-manager
```

I wonder if this is causing the problem. Am I able to use the non oss cli with the fix we have merged?

**Comment by thallgren** [comment] 2024-11-19 17:12
That fix will probably be included when Ambassador Labs makes their next release., but you should be able to use the OSS client until then, if you can live with the warning.

Not sure what you mean by "urls are available in the codespace terminal", but unless it's the exact same problem that you reported earlier, I'd suggest you create a new ticket.

**Comment by lmtthws** [comment] 2024-12-11 00:42
I'm running into this same issue on the 2.20.3 client version. I'm not running in codespaces, but I am running VS Code inside a devcontainer locally, so really similar in terms of setup but I set up and run the container instead of some web server. When I run `telepresence connect` as non-root I get the `Launching Telepresence User Daemon` message and then the `telepresence connect: error: connector.Connect: root daemon is not running`. 

```bash
$ telepresence connect
Launching Telepresence User Daemon
telepresence connect: error: connector.Connect: root daemon is not running
```

If I run the command as root then I see the User Daemon start, presumably with the embedded root daemon, and things work. 

```bash
$ sudo telepresence connect --kubeconfig=/home/username/.kube/config
Launching Telepresence User Daemon
Connected to context ...
```

Similarly, if I remove the `/.dockerenv` file from the container's file system, then I see launches for both the User daemon and the Root daemon.

```bash
$ sudo rm /.dockerenv
$ telepresence connect
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
Connected to context ...
```

If I'm understanding this thread right, we want to start the root daemon if we're not in a container or we're in a container but not root? In that case, I think the change in 2.20.3 had a [small error](https://github.com/telepresenceio/telepresence/blob/v2.20.3/pkg/client/cli/connect/connector.go#L336) and should have been:

```go
defer func() {
		if err == nil && required && (!daemon.GetUserClient(rc).Containerized() || !proc.IsAdmin()) {
			// The RootDaemon must be started if the UserDaemon was started
			err = EnsureRootDaemonRunning(ctx)
		}
	}()
```

Or am I misunderstanding the cases where the root daemon should be started?

**Comment by thallgren** [comment] 2024-12-11 13:01
I believe that your condition `(!daemon.GetUserClient(rc).Containerized() || !proc.IsAdmin())` is the same as `!(daemon.GetUserClient(rc).Containerized() && proc.IsAdmin())`, i.e. (NOT A OR NOT B) is in fact the same as NOT (A AND B), and that's not the condition we're after.

Telepresence might still get confused by the `/.dockerenv` though. It shouldn't, so if that's the case, then I'd like to fix it.

Can you please try this with the [2.21.0-rc.2 release candidate](https://github.com/telepresenceio/telepresence/releases/tag/v2.21.0-rc.2) and see if that makes any difference?

**Comment by thallgren** [comment] 2024-12-11 16:58
@lmtthws  Never mind trying the rc.2. I found the problem. Will have a fix in rc.3.

**Comment by lmtthws** [comment] 2024-12-11 17:01
Okay, cool! I had just tried testing it and saw the same thing. Is the issue that we're doing `NOT (A OR B)` instead of `NOT (A AND B)` or something more complicated? 

Also, just noting for posterity, I had thought removing `/.dockerenv` worked around the issue, but I must have tested that incorrectly. In a fresh container when I tried that approach the root daemon would launch but then exit because it would try a code path to set up DNS resolution using systemd and dbus which isn't available in the container. Using sudo does work.

**Comment by thallgren** [comment] 2024-12-11 18:35
A bit more complicated, the full fix is in [this commit](https://github.com/telepresenceio/telepresence/commit/18245cfb8e981778f824c28bada0edc27d271045).

**Comment by thallgren** [comment] 2024-12-12 13:30
@lmtthws the [v2.21.0-rc.3 release candidate](https://github.com/telepresenceio/telepresence/releases/tag/v2.21.0-rc.3) is ready now. Please try it out.

**Comment by lmtthws** [comment] 2024-12-12 15:21
I'm giving it a shot, and I do see that it is starting the root daemon, but after it prints that it is launching the daemon, I get a timeout:

```bash
$ telepresence connect -n mynamespace --kubeconfig /workspaces/application/.kubeconfig
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
telepresence connect: error: connector.Connect: failed to connect to root daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded

See logs for details (2 errors found): "/home/code/.cache/telepresence/logs/daemon.log"
See logs for details (6 errors found): "/home/code/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

I have debug logging configured, and the daemon appears to be getting stuck on something right after getting the docker gateway IP address:

```
2024-12-12 08:42:02.6084 info    Telepresence daemon v2.21.0-rc.3 (api v3) starting...
2024-12-12 08:42:02.6085 info    PID is 242877
2024-12-12 08:42:02.6085 info    
2024-12-12 08:42:02.6092 debug   Listener opened
2024-12-12 08:42:02.6095 info    daemon/server-grpc : gRPC server started
2024-12-12 08:42:06.2371 debug   daemon/server-grpc/conn=4 : Received gRPC Connect
2024-12-12 08:42:06.2371 info    daemon/session : -- Starting new session
2024-12-12 08:42:06.4462 debug   daemon/session : Using WebSocket based port-forward to pod traffic-manager-5ccc56fd97-44wxf.ambassador
2024-12-12 08:42:07.0357 info    daemon/session : Connected to OSS Traffic Manager v2.19.1
2024-12-12 08:42:07.0358 info    daemon/session : Connected to Manager 2.19.1
2024-12-12 08:42:07.0358 debug   daemon/session : Creating session with id session_id:"c4c631be-c085-44f1-9cba-dc9b237dd0ca" cluster_id:"1211f7be-02d8-4874-ae11-49f13a7a12cc" install_id:"d4db2b2e-f3ed-4b6a-970e-aeb3f8360423"
2024-12-12 08:42:07.0358 info    daemon/session : also-proxy subnets []
2024-12-12 08:42:07.0358 info    daemon/session : never-proxy subnets [20.96.149.235/32]
2024-12-12 08:42:07.0359 info    daemon/session : allow-conflicting subnets []
2024-12-12 08:42:07.0359 info    daemon/session : Configuration reloaded
2024-12-12 08:42:07.0359 debug   daemon/session : Returning session from new session session_id:"c4c631be-c085-44f1-9cba-dc9b237dd0ca" cluster_id:"1211f7be-02d8-4874-ae11-49f13a7a12cc" install_id:"d4db2b2e-f3ed-4b6a-970e-aeb3f8360423"
2024-12-12 08:42:07.0802 debug   daemon/session/agentPods : WatchAgentPods starting
2024-12-12 08:42:07.1207 info    daemon/session/network : also-proxy subnets []
2024-12-12 08:42:07.1207 info    daemon/session/network : never-proxy subnets [20.96.149.235/32]
2024-12-12 08:42:07.1207 info    daemon/session/network : allow-conflicting subnets []
2024-12-12 08:42:07.1208 debug   daemon/session/network : Performing pod connectivity check on IP 10.230.13.20 with timeout 500ms
2024-12-12 08:42:07.1208 debug   daemon/session/agentPods : Using WebSocket based port-forward to pod mychart-chat-mediator-mr-16-f7887fcd6-8s8n5.mychart
2024-12-12 08:42:07.6214 warning daemon/session/network : Manager IP 10.230.13.20 is connectable but not a traffic-manager instance (rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded). Will proxy pods, but this may interfere with your VPN routes.
2024-12-12 08:42:07.6216 debug   daemon/session/network : Performing service connectivity check on https://10.0.36.29:443/healthz with Host agent-injector.ambassador and timeout 500ms
2024-12-12 08:42:07.6513 info    daemon/session/agentPods : Connected to OSS Traffic Agent v2.19.1
2024-12-12 08:42:08.1229 debug   daemon/session/network : Will proxy services (Get "https://10.0.36.29:443/healthz": context deadline exceeded)
2024-12-12 08:42:08.1229 debug   daemon/session/network : WatchClusterInfo update
2024-12-12 08:42:08.1229 info    daemon/session/network : Adding service subnet 10.0.0.0/16
2024-12-12 08:42:08.1229 info    daemon/session/network : Adding pod subnet 10.230.0.0/20
2024-12-12 08:42:08.1235 info    daemon/session/network : Creating routing table with index 779 and priority 32761
2024-12-12 08:42:08.1792 info    daemon/session/network : Setting cluster DNS to 10.230.13.20
2024-12-12 08:42:08.1793 info    daemon/session/network : Setting cluster domain to "cluster.local."
2024-12-12 08:42:08.1793 info    daemon/session/network : Dropping never-proxy "20.96.149.235/32" because it is not routed
2024-12-12 08:42:08.1794 info    daemon/session/network : Starting Endpoint
2024-12-12 08:42:08.4062 debug   daemon/session/network : UpdatinRoutes [10.0.0.0/16 10.230.0.0/20], [], []
2024-12-12 08:42:08.6793 debug   daemon/session/network : Opening traffic-agent tunnel for id tcp 172.17.0.2:44356 -> 10.0.36.29:443
2024-12-12 08:42:08.7977 error   daemon/session/dns/resolved : failed to connect to system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
2024-12-12 08:42:08.7978 error   daemon/session/dns/resolved : systemd-resolved is not running
2024-12-12 08:42:08.7978 info    daemon/session/dns : Unable to use systemd-resolved, falling back to local server
2024-12-12 08:42:08.7978 debug   daemon/session/dns/legacy : # Generated by telepresence

nameserver 10.142.39.231
nameserver 10.142.39.230
nameserver 1.1.1.1
nameserver 8.8.8.8

2024-12-12 08:42:08.7978 info    daemon/session/dns/legacy : Automatically set -dns=10.142.39.231
2024-12-12 08:42:08.8097 info    daemon/session/dns/legacy : started command ["docker" "inspect" "bridge" "-f" "{{(index .IPAM.Config 0).Gateway}}"] : dexec.pid="242943"
2024-12-12 08:42:08.8098 info    daemon/session/dns/legacy :  : dexec.pid="242943" dexec.stream="stdin" dexec.err="EOF"
2024-12-12 08:42:08.8888 info    daemon/session/dns/legacy :  : dexec.pid="242943" dexec.stream="stdout" dexec.data="172.17.0.1\n"
2024-12-12 08:42:08.8895 info    daemon/session/dns/legacy : finished successfully: exit status 0 : dexec.pid="242943"
```

Since there isn't an entry for `Bootstrapping local DNS server on port`, it seems like it's getting stuck in [the for loop looking for an available port](https://github.com/telepresenceio/telepresence/blob/v2.21.0-rc.3/pkg/client/rootd/dns/server_linux.go#L228)? We're not progressing to starting the DNS server or setting up the ip table rules.

If I run `daemon-foreground` with `sudo` it's getting stuck in the same place. 

A subsequent `telepresence quit -s` also takes a while to finish. I have to ctl-c the `daemon-foreground` if I'm running it separately. If I didn't run the daemon separately and just ran `telepresence connect`, the `quit` will output the following lines to the log (these occur immediately after the `finished successfully` log line above) and then hang. I've seen it hang indefinitely as when I ran `daemon-foreground` and also then terminate after a few minutes.

These lines are reliably getting logged when the quit is invoked:

```
2024-12-12 09:08:49.5974 debug   daemon/server-grpc/conn=5 : Received gRPC Quit
2024-12-12 09:08:49.5975 debug   daemon/session/agentPods : WatchAgentPods ending with 1 clients still active
2024-12-12 09:08:49.5976 info    daemon/session:shutdown_logger : shutting down (gracefully)...
2024-12-12 09:08:49.5976 error   daemon/session/agentPods : goroutine "/daemon/session/agentPods" exited with error: rpc error: code = Canceled desc = context canceled
2024-12-12 09:08:49.5980 debug   daemon/session/network : goroutine "/daemon/session/network" exited
2024-12-12 09:08:56.8591 debug   daemon/server-grpc/conn=6 : Received gRPC Quit
```

These lines showed up in an earlier test:

```
2024-12-12 08:29:23.1972 debug   daemon/server-grpc/conn=5 : Received gRPC Quit
2024-12-12 08:29:23.1981 info    daemon/session:shutdown_logger : shutting down (gracefully)...
2024-12-12 08:29:23.1986 debug   daemon/session/network : goroutine "/daemon/session/network" exited
2024-12-12 08:29:23.1992 debug   daemon/session/agentPods : WatchAgentPods ending with 1 clients still active
2024-12-12 08:29:23.1993 error   daemon/session/agentPods : goroutine "/daemon/session/agentPods" exited with error: rpc error: code = Canceled desc = context canceled
2024-12-12 08:29:30.4561 debug   daemon/server-grpc/conn=6 : Received gRPC Quit
2024-12-12 08:35:33.7287 debug   daemon/session : Bringing down TUN-device
2024-12-12 08:35:33.7482 error   daemon/session : failed to remove subnet 10.0.0.0/16: no such device
2024-12-12 08:35:33.7581 error   daemon/session : failed to remove subnet 10.230.0.0/20: Link not found
2024-12-12 08:35:33.7681 error   daemon/session/dns : goroutine "/daemon/session/dns" exited with error: unable to find a free port for both 127.0.0.1 and 172.17.0.1
2024-12-12 08:35:33.8091 debug   daemon/session/vif : vif ended
2024-12-12 08:35:33.8095 debug   daemon/session/vif : goroutine "/daemon/session/vif" exited
2024-12-12 08:35:33.8101 info    daemon/session:shutdown_status :   final goroutine statuses:
2024-12-12 08:35:33.8105 info    daemon/session:shutdown_status :     /daemon/session/agentPods: exited with error
2024-12-12 08:35:33.8105 info    daemon/session:shutdown_status :     /daemon/session/dns      : exited with error
2024-12-12 08:35:33.8105 info    daemon/session:shutdown_status :     /daemon/session/network  : exited
2024-12-12 08:35:33.8105 info    daemon/session:shutdown_status :     /daemon/session/vif      : exited
2024-12-12 08:35:33.8105 info    daemon/session : -- Session ended
2024-12-12 08:35:34.8457 error   daemon/session : rpc error: code = Canceled desc = context canceled
2024-12-12 08:35:34.8463 info    daemon/session : Configuration reloaded
2024-12-12 08:35:34.8463 debug   daemon/session : goroutine "/daemon/session" exited
2024-12-12 08:35:34.8464 info    daemon:shutdown_logger : shutting down (gracefully)...
2024-12-12 08:35:34.8464 debug   daemon/metriton : goroutine "/daemon/metriton" exited
2024-12-12 08:35:34.8584 debug   daemon/server-grpc : gRPC server ended
2024-12-12 08:35:34.8585 debug   daemon/server-grpc : goroutine "/daemon/server-grpc" exited
2024-12-12 08:35:34.8789 debug   daemon/config-reload : goroutine "/daemon/config-reload" exited
```

If I run `sudo telepresence connect` then everything works.

Also, there's a separate issue with mounts in this devcontainer/codespaces environment on the newer version (some time after 2.16.1) - I think it's because of a silent switch to local mount port if the mount is provided when the user daemon is containerized but nothing subsequently interacting with that port (presumably it's what the volume driver uses?). Would you prefer me to document that in a separate issue?

**Comment by thallgren** [comment] 2024-12-12 15:33
Thanks for testing and providing all that valuable info. I'll make some more tests in my own environment to see if I can reproduce.

**Comment by lmtthws** [comment] 2024-12-12 16:06
I think it might be that `SetRunningInContainer` addition now causing us to not quit early in the dnsListeners func. This docker gateway IP lookup and port search code path used to not be reachable when the daemon ran inside a container, looks like?

**Comment by thallgren** [comment] 2024-12-12 17:08
I've been looking at that code for a while now, and I'm fairly convinced that all that stuff concerning the docker bridge is actually old legacy that doesn't bring anything but harm. So I'm testing now, with all of that removed, and it seems to work fine in my codespace. I need to run more tests though, to verify that I don't break things by removing it.

**Comment by thallgren** [comment] 2024-12-12 19:26
Please try the [v2.21.0-rc.4](https://github.com/telepresenceio/telepresence/releases/tag/v2.21.0-rc.4). Mounts works from me in my codespace.

**Comment by lmtthws** [comment] 2024-12-12 20:25
This is great! Just tested and I'm seeing the same thing as you: I was able to connect without using `sudo` without issue and the mounts worked as expected. Thanks a lot!

**Comment by thallgren** [comment] 2024-12-13 11:56
Telepresence 2.21.0 has been released.

**Closed as completed by thallgren** 2024-12-13 11:56 UTC
