### ISSUE TITLE
[v2] DNS lookup fails

### ISSUE THREAD

**Issue by KhaledSakr** [telepresenceio/telepresence#1638] opened 2021-04-05 14:27 UTC
**Problem**
After installing telepresence v2 as described [here](https://www.getambassador.io/docs/telepresence/latest/howtos/intercepts/), and then running `telepresence connect`, I get the following message:
```
Launching Telepresence Daemon v2.1.3 (api v3)
Connecting to traffic manager...
Connected to context REDACTED (https://REDACTED:443)
```

but then, when I try to `curl -ik https://kubernetes.default`, I get the error:
```
curl: (6) Could not resolve host: kubernetes.default
```
This also happens if I try to curl any of the other services in my cluster.

**Additional data**
My resolve.conf is pretty basic, with only the following lines:
```
nameserver 192.168.86.1
nameserver 1.1.1.1
search lan
```
Additionally, when I run `systemd-resolve --status`, I get the following in addition to my `wlan0` link:
```
Link 24 (tel0)
      Current Scopes: DNS             
DefaultRoute setting: no              
       LLMNR setting: yes             
MulticastDNS setting: no              
  DNSOverTLS setting: no              
      DNSSEC setting: no              
    DNSSEC supported: no              
  Current DNS Server: 10.0.0.2        
         DNS Servers: 10.0.0.2        
          DNS Domain: ~ambassador     
                      ~default        
                      ~kube-node-lease
                      ~kube-public    
                      ~kube-system    
```

**Telepresence version**
Client v2.1.3 (api v3)

**OS**
- Ubuntu 20.04.2 LTS
- Linux kernel: 5.8.0-48-generic
- systemd 245 (245.4-4ubuntu3.4)

**Comment by thallgren** [comment] 2021-05-06 13:00
Please try again with the latest version of Telepresence. We've made some improvements to DNS. If it still fails, then please provide the ~/.cache/telepresence/logs/daemon.log file from the failing session.

**Comment by KhaledSakr** [comment] 2021-05-11 11:43
Unfortunately the issue still happens on v2.2.1.

Here's a gist with the log file content (with some service and pod names redacted): https://gist.github.com/KhaledSakr/d215621928cdbfbcab15bfcb32532de5

**Comment by thallgren** [comment] 2021-05-11 12:04
The problem is most likely this (from the daemon.log): `kubernetes.default.svc.cluster.local. -> 10.0.0.1`. It is the same address that we use for the TUN-device where we attach our DNS-resolver. We have a solution for that but it's in the making still.

**Comment by KhaledSakr** [comment] 2021-05-23 19:00
That's great to hear. I'm assuming that by "a solution is in the making" you mean that you're not expecting PRs for this, so I won't dig further. But if you need more logs or any additional info, feel free to send me.

**Comment by thallgren** [comment] 2021-06-07 09:26
@KhaledSakr the 2.3.0 version is out and it contains the solution that I mentioned before. Please giv it spin and check if it fulfills that promise.

**Comment by KhaledSakr** [comment] 2021-06-07 14:45
@thallgren Unfortunately, it's still not working. Still can't resolve the host. Here's the daemon.log: https://gist.github.com/KhaledSakr/4c26f8fb76de691f21951bd3e5f70a4a

**Comment by thallgren** [comment] 2021-06-07 16:28
Sorry to hear that. What kind of Kubernetes cluster are you connecting to? Also, what's the output from `systemd-resolve --status` when you use 2.3.0? The output of `ip a show` might also be helpful.

**Comment by KhaledSakr** [comment] 2021-06-07 16:49
It's an AKS cluster running v1.18.7.

This is the output of `systemd-resolve --status`
```
Global
       LLMNR setting: no                  
MulticastDNS setting: no                  
  DNSOverTLS setting: no                  
      DNSSEC setting: no                  
    DNSSEC supported: no                  
          DNSSEC NTA: 10.in-addr.arpa     
                      16.172.in-addr.arpa 
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa 
                      18.172.in-addr.arpa 
                      19.172.in-addr.arpa 
                      20.172.in-addr.arpa 
                      21.172.in-addr.arpa 
                      22.172.in-addr.arpa 
                      23.172.in-addr.arpa 
                      24.172.in-addr.arpa 
                      25.172.in-addr.arpa 
                      26.172.in-addr.arpa 
                      27.172.in-addr.arpa 
                      28.172.in-addr.arpa 
                      29.172.in-addr.arpa 
                      30.172.in-addr.arpa 
                      31.172.in-addr.arpa 
                      corp                
                      d.f.ip6.arpa        
                      home                
                      internal            
                      intranet            
                      lan                 
                      local               
                      private             
                      test                

Link 9 (tel0)
      Current Scopes: none            
DefaultRoute setting: no              
       LLMNR setting: yes             
MulticastDNS setting: no              
  DNSOverTLS setting: no              
      DNSSEC setting: no              
    DNSSEC supported: no              
          DNS Domain: ~ambassador     
                      ~default        
                      ~kube-node-lease
                      ~kube-public    
                      ~kube-system    
                      cluster.local   

Link 5 (br-f9b2d5b88d4b)
      Current Scopes: none
DefaultRoute setting: no  
       LLMNR setting: yes 
MulticastDNS setting: no  
  DNSOverTLS setting: no  
      DNSSEC setting: no  
    DNSSEC supported: no  

Link 4 (docker0)
      Current Scopes: none
DefaultRoute setting: no  
       LLMNR setting: yes 
MulticastDNS setting: no  
  DNSOverTLS setting: no  
      DNSSEC setting: no  
    DNSSEC supported: no  

Link 3 (wlan0)
      Current Scopes: DNS         
DefaultRoute setting: yes         
       LLMNR setting: yes         
MulticastDNS setting: no          
  DNSOverTLS setting: no          
      DNSSEC setting: no          
    DNSSEC supported: no          
  Current DNS Server: 192.168.86.1
         DNS Servers: 192.168.86.1
                      1.1.1.1     
          DNS Domain: ~.          
                      lan         
```

This is the output for `ip a show`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 18:1d:ea:9e:bc:63 brd ff:ff:ff:ff:ff:ff
    inet 192.168.86.35/24 brd 192.168.86.255 scope global dynamic noprefixroute wlan0
       valid_lft 86145sec preferred_lft 86145sec
    inet6 fe80::8a8b:7cc:24f1:1225/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:68:35:4e:4d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: br-f9b2d5b88d4b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2a:71:d7:df brd ff:ff:ff:ff:ff:ff
    inet 172.24.0.1/16 brd 172.24.255.255 scope global br-f9b2d5b88d4b
       valid_lft forever preferred_lft forever
9: tel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.0.0.0/16 scope global tel0
       valid_lft forever preferred_lft forever
    inet 10.244.10.0/24 scope global tel0
       valid_lft forever preferred_lft forever
    inet 10.244.12.0/24 scope global tel0
       valid_lft forever preferred_lft forever
    inet 10.244.17.0/24 scope global tel0
       valid_lft forever preferred_lft forever
    inet 10.244.9.0/24 scope global tel0
       valid_lft forever preferred_lft forever
    inet 10.244.11.0/24 scope global tel0
       valid_lft forever preferred_lft forever
    inet6 fe80::a033:a575:7785:b456/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

**Comment by thallgren** [comment] 2021-06-07 21:08
Can you please enable debug logging for the daemon and check the traces (if any) that you see in the daemon.log when you curl the host? You can set the log level by adding:
```
logLevels:
  rootDaemon: debug
```
to the file `~/.config/telepresence/config.yml`

**Comment by ventsislav-georgiev** [comment] 2022-07-07 16:08
Getting the same issue sporadically. Here is the log from the daemon:
```
2022-07-07 19:03:16.3628 info    Telepresence daemon v2.6.8 (api v3) starting...
2022-07-07 19:03:16.3628 info    PID is 99371
2022-07-07 19:03:16.3628 info    
2022-07-07 19:03:16.3716 info    daemon/server-grpc : gRPC server started
2022-07-07 19:03:21.4990 info    daemon/session : -- Starting new session
2022-07-07 19:03:21.5021 info    daemon/session : Connected to Manager 2.6.8
2022-07-07 19:03:21.5217 info    daemon/session : Adding never-proxy subnet 127.0.0.1/32
2022-07-07 19:03:27.3906 info    daemon/session/watch-cluster-info : Setting cluster DNS to 10.43.0.10
2022-07-07 19:03:27.3907 info    daemon/session/watch-cluster-info : Setting cluster domain to "cluster.local."
2022-07-07 19:03:27.3907 info    daemon/session/watch-cluster-info : Adding service subnet 10.43.0.0/16
2022-07-07 19:03:27.3907 info    daemon/session/watch-cluster-info : Adding pod subnet 172.17.0.0/24
2022-07-07 19:03:27.3917 info    daemon/session/dns : Generated new /etc/resolver/telepresence.local
2022-07-07 19:03:27.3918 info    daemon/session/dns/SearchPaths : setting search paths ambassador default kube-node-lease kube-public kube-system
2022-07-07 19:03:27.3977 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.default.local
2022-07-07 19:03:27.3980 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.kube-node-lease.local
2022-07-07 19:03:27.3982 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.kube-public.local
2022-07-07 19:03:27.3985 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.kube-system.local
2022-07-07 19:03:27.3988 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.tel2-search.local
2022-07-07 19:03:27.3990 info    daemon/session/dns/SearchPaths : Generated new /etc/resolver/telepresence.ambassador.local
2022-07-07 19:03:37.4181 error   daemon/session/dns/SearchPaths : recursion check failed. The DNS isn't working properly
```

added:
```
logLevels:
  rootDaemon: debug
```
in. the config but doesn't seem to change the log output.

This is on macOS with arm CPU.

**Comment by ventsislav-georgiev** [comment] 2022-07-07 16:59
Rebuilding the telepresence cli with CGO_ENABLED=0 seem to solve it.

**Comment by thallgren** [comment] 2022-11-14 02:04
Closing this as the issues reported here it were resolved a long time ago.

**Closed by thallgren** 2022-11-14 02:04 UTC
Labels: t:bug, v2
